### ISSUE TITLE
Finish updating time zone conversion 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1000]
## 📋 Summary
Make sure that the conversion from UTC to CST is working correctly.

- [x] Update in test file
- [x] Update in documentation
- [x] Add in adjustment from UTC-6 to UTC-5 for Daylight Savings Time (second Sunday in March to first Sunday in November)
- [x] QA in "production file"

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by JonErvin** [comment]
@JTBassett @joseluisrangel-dataheim I think this is good to go in both [testing](https://docs.google.com/spreadsheets/d/1FKw4C6Cw0oQT6YJX8GoSZ5p4-7YaOGIxDe20tb-SaSM/edit#gid=573732413) and [NECC](https://docs.google.com/spreadsheets/d/1TMfnOwR7PILhj9xNwzQf7Ejkz944jAMjCLHY-Sog8L8/edit#gid=573732413).  In testing, I've replaced the dummy WS attendance data with the same data, just ahead 6 hours to convert it to UTC input.  Then, in Daily Calculation, I use the same formula we dropped into the NECC doc to subtract 6 hours and convert to Central Time (this assumes providers are Central for now).  Both original and adjusted dataset in testing are here if we need them: https://docs.google.com/spreadsheets/d/1OmvrmFeDIKl-2hMi18YP3MLlux80bAju1_ZWPp9k7i8/edit?usp=sharing

JT and Jose any chance one of you could do a quick QA for this issue?

**Comment by JTBassett** [comment]
@JonErvin you've got a 👍 from me!

**Comment by JonErvin** [comment]
Opened back up to address daylight savings issues beginning second Sunday in March

**Comment by JonErvin** [comment]
@joseluisrangel-dataheim Now this should be good to go - could you QA again for me when you have a minute please :)
