### ISSUE TITLE
Check on failed rspec seeds

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1016]
## 📋 Summary
Search for: `# TODO: check time calculation`

failed seeds:

- [ ] 34588
- [ ] 64502
- [ ] 19218
- [ ] 15349
- [x] 39542

@csprayregen no need to prioritize this - just a cleanup task for trying to track down some flaky specs

**Comment by csprayregen** [comment]
Will prioritize in the bucket of tech debt cleanup for after NE formulas are implemented (or earlier if we can get others to contribute) @katelovescode
