### ISSUE TITLE
Production dashboard not rendering all data correctly

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1017]
## 🤬 What's wrong?
One field for one child is showing up differently from the dashboard being uploaded thru S3. All other fields appear to be working (though there could be other issues with this child upon further investigation). 

ID of individual with data issue: 7f325b31-ba33-4688-aa38-2290b5710176
Field with bug: estimated revenue
(All other fields are correctly displaying as zero)

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

## 🏓 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by katelovescode** [comment]
Fixing this manually; there were commas in the monetary fields in the csv
