### ISSUE TITLE
pie_erd.pdf

### ISSUE THREAD

**Issue by jhsu802701** [pieforproviders/pieforproviders#1030]
## 🤬 What's wrong?
The pie_erd.pdf file is in the repository.

## 👉🏼 Steps to Reproduce

It's created when running "rails db:setup" or "bundle exec rake db::migrate".

## 🧥Expected behavior

I'm all for using the rails-erd tool, but shouldn't the block diagram files be kept out of the source code?

## Solutions
* The "git rm" command can delete this file from the repository.  In addition, there should be a way to keep the pie_erd.pdf file out of the repository.
* One possible solution is to add pie_erd.pdf to .gitignore.
* Another possible solution is to edit the script that generates this file to automatically move it into the tmp directory

**Comment by katelovescode** [comment]
Thanks for the suggestion! Our preference is actually to keep it in the repository so we all have a shared understanding of the data model that's publicly displayed without having to run the ERD commands.  Some of our repo users are non-technical folks and do not run the code locally.
