### ISSUE TITLE
I can retrieve weekly hours used from the API for the NE dashboard

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1034]
✨ What new feature do you want to see?
The API returns the hours used per week column/field for the Nebraska dashboard

🧶 Acceptance Criteria
- [x] Ticket #1035 has the necessary query for this data documented
- [ ]  This matches formulas laid out by the data team
- [ ] This passes test cases

🥧 Additional context
Figma link for reference of initial implementation of this query on the front-end (see V2): https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4538%3A16605

**Implementation Details**

![Screen Shot 2021-06-21 at 3 32 09 PM](https://user-images.githubusercontent.com/8364647/122824133-da5e9300-d2a5-11eb-8098-0500eca49324.png)

This implements the "Hours attended" for a particular week span.

Notes to consider while implementing/Acceptance Criteria:
- Hours attended will *always* (in current state) display the *week (Sun - Sat) of the last elapsed day in that month* chosen in the filter.  i.e. if today is June 21st, 2021, and we're looking at June of 2021, the Hours Attended column will display June 20th to June 26th (Sun - Sat).  If I go back to May of 2021 using the date filter, the Hours Attended column will display May 30th to June 5th.  The front end takes care of displaying these dates, but the backend needs to make sure it only returns data for those dates.
  - **OPEN QUESTIONS**
    - what happens when a week is split between months?
- The display of these hours will be X (completed hours this week) of X (approved hours this week)
  - **OPEN QUESTIONS**
    - I believe approved hours this week should be stored on the `child_approval` level - right now anything that is at the child-level and doesn't have its effective/expiration date impacted by the subdivisions of Nebraska Approval Amounts (i.e. it shares its effective/expiration date with the approval as a whole) belongs here - need to confirm this with the data team
- as a part of this ticket, `approved_hours_this_week` will need to be added to the `child_approval` table 
- completed hours is a sum of all the hours of attendance for this week, whether or not they counted as a daily unit or an hourly unit (sum of `total_time_in_care` for all the attendances of the week)
- this should all be put behind a feature flag to determine if we're using live algorithms or not (see PRs for https://github.com/pieforproviders/pieforproviders/issues/698 and https://github.com/pieforproviders/pieforproviders/issues/714 as an example)

**Comment by katelovescode** [comment]
@csprayregen  testing instructions are on the PR: #1068

**Comment by JonErvin** [comment]
Looks good in my opinion!  To the question on weeks that span two month, our understanding is that its independent of the month.  So in May 30th-June 5th, that is a valid week in both May and June.  Believe this applies across years as well.
