### ISSUE TITLE
I can view dynamic data for hours used per week in the NE dashboard 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1035]
## ✨ What new feature do you want to see?
I can see the "hours" column in the table on my NE dashboard table

## 🧶 Acceptance Criteria
- [x] I can see the "hours used so far this week" for the current week for the children associated with my account in the dashboard table
- [x] In the same column, I can see the "max hours for this week" for the current week for the children associated with my account in the dashboard table
- [x] The top of the column has the dates of the current week (Sunday 12am-Saturday 11:59am). 
- [ ] When I use date filtering to look at previous months, the dates at the top of the column do not appear. OPEN QUESTION: should the column disappear as a whole? Just be blank? What's the easiest way to implement this that is still clear to the user? 
- [x] I can click the question mark at the top of this column to move to the definitions panel
- [x] I can see the definition for this column in my definitions panel
- [x]  The above criteria work in both English and Spanish
- [ ]  Verify accessibility (see details below)

## 🖍️ Implementation Details
NOTE: WE HAVE AN OPEN QUESTION ABOUT WHAT DAYS THE WEEK STARTS ON - For now, we are developing this based on an assumption of Sun-Sat, but please confirm before implementing to see if we have received more info. 

UPDATE: @cjhaddad this is now answered (Sunday 12am-Saturday 11:59am). Additionally, Kate says, "I think this should be a front-end ticket; the front end date library should be able to calculate what week it is in the current month and display the dates." 

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🥧 Additional context
New column is reflected in the Nebraska V2 mockup here. However, there is a pending change to hours used (not hours left) to match the other attendance columns: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4538%3A16605

**Comment by katelovescode** [comment]
@csprayregen do you mean the planned implementation is Sun-Sat or Mon-Sun?  Sun-Mon would be more than a week (or it would be one day :D )

**Comment by csprayregen** [comment]
@katelovescode Sunday-Saturday! Changing

**Comment by csprayregen** [comment]
@cjhaddad we got an answer from NE on when the week starts and ends: Sunday 12am-Saturday 11:59am

**Comment by csprayregen** [comment]
@cjhaddad a few issues here:
- [ ] The weekly date is not appearing correctly in English. It currently says March 28-Mar 3 (I think this is meant to be Apr)
- [ ] The weekly date is not translating into Spanish (I think you already have the month abbreviation translations - can you re-use those?)

Then some more general questions:

- What is the current expected behavior for this column if I use date filtering and look at previous months? That last week of the month they're viewing? If it's not what we want, I can ticket that separately, but want to check in about it. 
-In weeks like the current one, which includes both March and April, we want the user to see every day of the week, even if it includes different months. Is that the current behavior? (I'm not sure, given the issue noted above)

**Comment by cjhaddad** [comment]
> @cjhaddad a few issues here:
> 
> * [ ]  The weekly date is not appearing correctly in English. It currently says March 28-Mar 3 (I think this is meant to be Apr)
> * [ ]  The weekly date is not translating into Spanish (I think you already have the month abbreviation translations - can you re-use those?)
> 
> Then some more general questions:
> 
> * What is the current expected behavior for this column if I use date filtering and look at previous months? That last week of the month they're viewing? If it's not what we want, I can ticket that separately, but want to check in about it.
>   -In weeks like the current one, which includes both March and April, we want the user to see every day of the week, even if it includes different months. Is that the current behavior? (I'm not sure, given the issue noted above)

will check out why it isn't appearing correctly! yes, I can reuse those translations!

-- let's discuss your general functionality questions tomorrow at our check-in @csprayregen

**Comment by csprayregen** [comment]
@cjhaddad confirming that the two specific questions now look good. Will leave this open until we connect live tomorrow.

**Comment by csprayregen** [comment]
Candice: currently renders only the current week regardless of date filtering. Could add additional logic to show last week or whatever we want to render. @csprayregen ticket separately.
