### ISSUE TITLE
The NE low code prototype can accommodate the new Family Fee field in the table

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1036]
## 📋 Summary
We have removed Transportation revenue from the NE dashboard table and removed it with a Family Fee field. The data/spreadsheet changes for this are in #1037 .

To implement this in the low code prototype:
- [ ] Update dashboard rake task/spreadsheet parser and model to accept this field
- [ ] Update api case_list_for_dashboard to return this field
- [ ] Connect with Jon to specify formatting details for this field in the S3 upload spreadsheet and which column number to add this field to

## 💻 Implementation Details
New column is reflected in the Nebraska V2 mockup here. https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4538%3A16605

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by katelovescode** [comment]
@csprayregen testing instructions are on the PR: https://github.com/pieforproviders/pieforproviders/pull/1067

**Comment by csprayregen** [comment]
- [ ] try to process a spreadsheet in the old format (with Transportation revenue) - it should work without throwing errors
- [ ] try to process a spreadsheet in the new format (with Family Fee) - it should work without throwing errors
- [ ] the front end should load correctly without throwing errors
- [ ] when you hit the api for /case_list_for_dashboard transportation fee should be gone and family fee should be present

**Comment by csprayregen** [comment]
@katelovescode the above AC work, but my questions are:
-Should I see the dashboard data I uploaded in the app in staging? I don't. But I'm confused about how that dummy data is working, so this may be a non-issue
-

**Comment by csprayregen** [comment]
Error on the version with Family Fee:

 ›   Warning: heroku update available from 7.50.0 to 7.51.0.
Running bundle exec rails read_wonderschool_necc_dashboard_cases on ⬢ pie-staging... up, run.8601 (Hobby)
I, [2021-03-27T13:20:27.784255 #4]  INFO -- : Raven 3.1.1 ready to catch errors
I, [2021-03-27T13:20:28.663594 #4]  INFO -- : Sending event 93d05911a9cf4e0b8a0a62e9c465c7df to Sentry
D, [2021-03-27T13:20:28.675297 #4] DEBUG -- : Raven HTTP Transport connecting to https://o379991.ingest.sentry.io
rails aborted!
CSV::MalformedCSVError: Invalid byte sequence in UTF-8 in line 1.
/app/vendor/ruby-2.6.6/lib/ruby/2.6.0/csv/parser.rb:711:in `build_scanner'
/app/vendor/ruby-2.6.6/lib/ruby/2.6.0/csv/parser.rb:297:in `parse'
/app/vendor/ruby-2.6.6/lib/ruby/2.6.0/csv.rb:1236:in `each'
/app/vendor/ruby-2.6.6/lib/ruby/2.6.0/csv.rb:1236:in `each'
/app/vendor/ruby-2.6.6/lib/ruby/2.6.0/csv.rb:1245:in `to_a'
/app/vendor/ruby-2.6.6/lib/ruby/2.6.0/csv.rb:1245:in `read'
/app/vendor/ruby-2.6.6/lib/ruby/2.6.0/csv.rb:685:in `parse'
/app/app/services/wonderschool/necc/dashboard_processor.rb:72:in `parse_string_to_csv'
/app/app/services/wonderschool/necc/dashboard_processor.rb:41:in `convert_by_type'
/app/app/services/wonderschool/necc/dashboard_processor.rb:24:in `read_contents'
/app/app/services/wonderschool/necc/dashboard_processor.rb:18:in `call'
/app/app/services/wonderschool/necc/dashboard_downloader.rb:32:in `process_file'
/app/app/services/wonderschool/necc/dashboard_downloader.rb:26:in `block in download_dashboard_exports'
/app/app/services/wonderschool/necc/dashboard_downloader.rb:25:in `each'
/app/app/services/wonderschool/necc/dashboard_downloader.rb:25:in `download_dashboard_exports'
/app/app/services/wonderschool/necc/dashboard_downloader.rb:10:in `call'
/app/lib/tasks/read_wonderschool_necc_dashboard_cases.rake:4:in `block in <main>'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.3/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.3/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.3/lib/rails/command.rb:52:in `invoke'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.3/lib/rails/commands.rb:18:in `<main>'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
Tasks: TOP => read_wonderschool_necc_dashboard_cases
(See full trace by running task with --trace)
chelseasprayregen@Chelseas-MacBook-Pro ~ % heroku run bundle exec rails read_wonderschool_necc_dashboard_cases --app pie-staging

 ›   Warning: heroku update available from 7.50.0 to 7.51.0.
Running bundle exec rails read_wonderschool_necc_dashboard_cases on ⬢ pie-staging... up, run.4041 (Hobby)
I, [2021-03-27T13:24:36.661859 #4]  INFO -- : Raven 3.1.1 ready to catch errors
D, [2021-03-27T13:24:37.356782 #4] DEBUG -- :   Business Load (1.0ms)  SELECT "businesses".* FROM "businesses" WHERE "businesses"."name" = $1 LIMIT $2  [["name", "Little Sprouts Daycare"], ["LIMIT", 1]]
D, [2021-03-27T13:24:37.374432 #4] DEBUG -- :   Child Load (1.0ms)  SELECT "children".* FROM "children" WHERE "children"."full_name" = $1 AND "children"."business_id" IS NULL LIMIT $2  [["full_name", "Chi Delta"], ["LIMIT", 1]]
D, [2021-03-27T13:24:37.377872 #4] DEBUG -- :   Business Load (2.5ms)  SELECT "businesses".* FROM "businesses" WHERE "businesses"."name" = $1 LIMIT $2  [["name", "Little Sprouts Daycare"], ["LIMIT", 1]]
D, [2021-03-27T13:24:37.380220 #4] DEBUG -- :   Child Load (0.9ms)  SELECT "children".* FROM "children" WHERE "children"."full_name" = $1 AND "children"."business_id" IS NULL LIMIT $2  [["full_name", "Epsilon Phi"], ["LIMIT", 1]]
E, [2021-03-27T13:24:37.380672 #4] ERROR -- : [NECC Dashboard cases failed to process] ["As of Date", "2/19/2020", "Child Name", "Chi Delta", "Case Number", "234567890", "Business", "Little Sprouts Daycare", "Full Days", "13 of 20", "Hourly", "0 of 0", "Absences", "1 days, 0 hours", "Status", "on_track", "Earned revenue", "417.9", "Estimated Revenue", "653.1", "Approved (Scheduled) revenue", "619.5", "Family Fee", "653.1", "As of Date", "2/19/2020", "Child Name", "Epsilon Phi", "Case Number", "234567890", "Business", "Little Sprouts Daycare", "Full Days", "13 of 20", "Hourly", "18 of 27", "Absences", "1 days, 3 hours", "Status", "on_track", "Earned revenue", "556.45", "Estimated Revenue", "853.13", "Approved (Scheduled) revenue", "801.83", "Family Fee", "853.13"]
E, [2021-03-27T13:24:37.527305 #4] ERROR -- : [NECC Dashboard] Family fee S3 testing - Sheet1.csv
chelseasprayregen@Chelseas-MacBook-Pro ~ % 

Spreadsheet I used in Drive is here (I can't upload CSVs, but I downloaded exactly as is as a CSV and can Slack you that file): https://docs.google.com/spreadsheets/d/1t1YffEs1trJSEoOqZDr80jQeZX1EjHnxLcqBsRtAM6o/edit#gid=0
