### ISSUE TITLE
I can retrieve Family Fee from the API for the NE dashboard 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1038]
✨ What new feature do you want to see?
The API returns the family fee column/field for the Nebraska dashboard

🧶 Acceptance Criteria
- [x] Ticket #1039 has the necessary query for this data documented
- [ ]  This matches formulas laid out by the data team
- [ ] This passes test cases

🥧 Additional context
Figma link for reference of initial implementation of this query on the front-end (see V2): https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4538%3A16605

**Comment by katelovescode** [comment]
@csprayregen testing instructions are on the PR: https://github.com/pieforproviders/pieforproviders/pull/1067

**Comment by katelovescode** [comment]
@csprayregen the description of this is the same as hours used, just want to make sure the real description should just be "I can retrieve the family fee" - which is added during onboarding, correct?  So that's just flat-out displaying the family fee from when we stored it in the db?

**Comment by csprayregen** [comment]
@katelovescode yes this is all correct! Just a copy-paste fail on my end, now updated.
