### ISSUE TITLE
I can view dynamic data for Family Fee in the NE dashboard

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1039]
## 🧶 Acceptance Criteria
- [x] I can no longer see the Transportation Revenue column of my NE dashboard
- [x] Instead, I see a Family Fee column on the dashboard in place of the transportation revenue column
- [x] I can see dynamic data for Family Fee for the children associated with my account 
- [x] The definition of Family Fee is included in the definition section (see copy from the mockup)
- [x] The Transportation Revenue definition is removed from the definitions section of my dashboard
- [x] The above criteria work in both English and Spanish
- [ ] Verify accessibility (see details below)
- [ ] TO DISCUSS: if I look at a previous month for which there is no family fee information, what does the user see? Assume family fee is $0 for that month? Say unknown or n/a? 

## 🖍️ Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🥧 Additional context
Figma link for reference (see V2): https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4538%3A16605

**Comment by katelovescode** [comment]
New shape of data has been stored in Postman documentation, I'll walk through this with @cjhaddad on Sunday

**Comment by csprayregen** [comment]
@cjhaddad the sort function appears to be broken on this column. Here is the error I get when I click it. If I refresh from there, I am still logged in and looking at my dashboard again (I'm in Chrome, Mac, all up to date):

<img width="1440" alt="Screen Shot 2021-04-01 at 8 05 40 AM" src="https://user-images.githubusercontent.com/26717304/113298169-27dbed00-92c1-11eb-94c3-d151bca61a4a.png">

**Comment by cjhaddad** [comment]
> @cjhaddad the sort function appears to be broken on this column. Here is the error I get when I click it. If I refresh from there, I am still logged in and looking at my dashboard again (I'm in Chrome, Mac, all up to date):
> 
> <img alt="Screen Shot 2021-04-01 at 8 05 40 AM" width="1440" src="https://user-images.githubusercontent.com/26717304/113298169-27dbed00-92c1-11eb-94c3-d151bca61a4a.png">

ah! yes, let me check this out and fix!
