### ISSUE TITLE
The NE low code prototype can accommodate the absence field in the table

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1044]
## 📋 Summary
The data team is updating the Absences formula (see #982) - it is not currently integrated into formulas. When this is implemented, we will want to be able to pull these from the spreadsheet to the dashboard as part of our low code prototype. The below may already be implemented, but I'm creating this ticket to confirm. 

## 💻 Implementation Details

- [ ]  Update dashboard rake task/spreadsheet parser and model to accept this field
- [ ]  Update api case_list_for_dashboard to return this field
- [ ]  Connect with Jon to specify formatting details for this field in the S3 upload spreadsheet and which column number to add this field to

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by katelovescode** [comment]
Closed as duplicate work
