### ISSUE TITLE
As a user, after uploading a spreadsheet without using the template, I can view my fields and match them to column names

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#105]
## ✨ What new feature do you want to see?
After I use a spreadsheet that does not match Pie's spreadsheet, I can view my uploaded spreadsheet fields and match them to column names 

## 🧶 Acceptance Criteria
-If the user completes the spreadsheet upload (#71) but does not use the template spreadsheet, no columns are recognized
 -The user can click "edit" on every column header to select a new column name
-The following validations are activated when the user selects a column:
   -Date of birth: valid date
   -Site: must match sites that were previously added
   -Full days: valid number
   -Part days: valid number
   -Effective on: valid date
   -Expires on: valid date 
   -Co-pay frequency: can only be "Daily" "Weekly" or "Monthly"
-The following validations are activated when the user clicks "next"
   -First name: required
   -Last name: required
   -Date of birth: required 

## 🖍️ Implementation Details
Upload covered in #36 
Accessing and using the template is covered in #71 
If the user completes the upload with a template, see issue #72  

## 🥧 Additional context
Designs: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=313%3A183
Validation designs: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=313%3A20

**Comment by rebeccakarasiktw** [comment]
As per discussion with @katelovescode and @csprayregen I am adding the "icebox" label to this and not updating the designs (for now).
