### ISSUE TITLE
Attendance risk tags not appearing correctly on NE dashboard

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1056]
## 🤬 What's wrong?
All attendance risk tags are appearing as "Not Enough Info" on the NE dashboard low code prototype, even though the uploaded spreadsheets have other labels. 

## 🏓 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by cjhaddad** [comment]
Made adjustments to spreadsheet to trim the excess whitespace in attendance risk labels. This should now fix how the frontend identifies which label to show.
