### ISSUE TITLE
As a user, I can associate agencies with subsidy cases and add new agencies

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#109]
## ✨ What new feature do you want to see?
We need to figure out how users will add new agencies and/or select from a list of existing agencies in order to associate each subsidy case with an agency. We decided not to include this in the initial dashboard creating and child/case upload process, because we don't know enough about how the billing reconciliation features will look yet. We will need to come back to this. 

## 🧶 Acceptance Criteria

- Users will see a list of all the children that were uploaded in the spreadsheet (default sort)
- Users can sort the list by Site
- Assign agencies from a pre-existing list
- Users can re-assign agencies to children
- Once all children in the list have been assigned, the button is enabled. 

## 🖍️ Implementation Details
Link to FIgma: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=1401%3A1961

**Comment by csprayregen** [comment]
@rebeccakarasiktw pulled this old issue into the To Do column. As discussed last night, we will add a new Step into the onboarding flow in which users will select the subsidy agencies that pay them from a dropdown we create (per state), and then they will associate uploaded cases with agencies.

**Comment by rebeccakarasiktw** [comment]
@csprayregen I added the link to Figma and added some prelim A/C. We should discuss how to split into additional stories (for example, adding agencies from another state, etc.)
