### ISSUE TITLE
As a user, I can log into my account

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#11]
## ✨ What new feature do you want to see?
I can log into my account

## 🏖 Implementation Details
- we'll probably want to make an authenticated view and a public view to distinguish (even just a placeholder dashboard for the auth'ed user, and a "hi" landing page for the public view)
- Devise?  JWT/token exchange?  What we doin

## 🥞Additional context
- I've been back and forth on authentication methods and I haven't decided yet what we're going to do, this is kind of "needs more info"

**Comment by katelovescode** [comment]
@jessehall3

**Comment by jessehall3** [comment]
@katelovescode 

Tuesday update:
- I was able to get everything up and running just fine, thanks for all the details in the readme.
- Regarding authentication -- I am looking into [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) as it's the most popular of all [the alternatives listed](https://github.com/heartcombo/devise/wiki/How-To:-Simple-Token-Authentication-Example#alternatives) by devise. I hope to report back once I have something working in a fork of this project.

**Comment by katelovescode** [comment]
@jessehall3 if you're going to work on this, can you assign the ticket to yourself and move it into "In Progress" on the Project board, just so someone doesn't steal it from you or double your work!

**Comment by jessehall3** [comment]
@katelovescode No problem, doing that now.
