### ISSUE TITLE
As a user, I can enter a site QRIS rating and have that factored into my subsidy billing calculations

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#111]
We currently have QRIS rating as a field in the State Rules table. However, we don't yet know how we will collect this info from users. It is currently not part of onboarding but may need to be in the future. Adding to the backlog so we don't lose this.

**Comment by weedySeaDragon** [comment]
@csprayregen  Is this site good info about what "QRIS" is? 
https://www.childcareaware.org/families/child-care-quality-ratings/

**Comment by csprayregen** [comment]
@weedySeaDragon yes it is! I can also answer questions/give you the 101 over Slack.

**Comment by csprayregen** [comment]
We are now collecting this thru on the onboarding spreadsheet, and we are factoring qris into the algorithms we're building in the no code prototype, which will affect the app algorithm too
