### ISSUE TITLE
As a user I can tell what site I'm on in the tab title

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#112]
## ✨ What new feature do you want to see?

We need "Pie for Providers" and our favicon in the tab title

## 🧶 Acceptance Criteria

I can see "Pie for Providers" and our favicon in the tab title instead of the default React app stuff

## 🏖 Implementation Details
Link to SVG: https://drive.google.com/open?id=1f7o0tODOH_G2fQYQCa67oYG9jokG9iCj please talk to @katelovescode to access the google drive link

https://create-react-app.dev/docs/title-and-meta-tags/
https://medium.com/@jenniferdobak/the-public-folder-and-favicons-in-create-react-app-8dc2cc1d492b

**Comment by rebeccakarasiktw** [comment]
Uploading logo for favicon FYI @katelovescode

**Comment by rebeccakarasiktw** [comment]
Link to SVG: https://drive.google.com/open?id=1f7o0tODOH_G2fQYQCa67oYG9jokG9iCj please talk to @katelovescode to access the google drive link

**Comment by csprayregen** [comment]
@arku @katelovescode this isn't working in Safari or Chrome

![Screen Shot 2020-08-28 at 10 47 55 AM](https://user-images.githubusercontent.com/26717304/91587031-d11dc780-e91b-11ea-804e-aae637d7c3ca.png)
![Screen Shot 2020-08-28 at 10 47 47 AM](https://user-images.githubusercontent.com/26717304/91587032-d1b65e00-e91b-11ea-8e81-311c2bf6789f.png)

**Comment by katelovescode** [comment]
cc @arku "In QA" is only for when it's been merged. :)
