### ISSUE TITLE
Google analytics not working as expected in production

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1123]
## 🤬 What's wrong?
We see activity in Nebraska on GA in staging, and we don't see any data in production. For this issue, start by looking into the environment variable for production and see if that also fixes the issue in staging. 

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

## 🏓 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by cjhaddad** [comment]
Note: The changes made to the frontend by adding a library that use runtime env vars are now on staging. Until we can release staging to demo and production this ticket won't be completely QA-able. Added the 'blocked behind other work' label to signify this.

**Comment by rebeccakarasiktw** [comment]
HI @cjhaddad @katelovescode I think this is working as expected and so I will move to done. However, I'm only able to see our (Chelsea, Kate, Candice, etc) user IDs in prod environment. It's possible that no NECC users have logged in since we launched this user dimension. It seems strange but I think we can close this bug for now.
