### ISSUE TITLE
I can add attendance records for the kids in my care

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1125]
## 🧶 Acceptance Criteria

- [x] I can click "Add attendance" in my dashboard to be redirected to the Attendance page
- [x] When I go to the attendance page, each row is auto populated with one child in my care
- [x] When I go to the attendance page, I will see a warning message with some information. I am able to close that warning message if I want to dismiss it. @csprayregen @cjhaddad new AC
- [x] If I have closed the warning message and re-open the attendance page or re-load it, I will see the warning message again. @csprayregen @cjhaddad new AC
- [x] When I go to the attendance page, I will not see any children that have been marked inactive in the list. @csprayregen @cjhaddad new AC
- [x] I can add a check in and check out time 
- [x] I can mark a child as absent
- [x] When I mark a child as absent, I can select the reason as either COVID-related or not COVID-related
- [x] I can input attendance for up to 7 days
X I can click "Add another date" to enter attendance for more than 7 days --> NO LONGER IN FIRST RELEASE PER 6/4 DISCUSSION
- [x] I can only enter attendance for the current date or previous dates (not future dates)
- [x] The user is told to choose between WS and P4P but not to use both (copy at the top of the page)
- [x] I can click Save to save my attendance
- [x] when I save my attendance, the Success box pops up
- [x] I can click "Go to dashboard" in the success box to return to my dashboard
- [x] This works for NE and IL users
- [x] This works in English and Spanish
- [x] New AC: if my check out time is earlier than my check in time, or is the same as my check out time, assume the check out happened on the following date
- [ ] Check accessibility (see below)

For now, we have no logic or validations around overlapping records. This will be added in future tickets. 

## 🖍️ Implementation Details

[Figma link](https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=5194%3A0)

Spanish: https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=505390032

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by katelovescode** [comment]
Data structure documented here: https://github.com/pieforproviders/pieforproviders/pull/1327

**Comment by katelovescode** [comment]
First pass-through
- [x] I can click "Add attendance" in my dashboard to be redirected to the Attendance page
- [x] When I go to the attendance page, each row is auto populated with one child in my care
- [x] When I go to the attendance page, I will see a warning message with some information. I am able to close that warning message if I want to dismiss it.
- [x] If I have closed the warning message and re-open the attendance page or re-load it, I will see the warning message again.
- [ ] **When I go to the attendance page, I will not see any children that have been marked inactive in the list.**
> This didn't work for me
> To reproduce, I clicked "inactive" on a kid on the dashboard, as of today, selected "no longer in my care" and they're still there

- [ ] **I can add a check in and check out time **

> I know you mentioned something about this in the morning meeting, Candice, but I don't remember.  If we do PM times, is it expected to change it to 24-hour format?
> I can add a check out time *before* a check in time.  If I do, say, 1pm check in and 4am check out the front end doesn't roll over to the next day, and it records negative duration.
<img width="585" alt="Screen Shot 2021-07-02 at 12 15 21 PM" src="https://user-images.githubusercontent.com/8364647/124308684-41ded300-db2f-11eb-9de4-2a014e0eb8fb.png">
> Should we add this as an error state and protect against it on the back end as well?

- [x] I can mark a child as absent
- [x] When I mark a child as absent, I can select the reason as either COVID-related or not COVID-related
- [x] I can input attendance for up to 7 days
- [x] I can only enter attendance for the current date or previous dates (not future dates)
- [x] The user is told to choose between WS and P4P but not to use both (copy at the top of the page)
- [x] I can click Save to save my attendance
- [x] when I save my attendance, the Success box pops up
- [x] I can click "Go to dashboard" in the success box to return to my dashboard
- [x] This works for NE and IL users
- [ ] This works in English and Spanish
- [ ] Check accessibility (see below)

**Comment by csprayregen** [comment]
Chelsea's QA:

- [ ]  I can click "Add attendance" in my dashboard to be redirected to the Attendance page
- [ ]  When I go to the attendance page, each row is auto populated with one child in my care
- [ ]  When I go to the attendance page, I will see a warning message with some information. I am able to close that warning message if I want to dismiss it.
- [ ]  If I have closed the warning message and re-open the attendance page or re-load it, I will see the warning message again. 
- [ ]  When I go to the attendance page, I will not see any children that have been marked inactive in the list. 
- [ ]  I can add a check in and check out time
- [ ]  I can mark a child as absent
- [ ]  When I mark a child as absent, I can select the reason as either COVID-related or not COVID-related
- [ ]  I can input attendance for up to 7 days
- [ ]  I can only enter attendance for the current date or previous dates (not future dates)
- [ ]  The user is told to choose between WS and P4P but not to use both (copy at the top of the page)
- [ ]  I can click Save to save my attendance
- [ ]  when I save my attendance, the Success box pops up
- [ ]  I can click "Go to dashboard" in the success box to return to my dashboard
- [ ]  This works for NE and IL users
- [ ]  This works in English and Spanish
- [ ]  New AC: if my check out time is earlier than my check in time, or is the same as my check out time, assume the check out happened on the following date
- [ ]  Check accessibility (see below)
