### ISSUE TITLE
When I have marked a child as inactive, they appear differently in my grid 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1141]
## 🧶 Acceptance Criteria
- [x] When I look at my table for the current month, I only see children with the status active - or they appear differently on my grid --> they appear on the bottom of the table with: First column in gray 3, (Inactive) after the name, other columns left blank, "Mark inactive" disabled
- [ ] When I look at my table for a previous month, I only see children who had the status active during that month - or they appear differently on my grid -->  they appear on the bottom of the table with: First column in gray 3, (Inactive) after the name, other columns left blank, "Mark inactive" disabled --> delayed for a future ticket

## 🖍️ Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**[Figma link](https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4979%3A23572)**

**Comment by rebeccakarasiktw** [comment]
Hey @cjhaddad a couple of things i noticed here too, let me know what you think!

1. When I. mark a child inactive, they continue to appear at the top of the page, even when I reload the page.
<img width="1792" alt="Screen Shot 2021-05-17 at 09 51 09" src="https://user-images.githubusercontent.com/26929739/118506574-6e639a80-b6fb-11eb-837f-355548c61992.png">

2. In the IL dashboard, even when reloading the page, I noticed that the inactive children did not move to the bottom of the table. (I did not find this issue in NE dashboard, and only found it intermittently in IL dashboard)
<img width="1790" alt="Screen Shot 2021-05-17 at 09 52 33" src="https://user-images.githubusercontent.com/26929739/118506526-64419c00-b6fb-11eb-91e4-199c606a83c1.png">

3. When I marked a child as inactive starting a date in May, I went back to April and saw that the child was inactive. Not sure if this is dependent on the backend ticket and/or we should discuss w Chelsea & Kate? 
<img width="1792" alt="Screen Shot 2021-05-17 at 09 41 14" src="https://user-images.githubusercontent.com/26929739/118506646-80ddd400-b6fb-11eb-93ed-58b0151ad865.png">

**Comment by cjhaddad** [comment]
> Hey @cjhaddad a couple of things i noticed here too, let me know what you think!
> 
> 1. When I. mark a child inactive, they continue to appear at the top of the page, even when I reload the page.
> 
Ah! This is how it's coming back from backend. I need to add sorting to the data returned from the BE. Easily addressed. 
> <img alt="Screen Shot 2021-05-17 at 09 51 09" width="1792" src="https://user-images.githubusercontent.com/26929739/118506574-6e639a80-b6fb-11eb-837f-355548c61992.png">
> 
> 1. In the IL dashboard, even when reloading the page, I noticed that the inactive children did not move to the bottom of the table. (I did not find this issue in NE dashboard, and only found it intermittently in IL dashboard)
> 
Cool! Will have a look...not sure what's going on here. 
> <img alt="Screen Shot 2021-05-17 at 09 52 33" width="1790" src="https://user-images.githubusercontent.com/26929739/118506526-64419c00-b6fb-11eb-91e4-199c606a83c1.png">
> 
> 1. When I marked a child as inactive starting a date in May, I went back to April and saw that the child was inactive. Not sure if this is dependent on the backend ticket and/or we should discuss w Chelsea & Kate?
> 
Yes, I'll need to investigate this and then see if we need to make some BE updates. 
> <img alt="Screen Shot 2021-05-17 at 09 41 14" width="1792" src="https://user-images.githubusercontent.com/26929739/118506646-80ddd400-b6fb-11eb-93ed-58b0151ad865.png">

**Comment by csprayregen** [comment]
@cjhaddad this looks good! Just one tiny issue - when we translate to Spanish, the child's name should have "Inactivo/a" at the end, not "Inactive". If you can update that, this one is good to go!
