### ISSUE TITLE
As a user, I can track remaining hourly and daily units during my approval period

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1142]
## ✨ What new feature do you want to see?
There is an additional column on my dashboard that tells me how many hourly and daily units I have left for my approval period, and in some way alerts me to request more from the state if I'm getting close to using them up. 

OPEN QUESTIONS:
-If a provider signs up in the middle of her approval period, (how) will we know how many of each unit she has used so far? How should we handle this?
-Does this need to be yet another column? Open to any other ways to display this, maybe w/in an existing column? But another column is also fine. 

## 🧶 Acceptance Criteria

- [x] There is an additional header row clarifying the weekly, monthly, and approval period time frames 

## 🖍️ Implementation Details
https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4538%3A16605

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by csprayregen** [comment]
@rebeccakarasiktw to close this one out, can you add it to the "official" dashboard mockup link, and then I'll ticket the engineering ticket?

**Comment by csprayregen** [comment]
Moving this back to QA column for now as a reminder to update the dev ticket when ready

**Comment by rebeccakarasiktw** [comment]
@csprayregen added. I think for this question "(how) will we know how many of each unit she has used so far?" maybe we should discuss more, including with the data team. should we make some assumptions here? or would we not make the calculation at all?

**Comment by csprayregen** [comment]
@rebeccakarasiktw yes this is a great point. I'm going to move that conversation over to the relevant front end ticket so we can work on it all in one place.
