### ISSUE TITLE
I can retrieve "hourly units remaining" during the approval period from the API

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1143]
✨ What new feature do you want to see?
The API returns the hourly units remaining during the approval period column/field for the Nebraska dashboard

🧶 Acceptance Criteria
- [ ] Ticket #1145  has the necessary query for this data documented
- [ ]  This matches formulas laid out by the data team
- [ ] This passes test cases

🥧 Additional context
Figma link for reference of initial implementation of this query on the front-end (see V2): https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4538%3A16605

The formulas for this are address in the data ticket #1146

**Comment by katelovescode** [comment]
@csprayregen Same question here - is this the "of x" part of the Hours column on the dashboard?

**Comment by csprayregen** [comment]
@katelovescode on the dashboard itself, we've changed this field to just say full days and full hours used. So "5" instead of "5 of 10." Tweaking the name of the card to make that clearer

**Comment by csprayregen** [comment]
@katelovescode we haven't implemented this card yet in design or data, so I'd de-prioritize for now
