### ISSUE TITLE
I can view dynamic data for hourly units remaining and daily units remaining in the NE dashboard

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1145]
## ✨ What new feature do you want to see?
I can see these fields in the table on my NE dashboard table

## 🧶 Acceptance Criteria
- [ ] I can see the hourly units remaining for this approval period for the kids associated with my account in the dashboard table
- [ ] I can see the daily units remaining for this approval period for the kids associated with my account in the dashboard table
- [ ] I can click the question mark to see definitions for both of these columns
- [ ]  The above criteria work in both English and Spanish
- [ ]  Verify accessibility (see details below)

## 🖍️ Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🥧 Additional context
New column is reflected in the Nebraska V3 mockup here: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4538%3A16605

The formulas are being built for this in #1146  - merged in from https://github.com/pieforproviders/pieforproviders/pull/1763

**Comment by csprayregen** [comment]
@rebeccakarasiktw please add mock up to this one when ready. ideally in next couple weeks or so:

**Comment by rebeccakarasiktw** [comment]
@csprayregen please take a look at the [Figma here (V3)](https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4538%3A16605) and let me know what you think. Also should we add definitions for these new details?

**Comment by csprayregen** [comment]
@rebeccakarasiktw a few thoughts on this. 

1. I worry the different time periods aren't clear enough. Days, hours and absences are monthly. Hours attended is weekly. Revenue is monthly. And now this is added for approval period, usually annual though not 100% of the time. Do you think it's worth making this more explicit across the column headers, or in some other way?
2. I also wonder if we want to move these new columns to the far right, since they're less likely to be relevant on a regular basis as compared to revenue. In other words, you'll need to start paying attention to this toward the end of your approval period, 9 months or so into the case cycle. Whereas revenue comes up every two weeks or every month. 
3. I really like the warning, but wonder if we want to add it for the weekly hours first? Or simultaneously and use for both? I think the weekly hours is slightly more likely to come up. 
4. Yes, let's add definitions. Can you draft those as part of this ticket? 

Thank you!!
