### ISSUE TITLE
In the NE low code prototype spreadsheet, add columns to track remaining hourly and daily units for the approval period

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1146]
## ✨ What new feature do you want to see?
Approval letters state the max hourly and daily units allowed in an approval period. We should track this on their dashboard based on attendance data from WS.

## 🧶 Acceptance Criteria
- [ ]  The NE spreadsheet correctly calculates hourly and daily units used so far and total allowed hourly and daily units 
- [ ]  This field is included on the "Dashboard to S3" tab - @katelovescode can you please provide any formatting needs and tell us which column you'd like this new field to be in
- [ ]  I have updated these formulas in the documentation for Kate
- [ ] I have updated the test spreadsheet
- [ ] I have updated the production spreadsheet

## 🖍️ Implementation Details
We should first implement this in the testing spreadsheet and QA it. Only deploy to the production spreadsheet in coordination with engineering work to ensure this works as expected for users. 

Figma updates for reference of what this will look like on the front end coming soon. 

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by csprayregen** [comment]
Plan as discussed in Wednesday night meeting with @joseluisrangel-dataheim @JonErvin @katelovescode: build out full formulas for a child that is onboarded to P4P from the beginning of her approval period. Otherwise, no data is shown in these columns, unless the provider shares that info with us. Chelsea to find out more about how hard it is for the provider to get that info from state.

**Comment by carolinekinnen** [comment]
Added _Authorized hours_, _Hours used_, _Authorized days_, and _Days used_ to _Dashboard to S3_ tab and _Total daily units used in authorization period_ and _Total hourly units used in authorization period_ to Summary by Child tab.

Edited NE prediction algorithms sheets (both testing and production) and added to Nebraska Model Documentation

**Comment by katelovescode** [comment]
Does this impact revenue at all, or strictly the columns to display a tally of how many have been used so far?

**Comment by csprayregen** [comment]
@katelovescode I believe this has no impact on revenue. @carolinekinnen and @joseluisrangel-dataheim can confirm.

**Comment by carolinekinnen** [comment]
Confirmed no impact on revenue, strictly a tally!

**Comment by JonErvin** [comment]
QA looks good!  Dropped down the formulas in Dashboard to S3 (was only in the first row).  Otherwise everything works great.  @katelovescode @csprayregen 

We can close this issue.
