### ISSUE TITLE
The hours and days columns on my NE dashboard no longer have the "of XX" format

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1150]
## ✨ What new feature do you want to see?
We are editing the hours and days used fields to not have the "of X" at the end (but simply say how many have been used for the month)

## 🧶 Acceptance Criteria

- [x] The format is updated on my "days attended" column
- [x] The format is updated on my "hours attended" column
- [x]  The above criteria work in both English and Spanish

- [ ]  Verify accessibility (see details below)

## 🖍️ Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🥧 Additional context
Updated Figma coming soon (but it's pretty straightforward)

**Comment by nneka-nu** [comment]
I'd like to work on this issue.

**Comment by nneka-nu** [comment]
@csprayregen, I need clarification. Do I remove `of XX` from all four fields: (full days, hours, absences, hours attended) or just from full days, hours attended.
<img width="804" alt="dashboard" src="https://user-images.githubusercontent.com/13953987/114487003-b0ad2f80-9bc3-11eb-9607-374dd0c1f3bd.png">

**Comment by csprayregen** [comment]
@nneka-nu this is only for the columns titled Full days and Hours. Does that make sense?

**Comment by nneka-nu** [comment]
Yes, thank you.
