### ISSUE TITLE
Backend Work for Mark Inactive (Historical Data)

### ISSUE THREAD

**Issue by cjhaddad** [pieforproviders/pieforproviders#1189]
## 📋 Summary
For frontend tickets: #1124 #1174 we need to make sure the child update endpoint takes in the following fields and adds them to the database:
```
{
   active: boolean,
   inactive_date: YYYY-MM-DD,
   inactive_reason: enum [ no_longer_in_my_care, no_longer_recieving_subsidies, other]
}
```

Also! We need to update the response data from the cases_list_for_backend to add the `active` field for each cases object from the child model.

This ticket along with #1206 should take care of the backend work needed for the mark inactive feature.

## 💻 Implementation Details

**Not in scope, but related**
* how are we going to manage historical data?
* how will we retrieve historical data?
* do we need to store data after the case becomes inactive?

cc @csprayregen 

## 🧐 Why tho
We need this change in order to make a child as inactive and active.

**Comment by csprayregen** [comment]
FYI @cjhaddad and @katelovescode I've added these open questions to my to do list to scope for the backlog

**Comment by katelovescode** [comment]
@cjhaddad this will need your QA/Approval as well! ✅
