### ISSUE TITLE
I can enter my actual payment from the state 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1194]
## ✨ What new feature do you want to see?
I think we should consider developing this as an optional field that providers can enter. They might appreciate this for tracking as a first step toward more robust billing reconciliation. Additionally, if it turns out they do like to use this, it would be super helpful to us from an impact tracking and advocacy perspective. 

## 🖍️ Implementation Details

Figma link [here](https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=5969%3A43540)
Note some things:

- Responsive design (the modal changes a little bit)
- Updated language/display of the "earned revenue" 
- Sad path (potentially) of recording the same payment more than once.

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by rebeccakarasiktw** [comment]
@csprayregen I am moving this over to QA - can you review the updates I made and lmk any thoughts/changes you have?
