### ISSUE TITLE
update `case_list_for_dashboard` endpoint to include child id

### ISSUE THREAD

**Issue by cjhaddad** [pieforproviders/pieforproviders#1206]
## 📋 Summary
For the MarkInactive feature (#1124 and #1141) to work we need to call the `PUT /children/:id` endpoint. Currently, the `case_list_for_dashboard` endpoint does not return the needed child `id` to make this call. Therefore, the `case_list_for_dashboard` endpoint needs to be updated to give the frontend the child `id` to make the needed updates to that specific child. 

This ticket along with #1189  should take care of the backend work needed for the mark inactive feature.

## 💻 Implementation Details

- note on implementation, a long time ago we had implemented slugs for api records, but I think we backed those changes out when I simplified the data model and the API; I'd prefer we *don't* use slugs, but it's just a note in case there's some legacy code re: url slugs hanging around when you dig in

## 🧐 Why tho
So we can update the right records!

**Comment by katelovescode** [comment]
This will need to be QAed by @cjhaddad - testing instructions are on the PR!

**Comment by katelovescode** [comment]
@cjhaddad if this is ✅ can you move it to approved and close it?
