### ISSUE TITLE
Create Attendance Controller

### ISSUE THREAD

**Issue by cjhaddad** [pieforproviders/pieforproviders#1211]
## 📋 Summary
For the functionality for #1125 to work, we need the backend to have an attendance controller in the backend. The `PUT` attendance endpoint will be hit when the `Save` button is clicked.

## 💻 Implementation Details

Attendance `create` endpoint should accept the following params:

```
#  check_in       :datetime         not null
#  check_out    :datetime         not null
#  child_id         :uuid             not null
```

This controller method will need to determine the correct child_approval to associate the attendance with by finding the child, and finding the child_approval active as of the date of the attendance - much of this logic already exists with the `active_on_date` scope in the approval model; then you can find the correct child_approval by child_id

## 🧐 Why tho
So we can start creating attendances in-app rather than just from Wonderschool

**Comment by cjhaddad** [comment]
@katelovescode regarding the 'absent' and 'absent covid-related' checks (see figma: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=5194%3A0 ) how would you like to see this being sent to the backend?

**Comment by cjhaddad** [comment]
@katelovescode chatted with rebecca, and she confirmed the absent checks are mutually exclusive. how would you like to see this data come to the backend?

**Comment by katelovescode** [comment]
@cjhaddad let's do it like this:
```
#  absence       :string
```
and the values I'd be expecting would be `absence`, `absence_covid` or don't send it at all if neither box is checked - will there be a way to clear them if one is checked by mistake?

**Comment by katelovescode** [comment]
This is going to end up being a bulk update endpoint, more info to come
