### ISSUE TITLE
Bad /signup sizing on larger screens

### ISSUE THREAD

**Issue by noragharris** [pieforproviders/pieforproviders#125]
## 🤬 What's wrong?
Size of /signup endpoint pictures and form is not good on larger screens.

## 🧥Expected behavior
Auto-sizing to screen size

## 📸 Screenshots
![image](https://user-images.githubusercontent.com/31748798/84846456-7c54fb00-b014-11ea-9547-df51758e8155.png)

**Comment by rebeccakarasiktw** [comment]
Hey @noragharris what I was thinking we can do for these larger sizes is:
1- If its possible, can the photo take up 50% of the screen? 
2- If not, what about having a blue background behind the image?
I'm attaching a screenshot of the 2 options, and I'm open to any other suggestions you have!

![image](https://user-images.githubusercontent.com/26929739/85926065-588a8400-b862-11ea-97a6-20365c7215fd.png)
