### ISSUE TITLE
[Google Analytics] User IDs not available for all users in production 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1267]
## 👉🏼 Steps to Reproduce

**To investigate before closing out**
user hits /dashboard & gets redirected to /login , logs in --> we have no user id tracked here and that is correct.
[after logging in] goes to /dashboard then goes to /attendance >> are we tracking user id in this part of the journey? or are we missing it too? _put in the 'check' in this scenario that we are sending & updating user id_

**Resolved**
Specific issues: user IDs not set for all users. We are seeing that people are logging in but their user ID is listed as "not set." 
Additionally, at least one user ID does not appear to be showing up at all: e369cc28-2106-4fbe-8dad-fc4485270ce4
We are aware that this user has logged in, but are not seeing her in the GA reports. 

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

## 🍣 Additional context
Check out dataclips for UserIds: https://data.heroku.com/dataclips/kcugjjfhijxmlufihzaxbcldbjmi

## 🏓 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

TODO:
- investigate other analytics tools - is GA just bad for us?
- compare GA results with logs, can we track how many people have logged in using the post request, etc
- log aggregator tool? https://www.graylog.org/pricing

**Comment by csprayregen** [comment]
Closing on the assumption we're moving to Hotjar.

**Comment by katelovescode** [comment]
@cjhaddad I had an idea about this based on our convo with Lori, Rebecca and Chelsea earlier - I don't know if there's a way to tag route redirects when a person doesn't have authorization anymore, maybe even something with localStorage?  Like, if we could tag each of those /dashboard hits when the person is unauthorized at least we could filter them out?  Not sure if that's practical or do-able, but just a thought.
