### ISSUE TITLE
Should we be hashing passwords from the front end?

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#13]
## 📋 Summary
Hashing passwords in devise?  Passing passwords and confirmations in plain text to the API?  :/ Don't like

## 💻 Implementation Details
- Need to investigate how to send passwords safely from the front end to the API without exposing them in plain text
- Blocked by/impacted by #11 

## 🧐 Why tho
Plain text passwords are bad.  NO DO THIS

## 📎 Deliverables
- tickets to implement passwords between the front end and back end that don't involve sending them plaintext

**Comment by katelovescode** [comment]
@jessehall3 this might be relevant to your PR/implementation as well.

**Comment by jessehall3** [comment]
@katelovescode I see this, thank you.

**Comment by katelovescode** [comment]
This isn't necessary with HTTPS
