### ISSUE TITLE
Spike: investigate skinning to connect to Nebraska billing portal for providers 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1310]
## 📋 Summary
Inspired by Propel's technology, let's investigate whether we can use skinning to enable providers to access their billing portals through Pie for Providers. This might enable any number of improvements to provider experience, including:
- Providers submit billing using existing P4P data
- P4P updates providers on payments
- P4P reconciles payments based on our attendance calculations

## 🇺🇸 States this change applies to
- [x] Nebraska
- [ ] Illinois

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🧐 Why tho

Definition of done: Proposal from Goodfolk on this solution

**Comment by rebeccakarasiktw** [comment]
Moving to done as we received a scope & proposal from Goodfolk
