### ISSUE TITLE
When I manually enter attendance for a child, I have the option to enter two attendances from a single day

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1312]
## ✨ What new feature do you want to see?

I want to be able to add more than one attendance for a given day for any child.

## 🇺🇸 States this change applies to
- [X] Nebraska
- [ ] Illinois

## 🧶 Acceptance Criteria
- [x] I can add up to two total check in and check out times for a single day
- [x] I can click "Remove check in time" to remove the second check in. When I do so, anything I've entered but not saved is deleted
- [x] If I don't enter anything for the second check in/out, I can still save the first one
- [x] I can do this while adding a new attendance 
- [x] I can do this while editing an already saved attendance

## 🖍️ Implementation Details

This work is started and got put on hold on this branch: https://github.com/pieforproviders/pieforproviders/tree/PIE-1312/multiple_attendance_entry

[**Figma link**](https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=5693%3A33800)
Spanish translations: https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=505390032

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by katelovescode** [comment]
![Screen Shot 2021-12-01 at 5 41 59 PM](https://user-images.githubusercontent.com/8364647/144331890-8b508c67-7ff0-420c-afa0-30441805cfab.png)
@csprayregen - can I get Spanish translations?

**Comment by csprayregen** [comment]
@katelovescode all the translations should now be in this doc (linked in card now too): https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=505390032

**Comment by csprayregen** [comment]
Chelsea's QA:

- [ ]  I can add up to two total check in and check out times for a single day
- [ ]  I can click "Remove check in time" to remove the second check in. When I do so, anything I've entered but not saved is deleted
- [ ]  If I don't enter anything for the second check in/out, I can still save the first one
- [ ]  I can do this while adding a new attendance
- [ ]  I can do this while editing an already saved attendance

**Comment by csprayregen** [comment]
Issues: 
1. The duration on the second attendance is not appearing correctly in View Attendance
<img width="287" alt="Screen Shot 2022-01-12 at 12 42 09 PM" src="https://user-images.githubusercontent.com/26717304/149202119-dda69d73-7117-4628-abe2-d294f8e6897b.png">

**Comment by csprayregen** [comment]
Second issue, the time is not appearing as I enter it. What I entered for 1/9 was 3am-6am, and for 1/10, I entered 3am-5am. 

![image](https://user-images.githubusercontent.com/26717304/149202737-9ff29a1f-aaf5-472f-a0a4-7f4057536178.png)

![image](https://user-images.githubusercontent.com/26717304/149202758-1170cafa-efed-4272-a543-a34f06e30356.png)

**Comment by csprayregen** [comment]
CS follow up QA from above:
- [ ] Duration not appearing correctly on View Attendance
- [ ] Time not appearing as I entered on View Attendance
- [ ] Spanish translation of Remove check-in time

**Comment by csprayregen** [comment]
Duration times still not right. See below. 

<img width="1144" alt="Screen Shot 2022-01-13 at 9 44 33 AM" src="https://user-images.githubusercontent.com/26717304/149361899-4b6bd729-b642-439d-a6b2-81f5324e2f52.png">
