### ISSUE TITLE
When I enter attendance, I see errors when I make a mistake. 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1376]
## ✨ What new feature do you want to see?
When I enter my attendance (as detailed in #1125), I see errors as relevant to my entrance. 

## 🇺🇸 States this change applies to
- [x] Nebraska
- [x] Illinois

## 🧶 Acceptance Criteria
I see the following error states:
- [x] No date entered -->  Ideally, I see this error immediately after I leave the date/absence field. If that doesn't work, it should happen as soon as I start typing in the date or absence field 
- [x] Another question for @cjhaddad @rebeccakarasiktw @katelovescode - how do we want to handle it if someone enters information for a date that's already been entered? This could be an error. This could be an attempt to edit. We'll have more options for this when we get to the View Attendance and Multiple Records per day cards. Do we want to do anything currently? What is default behavior? **RK response: I dont think we will want to do anything currently until we better understand the user behavior. But I think if/when we enhance this feature we would only want a date to be entered one time. Also sorry I accidentally made this into a github issue.**
- [x] If an error is present, the 'Save' button is disabled to avoid making an API request with incomplete data.
- [ ] ~~Time is not valid~~ --> not needed, addressed w/in component
- [ ] ~~Date is invalid~~ --> not needed, addressed w/in component
- [ ] ~~Future dates are invalid~~ --> not needed, addressed w/in component 
- [ ] ~~Neither check in time nor absent status selected (at least one must be selected)~~ --> does not apply since some children may not have attendance.  

## 🖍️ Implementation Details
 [**Figma link**](https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=5194%3A0)

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🥧 Additional context
@rebeccakarasiktw please add figma mockups here when ready

**Comment by rebeccakarasiktw** [comment]
@cjhaddad @csprayregen FYI i added the figma link to this ticket as well as 1 comment/question I have about the AC "date is invalid" --- I was left with the the understanding that this is not possible, i.e. we are considering any date in the past valid. Am I right and if so, should we remove this AC from the ticket?
Or if it can indeed happen, what is considered an invalid date?

**Comment by csprayregen** [comment]
Chelsea's QA

Illinois English
- [ ] No date entered --> Ideally, I see this error immediately after I leave the date/absence field. If that doesn't work, it should happen as soon as I start typing in the date or absence field

Illinois Spanish
- [ ] No date entered --> Ideally, I see this error immediately after I leave the date/absence field. If that doesn't work, it should happen as soon as I start typing in the date or absence field

Nebraska English
- [ ] No date entered --> Ideally, I see this error immediately after I leave the date/absence field. If that doesn't work, it should happen as soon as I start typing in the date or absence field

Nebraska Spanish
- [ ] No date entered --> Ideally, I see this error immediately after I leave the date/absence field. If that doesn't work, it should happen as soon as I start typing in the date or absence field
