### ISSUE TITLE
Nebraska users do not have the option to mark COVID-related absences after the state of emergency ends on 7/31/21

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1377]
## ✨ What new feature do you want to see?
The NE state of emergency is over, and 30 days after that announcement, COVID related subsidy rules are no longer in effect. This means that providers are allowed only 5 absences, and the reason does not matter. 

## 🇺🇸 States this change applies to
- [x] Nebraska
- [ ] Illinois

## 🧶 Acceptance Criteria

- [ ] Hide or disable (whichever is easier) the COVID-related absence check box if the date chosen in the calendar is later than 7/31/21 
- [ ] This works in English and Spanish
- [ ] Check for accessibility 

## 🖍️ Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by katelovescode** [comment]
> As part of this, we may also want to turn the absence reason into a dropdown menu. We will make this call and develop after finishing the "add attendance" feature.

@csprayregen if this is still desired, let's make another ticket for it.

**Comment by katelovescode** [comment]
@csprayregen the estimate on this ticket is for removing the COVID checkbox only

**Comment by katelovescode** [comment]
@csprayregen can we get confirmation on the date that the COVID rules were no longer in effect?

**Comment by csprayregen** [comment]
@katelovescode sure - can you clarify why we need that date? (I understand for rule changes going forward, but this isn't built into our formulas at this point, I think)

**Comment by csprayregen** [comment]
@katelovescode belated follow up here - just confirming that these new rules are in effect starting July 31, based on this press release. The last day of the old rules was July 30. https://dhhs.ne.gov/Pages/Gov-Ricketts-Ends-Coronavirus-State-of-Emergency.aspx

**Comment by katelovescode** [comment]
@cjhaddad I gave this a quick shot but I'm struggling with the complexity of this component and dynamically changing these columns.  I got it to half work 😭   Branch is here: https://github.com/pieforproviders/pieforproviders/tree/PIE-1377/conditionally_remove_COVID_absence
