### ISSUE TITLE
Investigate user's new rates and update formulas accordingly

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1378]
## 📋 Summary
Our new user received a note from DHHS with updated rates effective 7/1. It is unclear if these changes are specific to her cases as the letter seems to indicate - and she clarified that her QRIS rate has not increased. If these are across-the-board new rates effective as of 7/1, that is confusing. We are still searching for a source on updated rates, but our NE partners told us the rates wouldn't change until 8/28. I will share the letter with whoever picks up this ticket.

## 🇺🇸 States this change applies to
- [x] Nebraska
- [ ] Illinois

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by carolinekinnen** [comment]
Looks like the rates the provider received match the results from the [2021 Market Rate Survey](https://dhhs.ne.gov/Child%20Care%20Market%20Rate%20Surveys/2021%20Market%20Rate%20Survey%20Report.pdf), which inform the rates set by NDHHS every odd numbered year. However, the [NDHHS website](https://dhhs.ne.gov/Pages/Child-Care-Subsidy-Information-for-Providers.aspx) still has the rates from 2019. I emailed dhhs.ccsubsidy@nebraska.gov to see if the rates from the MRS have gone into effect yet

**Comment by csprayregen** [comment]
@carolinekinnen great find on the market survey and really appreciate you going ahead and reaching out to the office. I have emails out to some policy people in the state. Let's stay in touch on this if either of us hears back. We can leave this ticket on pause for the meantime.

**Comment by carolinekinnen** [comment]
Update from DHHS, let me know if you'd like me to respond!

> Thank you for your email regarding the 2021 Market Rate Survey. Child Care Subsidy rates were updated 7/1/21. The guidance document posted on the website is currently under review for edits and will be updated when those edits are complete.

**Comment by csprayregen** [comment]
Hi @carolinekinnen that's great! If they can tell you what the new rates are without having to wait for the guidance doc to be posted, that would be awesome. Why don't you go ahead and ask. You can also ask if they know when the doc will be updated, or if there's a way to be alerted when it is. Much appreciated.

**Comment by carolinekinnen** [comment]
They were not able to provide a timeline on when those edits will be completed. There is an internal process that must be completed and it's unclear at what stage they are at currently.
 
She did add this though

> Our rates have been set again at the 60th percentile of the 2021 Market Rate Survey, which can be found on our webpage at https://dhhs.ne.gov/Pages/Market-Rate-Survey.aspx. Rates by percentile can be viewed on pages 13 and 14 of the document. I have also attached a chart of our rates for easier viewing.

[2021 CC Subsidy Provider Rates.pdf](https://github.com/pieforproviders/pieforproviders/files/7017711/2021.CC.Subsidy.Provider.Rates.pdf)

**Comment by JonErvin** [comment]
@katelovescode Just confirming I've reopened this ticket.  On the spreadsheet side, I need to:
- Update the rate tables
- Handle logic for different accredited rates based on county

Will post here when done.

**Comment by JonErvin** [comment]
Updated rates in NECC spreadsheet (opted not to make change in testing spreadsheet for simplicity, given we'll be retiring this spreadsheet soon).  Also made notes in the documents.
