### ISSUE TITLE
Update Sheets formulas for NE for attendances of >10 hours

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1387]
## 📋 Summary
Jon's overview in Slack:
"We haven't come across this situation yet, but in the rare event a child attends for more than 1 full day + 5.75 hours, I think the provider continues to bill hourly (we previously assumed it would become 2 full days).  The newer guidance document makes this more clear (page 8 ).  Super easy to fix on both the sheets and the ruby side, but want to make sure we get this right before its coded into the model." 

Guidance document: https://dhhs.ne.gov/Guidance%20Docs/Title%20392%20Guidance%20Document.pdf

Acceptance criteria:
- [x] I have adjusted all relevant attendance and revenue estimates to reflect this change
- [x] I have changed this in the test spreadsheet
- [x] I have changed this in the production spreadsheet
- [x] I have updated documentation 

## 🇺🇸 States this change applies to
- [x] Nebraska
- [ ] Illinois

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by JonErvin** [comment]
Hey @csprayregen should be good to go!  Summary of changes:

- Updated Table 1 in Other Lookup Tables (including expanded named ranges) so 10-18 hours bills 1 daily unit and 10-X hourly units.  Anything beyond 18 hours bills 1 daily units and 8 hourly units.
- Moved Table 8 in Other Lookup Tables farther down the sheet (no functional change)

**Comment by csprayregen** [comment]
Looks good - thanks @JonErvin !
