### ISSUE TITLE
Update formulas for multiple check in/out per day use case

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1390]
## 📋 Summary
Our formulas assume multiple check in/out are counted as separate instances of attendance. Should they be counted as a single unit for the purposes of determining whether a daily or hourly unit was used?

Note: per 9/1 email that Chelsea received from Mia at WS, the WS check in-out DOES allow for multiple check in/outs in a day, so we can get this info from our providers and from WS providers. We are working on adding this functionality to our own attendance feature, per #1312 

## 🇺🇸 States this change applies to
- [ ] Nebraska
- [ ] Illinois

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by JonErvin** [comment]
@csprayregen @katelovescode This should be good to go.  Updated in NECC spreadsheet, testing spreadsheet, and docs.

Now the attendance records for a given child and date are summed before assigning daily/hourly units and calculating revenue.  One key decision to flag - I assumed that if at least one of the attendance records is missing a check-out time, we should treat the combined record as missing check-out and use those assumption (scheduled time, if no schedule, assume 8 hours).  

Real life example: Child has two attendance records on 7/30:
- Check-in: 8:47 AM, Check-out: [blank]
- Check-in: 10:43 AM, Check-out: 3:30 PM
In this case, we consider this "missing check-out" and assign according to schedule (8 hours).  Are we OK with this logic?

To test there are three real examples in our data:
- 7560 on 9/8 | missing one check-out, defaulted to schedule of 8 hours
- 7561 on 8/28 | combines morning record (150 min) with afternoon record (187 min) for combined record (237 min --> 5.75 hr units billed)
- 8501 on 7/30 | see above

Also did some more testing on fake data and it works well dealing with the switch between hourly and daily units (e.g., 3 hour AM + 4 hour PM converts to 7 hours = 1 daily unit).

If the assumption above is OK, I think we should be good to go here!

**Comment by JonErvin** [comment]
Summary of changes for posterity - all updates in the word doc.

**New Daily Calculation - Helper**
Pulls in some of the attendance record-specific fields from Daily Calculation, specifically:
- Attendance ID, check-in UTC, check-out UTC straight from Wonderschool Attendance Upload
- Service Date
- Check-in Central Time, check-out Central Time (for reference)
- Attendance helper (to summarize by child and date)
- Calculated minutes

**Daily Calculation**
- Switched Attendance Helper to pull unique values from Daily Calculation - Helper
- Switched WS ID and Service Date to pull from Attendance Helper
- Calculated Minutes now sums all match child&date combos, returning "no end time" if >0 have no check-out
- Calculated Hours, Missing Checkout flag, and ChildCheckIn ID are updated to point to Calculated Minutes

**Comment by csprayregen** [comment]
Thanks @JonErvin ! This is now ready for work as back end ticket #1717
