### ISSUE TITLE
Write a script to sanitize data and pull from prod to staging

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#14]
## 📋 Summary
We need a script to pull prod data to staging and sanitize it.

## 🧐 Why tho
Easier onboarding for volunteers, less PII being passed around and needing deletion every day per our policies.

**Comment by brobertsaz** [comment]
@katelovescode this is pretty easy to do.  I believe that you are hosting on Heroku?

**Comment by katelovescode** [comment]
Yes we are.

**Comment by katelovescode** [comment]
Using Snaplet, need to run tests.
