### ISSUE TITLE
Implement typography/font styles

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#140]
## 📋 Summary
There was a mis-translation between designs in Figma and development. We want to make sure all H1, H2, etc is consistent across the app, and takes into account responsive sizes as well. 

## 💻 Implementation Details
Implement the styles according to Figma: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=175%3A1984
Update headers across the pages that have already been published to ensure they are using the correct font styles.

## 🧐 Why tho
Want to make sure we create a consistent user experience of course! And also to make us faster using consistent styles.

**Comment by katelovescode** [comment]
@jontrainor this ticket should go on hold, it's blocked behind some new design work.  Rebecca is going to rethink the font sizes in `rem` instead of explicit pixel sizes.

**Comment by Jess-White** [comment]
Hi - This seems like a great way to familiarize myself with the codebase - can I jump on it? I know it's hacktoberfest-tagged; I can look for other options. Thanks!

**Comment by jontrainor** [comment]
Yes! I was waiting for Rebecca to have some time to chat about it because
there was "large" and "small" typography sets and Ant just wants all font
sizes relative to the base font size. I would touch base with her but go
for it! I've had a busy month and haven't followed up on it.

**Comment by Jess-White** [comment]
Okay, I'm on the case!

**Comment by rebeccakarasiktw** [comment]
Hello!! I'm very sorry I totally missed this message. @Jess-White let me know how I can help!

**Comment by rebeccakarasiktw** [comment]
Hi @cjhaddad I noticed a few small fonts that should be updated, I've added them as screenshots here, lmk if you have any questions!
![Group 255](https://user-images.githubusercontent.com/26929739/108082096-b3662b00-703f-11eb-98b6-d972e0d9c327.png)
![Frame 81](https://user-images.githubusercontent.com/26929739/108082102-b4975800-703f-11eb-8ee4-64ea4f85151e.png)
![Frame 80](https://user-images.githubusercontent.com/26929739/108082104-b52fee80-703f-11eb-897f-d087d50a420c.png)

**Comment by rebeccakarasiktw** [comment]
Hi @cjhaddad I took a look and it all looks good! Thanks!
