### ISSUE TITLE
Restyle Create an Account page with Ant Library

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#141]
## ✨ What new feature do you want to see?
Let's restyle the Signup page close to the mockups using Ant component library

## 🏖 Implementation Details
- The signup page was styled once but we've since switched to the Ant component library; we need to update the signup form using Ant library elements (also make sure we pull out any non-ant validation library/implementation as necessary.

## Testing instructions
- visit https://pie-staging.herokuapp.com/signup
- the page should be restyled to match the mockups using the Ant library
- Note: we couldn't get the background color of the language toggles to be the light blue, Rebecca approved using the color as-is

**Comment by katelovescode** [comment]
Reopening for QA, this was accidentally tagged to close

**Comment by csprayregen** [comment]
- [ ] I can enter all the fields present in the UX mockup --> yes
- [ ]  All fields are required except phone --> No, issues with phone, TOS, and language.
TOS is mandatory, and should be starred. However, error state does occur when blank: 
![Screen Shot 2020-07-31 at 2 15 59 PM](https://user-images.githubusercontent.com/26717304/89069154-3cce3e00-d338-11ea-8fc7-acb2f7405623.png)
After I click submit and phone number is blank, I'm asked to select a phone type:
![Screen Shot 2020-07-31 at 2 17 00 PM](https://user-images.githubusercontent.com/26717304/89069317-8d459b80-d338-11ea-9402-fe3291e4751c.png)
If I don't toggle on language, it registers as blank when I hit submit:
![Screen Shot 2020-07-31 at 2 18 22 PM](https://user-images.githubusercontent.com/26717304/89069408-b36b3b80-d338-11ea-8a14-6d7450db14e4.png)
- [ ]  The field "Preferred Language" defaults to English --> yes
- [ ]  The user must accept the terms of service in order to click submit --> no, see above
- [ ]  If any required fields are not filled, error states are displayed and submit button is disabled --> yes

- [ ]  The following field validations are present:
- [ ]  Email is the correct format --> yes, but is this new format what we decided on for Ant?
![Screen Shot 2020-07-31 at 2 23 33 PM](https://user-images.githubusercontent.com/26717304/89069744-5c199b00-d339-11ea-948a-cd605692a54f.png)
- [ ]  Phone is the correct format --> no, see above screenshot
- [ ]  Password must be a minimum of 8 characters and include both numbers and letters --> yes
- [ ]  If the terms of service are not agreed to, an error state is displayed and submit button is disabled --> yes
- [ ]  I can click submit when all required fields are filled and terms of service are agreed to --> no, per the above, I must first toggle on language and am told to select a phone type (though it may be signing me up on the back end)
- [ ]  The "terms of service" phrase should link to the TOS content in a separate page --> yes
- [ ]  When I click submit, my user account is created and I'm navigated to a page that tells me to check my email (pending design) --> no longer part of AC for this page

Additional issues 
- [ ] Link to Log-In leads to page that just says Report Feedback --> CS to create bug ticket
- [ ] -Mandatory fields have red star on left instead of blue star on right - is this an Ant thing?
- [ ] -Cursor starts in the middle of the blank fields when entering phone number
- [ ] -Bottom of photo is cut off and the split scroll creates a weird effect when I scroll- let's create a separate, lower priority bug ticket
![Screen Shot 2020-07-31 at 2 13 11 PM](https://user-images.githubusercontent.com/26717304/89069015-f2e55800-d337-11ea-9ef4-adb1073f036a.png)

**Comment by katelovescode** [comment]
>   TOS is mandatory, and should be starred. However, error state does occur when blank:

Fixed

>   After I click submit and phone number is blank, I'm asked to select a phone type:

Fixed

>   If I don't toggle on language, it registers as blank when I hit submit:

Fixed

> * [ ]   Phone is the correct format --> no, see above screenshot

Still working on this one

> * [ ]   I can click submit when all required fields are filled and terms of service are agreed to --> no, per the above, I must first toggle on language and am told to select a phone type (though it may be signing me up on the back end)

Fixed

> * [ ]  In mobile, there is a lot of extra white space around the logo

Still investigating

> * [ ]  Sign up button is not rounded (I think there was convo about this)

I think there was button rounding in someone's PR, I'll track it down.

@csprayregen this list is for me, none of these fixes are deployed yet
