### ISSUE TITLE
"As of" date on the dashboard is wrong in the evening

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1429]
## 👉🏼 Steps to Reproduce

Visit the Nebraska dashboard in the evening CST, after 6pm or so is your best bet to see this behavior
You'll see the "As of" date is the next day

## 🇺🇸 States this bug is happening in
- [X] Nebraska
- [ ] Illinois

## 🧥Expected behavior
"As of" shows the correct day at all times

## 🍣 Additional context
My theory is that the frontend is displaying the day UTC rather than current time zone, but if it's being fed from the backend then it'll be server side.

## 🏓 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by csprayregen** [comment]
@katelovescode this seems to not be fixed. At 6pm CST on August 13, the date changed to August 14. See below. 

![image](https://user-images.githubusercontent.com/26717304/129425664-280a89a1-534e-44dd-b107-0b3e8e1e69e5.png)

**Comment by katelovescode** [comment]
Hm, that's weird - on staging at 6:45pm I'm seeing the correct date - did you check on staging or prod?  Who were you logged in as?

<img width="653" alt="Screen Shot 2021-08-13 at 6 45 16 PM" src="https://user-images.githubusercontent.com/8364647/129427549-53cfd051-d465-414b-a2d0-8a52d6e4a2e9.png">

**Comment by csprayregen** [comment]
Oh, I totally checked on Prod 🤦🏼‍♀️. Will check on staging tonight @katelovescode
