### ISSUE TITLE
Implement Hotjar

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1448]
## 📋 Summary

We've decided to go with Hotjar so we need to implement it in the front end

## 🇺🇸 States this change applies to
- [ ] Nebraska
- [ ] Illinois

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🧐 Why tho

GA was not catching all the people logging in, and the analytics on that dashboard are not as useful to us as we would like.

**Comment by rebeccakarasiktw** [comment]
closing this issue as we already implemented Hotjar
