### ISSUE TITLE
[Analytics] track user behavior on Add Attendance

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1449]
## 📋 Summary

Create custom events and parameters for Attendance feature usage:

**1 - Attendance dates changed** 
When, on the attendance page, I click any of the arrows to change weeks, this event should trigger.
Event name: Dates_filtered
(parameter): page_title: [attendance]
(new parameter): date_selected: [Week selected]

**2 - Attendance input clicked**
When I click on the "+ attendance" button, this event should trigger.
event name: Attendance_input_clicked
(parameter): page_title: [dashboard, attendance]

**3 - Save Attendance**
When I click "save" on, then 
event name: save_attendance
(parameter): number: how many attendance updates are being saved
(new parameter): page_title: [attendance, edit attendance]
_Note: This event should be the same as or similar to the hotjar event that was created_

## 🇺🇸 States this change applies to
- [x] Nebraska
- [x] Illinois

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by rebeccakarasiktw** [comment]
Hey @cjhaddad --- this looks good to me! Moving to approved!
