### ISSUE TITLE
Customize Ant button to match style guide

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#147]
## ✨ What new feature do you want to see?

The Ant button needs some additional styling to match the P4P styles.

## 🧶 Acceptance Criteria

Customize button components so they match the style guide: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=733%3A4545
Create small and large size button components as per the style guide.

**Comment by moonpatroller** [comment]
Make button component have correct background color, maybe with input parameter.
Give it slightly smaller font size, according to Figma.
Get CSS from https://github.com/pieforproviders/pieforproviders/pull/148/files
