### ISSUE TITLE
Data Model Update

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1470]
## 📋 Summary
After all we've learned in Nebraska, it's time for a data model update!

Action Items (pretty much in order):
- [x] @JonErvin will work on revamping the Data Model diagram based on the conversation we had Thursday Aug 5: https://app.diagrams.net/#G19TksAF79LxQcFznePsrMbTdhLIwuGISp
> Notable:
> - middle output columns are unnecessary
> - we will add calculations of daily revenue to the attendance import task, so daily revenue info should be stored on the attendance itself
> - refine what are currently referred to as Approval, ChildApproval, and NebraskaApprovalAmounts to more accurately represent how this works, likely: FamilyAuthorizationPeriod and ChildAuthorizationDetails or something like that, where the approval is just an approval period, and we don't need to have those tables separate
> - QRIS rating on the provider will need historical data, so will some other details
> - combine attendances and absences in the same table
> - QRIS rules are multipliers, do they need to be handled differently?

- [x] @katelovescode @JonErvin and @joseluisrangel-dataheim will take a look at the current schema over the next several days and take notes as comments in this issue so we can note any changes that need to be made to our existing schema: https://github.com/pieforproviders/pieforproviders/blob/develop/db/schema.rb
> Notable:
> - changes to tables explicitly
> - which details on Child, User, Business need historical records kept in detail for calculation (and therefore need to have a historical data table associated to the core record)
> - Any other outstanding issues

- [ ] @katelovescode @JonErvin and @joseluisrangel-dataheim will write tickets for backend changes that will need to be slotted in before calculations are finished

## 🇺🇸 States this change applies to
- [X] Nebraska
- [X] Illinois
- [X] Texas

## 🧐 Why tho
We've learned! 📖  ✏️  👓

**Comment by JonErvin** [comment]
Thanks Kate!  Great convo yesterday y'all.  See here for a v3 Data Model.

https://app.diagrams.net/#G1oPEKbXYSFxey_mze1k5PgCRnxCSPBmFS

It gets really simple when you think of most rules and user inputs as variables that translate attendance data --> daily revenue.  Hopefully not too simplistic? Any thoughts?

**Comment by JonErvin** [comment]
Also looked through the schema and it seems generally aligned.  I think approvals == family in the diagram.  My only question is around child_approval vs child.  I guess the main difference is that the info on child_approval would change over time (and be governed by effective date) while the child info is assumed to be static - is that right?  If that's the case should we add a separate child_approval table in the data model?

**Comment by katelovescode** [comment]
> Also looked through the schema and it seems generally aligned. I think approvals == family in the diagram. My only question is around child_approval vs child. I guess the main difference is that the info on child_approval would change over time (and be governed by effective date) while the child info is assumed to be static - is that right? If that's the case should we add a separate child_approval table in the data model?

See my comments on the V3 about this.

**Comment by katelovescode** [comment]
Schema annotations are here: https://hypothes.is/groups/kqp1KPoj/pieforproviders
