### ISSUE TITLE
Absences are automatically created for Wonderschool users

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1509]
## 📋 Summary

When the wonderschool attendance task runs, we'll run another job to:
- find out if there's an attendance for this day, if not create an absence
- check to see if an attendance has been filed for the days that currently have absences, and if so, delete those absences and create the wonderschool attendance

## 🇺🇸 States this change applies to
- [ ] Nebraska
- [ ] Illinois

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by katelovescode** [comment]
@csprayregen and @rebeccakarasiktw we're going to need a little more info on how this will work in practicality - I think my assumptions above are a good starting place but we might want to think about edge cases.  For example, if a kid usually attends in the morning and the evening (something we're not currently worrying about with schedules), if we have an attendance for the morning but not the evening, is that an hourly absence?  I'm guessing this is further down the line.

**Comment by csprayregen** [comment]
@katelovescode I know JT and @JonErvin  thought a lot about what exactly counts as an absence, and when the absence should be an hourly or daily unit. I would go back to #982 and use those assumptions as a starting point. Also, don't forget that there is a limit of 5 per month, so that should be part of the logic here. Finally, should this ticket be titled "Absences are automatically created..."?

**Comment by katelovescode** [comment]
Oops, yes, will fix.

**Comment by katelovescode** [comment]
@csprayregen my idea for this implementation was to run a job once a day that checks for an attendance for each Nebraska kid on that day.  If they don't have an attendance and they have a schedule for that day, it will create an attendance.

I think when we initially merge this, we'll want to run a one-time task to backfill all scheduled days that weren't attended, up to the kid's schedule effective date; it'll be complex and I'll probably want to run that logic by you and @JonErvin before I merge.  Just want to confirm that this all sounds generally right, or do we need another conversation about it?

**Comment by csprayregen** [comment]
That makes sense! I think we can break the backfilling out into a separate ticket and start with something that is accurate as of the release date. @katelovescode
