### ISSUE TITLE
Convert a test to use react-testing-library instead of enzyme for the team to see if they like it better

### ISSUE THREAD

**Issue by jontrainor** [pieforproviders/pieforproviders#153]
## 📋 Summary
Convert a test to use react-testing-library so the team can see if they like it better than enzyme.

## 💻 Implementation Details
https://testing-library.com/docs/react-testing-library/intro

## 🧐 Why tho
In my experience, RTL has been easier to use and read than enzyme for react tests.

**Comment by katelovescode** [comment]
@jontrainor I think this can be marked approved, right?
