### ISSUE TITLE
Implement layout for onboarding pages accessible after login

### ISSUE THREAD

**Issue by cyranix** [pieforproviders/pieforproviders#154]
## 📋 Summary

Add a reusable page layout that applies to pages accessible by a logged in user. 

## 💻 Implementation Details

See Figma screens under "Account Ledger / Add a Payment" for (what I believe to be) the most complete design for the layout, which includes
* top navbar with 
  * white background
  * Pie logo and "Pie for Providers" title on left side
  * user profile picture on right side, which links to the profile page
  * navigation links for "Ledger", "Attendance", and "Search Cases"
    * which collapse behind a hamburger menu when the user is on a mobile device
* outermost content container with 
  * `#D4D4D4` background color
  * interior padding
* design components included:
  * Ant breadcrumb for "Setup"
  * Tailwind base shadow for header & main content

I'd like to ask for some extra guidance from a P4P designer to review the above. 

Additionally, I'm seeing a few different styles for the "page title" located between the top navbar and the main content area: breadcrumbs, larger blue text, smaller dark-gray text, and absent. Are these intended to be different based on viewport size, or more consistent? (This might not end up being part of the layout but could be useful context.)

## 🧐 Why tho

Spun out of #65 because I'm trying not to block development. I imagine that the onboarding workflow can continue to be developed (at least from a functional perspective) independently of adding the outermost page chrome.

Following the merge of #148, please apply this layout to that page. 🙇

**Comment by csprayregen** [comment]
top navbar with
- [ ] white background
- [ ] Pie logo and "Pie for Providers" title on left side
- [ ] user profile picture on right side, which links to the profile page
- [ ] navigation links for "Ledger", "Attendance", and "Search Cases"
- [ ] which collapse behind a hamburger menu when the user is on a mobile device
- [ ] outermost content container with
- [ ] #D4D4D4 background color
- [ ] interior padding
design components included:
- [ ] Ant breadcrumb for "Setup"
- [ ] Tailwind base shadow for header & main content
