### ISSUE TITLE
When I view the "Edit Attendance" Page, the edit icons show different states of activity

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1545]
## ✨ What new feature do you want to see?
When I view the "Edit Attendance" Page, the edit icon has three states:
-  normal
- hover
- focused

Out of scope (per discussion w @cjhaddad @csprayregen
disabled with popover explainer text

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧶 Acceptance Criteria

[Figma Behavior States (near bottom of frame)](https://www.figma.com/file/GAYeTfOa7umyAhssCHUf8d/P4P-2.0?node-id=5556%3A32631)

## Implementation Details
The easiest way to determine editability based on the Figma mockup (probably) is to include wonderschool IDs with attendances returned (nested under the service days) from the get endpoint in the service_days controller, and then check for the existence of a wonderschool ID in any of a service day's attendances before determining if a service day's attendance records are editable or if the icon should be disabled.

### Backend Work

- [x] Add `wonderschool_id` to the Attendance Blueprint
- [x] Add tests to ensure wonderschool ID is returned as a value or null in the JSON

### Frontend Work

- [x] Use the `wonderschool_id` field returned from the `service_days` endpoint (in the nested `attendance` records) to determine if an individual record is editable or not; if the `wonderschool_id` is present, the record is not editable.  If its value is null, the record is editable
- [ ] normal, hover and focused states should be applied via Tailwind or Ant Design as necessary

**Comment by rebeccakarasiktw** [comment]
Hi @katelovescode looks good to me! We can close this out :)
