### ISSUE TITLE
Add Authorized Weekly Hours to Inputs to S3

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1592]
## ✨ What new feature do you want to see?

Please add Authorized weekly hours to the Inputs to S3 onboarding spreadsheet.  They're currently displaying as part of the string in the dashboard view, but they're not on the onboarding spreadsheet.

## 🇺🇸 States this change applies to
- [ ] ALL
- [X] Nebraska
- [ ] Illinois

**Comment by JonErvin** [comment]
Updated in the production spreadsheet, testing spreadsheet, and dos.

**Comment by katelovescode** [comment]
Approved!
