### ISSUE TITLE
DB Implementation: Case Cycles & Child Case Cycles

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#160]
## 📋 Summary
Write the migration, model and controller actions necessary for basic CRUD on Case Cycles from the data model.

## 💻 Implementation Details
- This is an authenticated route
- Users will be managing case cycles on their account and will need authorization (i.e. they can only add/edit/update/delete case cycles associated to their account)
- All CRUD actions are required
- see docs/dbdiagram.dbml for field definitions and associations
- this work should include creating child_case_cycles as an association table, as children are already implemented as a model
- technically this work is blocked by #161 but the association can probably be made as a part of that ticket if this work comes first; if you pick up this ticket and 161 has no merged PR, please update that ticket to ensure the association is made

## 🧐 Why tho
Start getting the DB built to make front end tickets easier

**Comment by arku** [comment]
Done in #228, #293, #311, and #324.
