### ISSUE TITLE
DB Implementation: Subsidy Rules

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#161]
## 📋 Summary
Write the migration and model for Subsidy Rules from the data model.

## 💻 Implementation Details
- This will have no route; these records will be manually added to the db either through rake tasks or SQL
- Only admins with direct access to the db will be able to update these records
- see docs/dbdiagram.dbml for field definitions and associations

- rename "provider_type" to `license_type` to be consistent with other models

## 🧐 Why tho
Start getting the DB built to make front end tickets easier

**Comment by weedySeaDragon** [comment]
`qris_rating` is in this table as well as in the `sites` table. Does it represent the same concept with the same constraints/defined values (1..5)?
If so, should this be defined as an enum common to both?

**Comment by katelovescode** [comment]
👁️ not sure how I missed this, sorry.  The answer is yes, these are the same concept and should be handled by an enum; your choice on if you do it in this PR or another one.
