### ISSUE TITLE
DB Implementation: Agencies

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#162]
## 📋 Summary
Write the migration and model for Agencies from the data model.

## 💻 Implementation Details
- This will have no route; these records will be manually added to the db either through rake tasks or SQL
- Only admins with direct access to the db will be able to update these records
- see docs/dbdiagram.dbml for field definitions and associations

## 🧐 Why tho
Start getting the DB built to make front end tickets easier

**Comment by weedySeaDragon** [comment]
@katelovescode : Since these will only be updated externally (rake, direct to db, etc), 
then are these _read only_ ?  In which case the only controller actions should be `index` and `show` ?

**Comment by weedySeaDragon** [comment]
@katelovescode also:  Does the `state` attribute refer to a State in the United States like "Illinois" ?   
or does it refer to a "status" ?
(So I know what to put in `db/seeds.rb` and `spec/factories/agencies.rb`)
