### ISSUE TITLE
[BUG staging] Attendance risk is wrong for 7560

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1626]
## 👉🏼 Steps to Reproduce

1. Go to Staging
2. Log in as Nebraska user
3. Look at the child w/ Wonderschool ID 7560
4. Attendance risk says "at risk" but should be "on track"

## 🇺🇸 States this bug is happening in
- [ ] ALL
- [X] Nebraska
- [ ] Illinois

## 🧥Expected behavior

Child's attendance risk should be "on track"

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

- Operating System: [e.g. iOS]
- Browser [e.g. Chrome, Safari]

## 🏓 Implementation Details

Check the calculations for on-track/at-risk inside the child model

**Comment by csprayregen** [comment]
Addressed
