### ISSUE TITLE
DB Implementation: Payments

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#165]
## 📋 Summary
Write the migration, model and controller actions necessary for basic CRUD on Payments from the data model.

## 💻 Implementation Details
- This is an authenticated route
- Users will be managing payments on their account and will need authorization (i.e. they can only add/edit/update/delete payments associated to their account)
- All CRUD actions are required
- see docs/dbdiagram.dbml for field definitions and associations
- technically this work is blocked by #162 and #159 but the association can probably be made as a part of those tickets if this work comes first; if you pick up this ticket and 159 or 162 has no merged PR, please update the appropriate tickets to ensure the association is made

## 🧐 Why tho
Start getting the DB built to make front end tickets easier

**Comment by weedySeaDragon** [comment]
@katelovescode  - just wondering -- should this be closed now?  Just learning what the overall workflow is.  (And I assume you should close it, yes?)
