### ISSUE TITLE
Investigate Events in Hotjar

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1656]
## 📋 Summary
Review GA analytics events tickets for examples of what we would want

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by csprayregen** [comment]
@cjhaddad @katelovescode @rebeccakarasiktw I'd love to review this during our next check in. My take is that we can probably get the info we need in Hotjar without events at this point, and can deprioritize this, but let's open it up and click around together. 

Documenting possible next steps after that (I can ticket these when we agree):
- Add "Add Attendance" page to Hotjar (is this necessary or automatic?)
- Add "View Attendance" page to Hotjar
- Set up analyticis views/reports we'd like in Hotjar (if needed)

**Comment by rebeccakarasiktw** [comment]
Hey @cjhaddad I can see the events and it all looks good to me! I did notice there seem to be 2 events for attendance, was that a result of your testing or is it something we need to look into?
![image](https://user-images.githubusercontent.com/26929739/140559428-0c73e8ac-add6-4ebb-b42e-36bb3978a86f.png)

**Comment by cjhaddad** [comment]
@rebeccakarasiktw every event in this list aside from 'save_attendance' was created when I was testing and troubleshooting the events. The current state of our code will only ever trigger a 'save_attendance' event. The extra ones are lingering from the test code. Let me know if this needs more explanation and we can talk!
