### ISSUE TITLE
Fix summary stats in Nebraska dashboard 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1697]
## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧶 Acceptance Criteria

- [ ] Comment out three undeveloped summary stats: Max revenue, total approved, total approved with family fee 
- [ ] Remove conditional - display even if there is attendance data and roll up to zero if there's no attendance data. Only applicable to earned and estimated revenue.

**Comment by csprayregen** [comment]
Hey @cjhaddad this looks good in English, but it's not being translated to Spanish. The Spanish translation you need is here: https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=1049848154

Additionally, @katelovescode can I QA the second QA related to the conditional? Happy to trust you two on this if it's hard to check on staging. 

Screenshot:
<img width="1088" alt="Screen Shot 2021-09-25 at 8 43 53 AM" src="https://user-images.githubusercontent.com/26717304/134773674-f6be570a-d497-495c-8883-e7c68166c701.png">

**Comment by katelovescode** [comment]
Yes, I can delete all the attendances on staging and you can check again, and then you can run the attendances rake task to repopulate. Let me know if you want me to do that this weekend.
