### ISSUE TITLE
Override the tailwind sm md lg breakpoints with ours

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#172]
## 📋 Summary
Tailwind has sm md lg breakpoints and we wrote our own custom ones ("small" "medium" "large").  I'd rather override the default ones if we can, so this is a spike to find out if we can do that, and if so, a task of doing it. 😂

**Comment by katelovescode** [comment]
@csprayregen for prioritization

**Comment by Khush1801** [comment]
Is this issue still open? If yes can I work on it?

**Comment by katelovescode** [comment]
> Is this issue still open? If yes can I work on it?

No, this issue has been finished, please take a look at our project board for open tickets!
