### ISSUE TITLE
Spike: After TX implementation, fully refactor NE

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1752]
## 📋 Summary

[Milestone 21](https://github.com/pieforproviders/pieforproviders/milestone/21) has all the steps that we need to do right away to prep the tables/data model for updated implementation, but no logic for refactoring the calculators for Nebraska, or business logic, or pulling anything out of the child model, etc.  This is a spike placeholder to do that work and backport the new changes to NE.

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by csprayregen** [comment]
Out of date - started refactor with NE before TX
