### ISSUE TITLE
[Spike] Is preschool age- or enrollment-based

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1759]
## 📋 Summary

The child with DHHS ID ending in *6689 has three approval letters in our Google Drive, and they go from infant service, to toddler service, to preschool service faster than we would have anticipated; the child was not even 2 years old when they were moved into preschool.  This requires some more research.

## 🇺🇸 States this change applies to
- [ ] ALL
- [X] Nebraska
- [ ] Illinois

**Comment by csprayregen** [comment]
@katelovescode @JonErvin documenting the response from DHHS here: Preschoolers are defined as children age 36 months to school-age.

Despite this confusing individual case, we will not make any changes to our rules at this time. We should consider a manual override for the provider in the future.
