### ISSUE TITLE
[Design task] Add state to signup form & flow

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#1760]
## ✨ What new feature do you want to see?

Add ability for user to choose state in signup
Because we want to be able to direct users to specific flows and dashboards, and also know when users are signing up who are in states where we are not active yet.

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by katelovescode** [comment]
Dupe
