### ISSUE TITLE
Upgrade RSwag config to Swagger 3.0 API

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#177]
## 📋 Summary
We should upgrade RSwag and update the configuration to use the Swagger 3.0 spec

## 🧐 Why tho
moderniiiiiiiizzzzeeeee

## 🛥️ Implementation Details
Here's a really great breakdown of the differences in Swagger 3.0: https://blog.readme.com/an-example-filled-guide-to-swagger-3-2 - my favorite part is specific components vs definitions

Also Rswag's readme has a cool explanation about anyOf, oneOf and allOf schemas: https://github.com/rswag/rswag#support-for-oneof-anyof-or-allof-schemas

Nullable values: https://github.com/rswag/rswag#null-values

This will have to be implemented when we get auth working in Swagger: https://github.com/rswag/rswag#specifyingtesting-api-security

Also looks like we have the ability to reference nested definitions (this is probably true in 2.0 too): https://github.com/rswag/rswag#referenced-parameters-and-schema-definitions (cc @weedySeaDragon this would solve that "creates need required fields but updates don't" issue)

**Comment by katelovescode** [comment]
@csprayregen for prioritization

**Comment by weedySeaDragon** [comment]
Other than changing the `Gemfile` to specify `~> 2.3` for the rswag gems, what else needs to be done?
(I don't really understand the implications beyond the Rails stuff, but want to.)

**Comment by katelovescode** [comment]
@weedySeaDragon added some implementation details, hopefully will answer your question!
