### ISSUE TITLE
As a user, I can access My Profile from the navigation

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#1798]
## ✨ What new feature do you want to see?
Add "My Profile" to the navigation bar in all device sizes.

## 🧶 Acceptance Criteria
- [x] My navigation has a link to "My Profile"
- [x] When I click that link, I am taken to my profile page.
- [ ] When I open the navigation, I can see that I am in my profile page (selected state).
- [x] In large devices, I can see an avatar with the first letter of my name, and I can see My Profile option in the dropdown (like in Figma)
- [x] In medium & small devices, I see the My Profile option in the menu (like in Figma)

## 🖍️ Implementation Details

[Figma link here](https://www.figma.com/file/huYplw9zgeVy3pPUaXhzan/P4P-Design-System?node-id=335%3A492)
Please note the design and layout changes in different device sizes

Avatar component in Ant design that we want to use: https://ant.design/components/avatar/

**Comment by rebeccakarasiktw** [comment]
Sorry, I accidentally moved this card to Approved, but I moved it back.

**Comment by csprayregen** [comment]
Hi @nicorinn this looks great! We are just missing one AC: When I open the navigation, I can see that I am in my profile page (selected state). Please let me know if you have any questions.

**Comment by cjhaddad** [comment]
@csprayregen  this is QA-able at: https://pie-peline-uchicago-tec-nuwjh6.herokuapp.com/

**Comment by csprayregen** [comment]
CS QA:
- [ ]  My navigation has a link to "My Profile"
- [ ]  When I click that link, I am taken to my profile page.
- [ ]  When I open the navigation, I can see that I am in my profile page (selected state).
- [ ]  In large devices, I can see an avatar with the first letter of my name, and I can see My Profile option in the dropdown (like in Figma)
- [ ]  In medium & small devices, I see the My Profile option in the menu (like in Figma)
