### ISSUE TITLE
User comms: update new user comms to reflect hours/days per approval period 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1813]
## ✨ What new feature do you want to see?
Update email 3 in new user comms to include the hourly and daily units per approval period fields. See note in this doc: https://docs.google.com/document/d/1rLsYhNquU0xu2OusW548emAsXudgysD-N-FXRlt5KuI/edit#

This is not a product update, but a communication about a product update, once the relevant tickets in this milestone are complete. 

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by katelovescode** [comment]
@csprayregen we can add a user-comms label or something if you want to mark things for that purpose like we do design and data!  Or any other tag that makes sense, just let me know
