### ISSUE TITLE
Remove 2 questions in the signup page

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#1849]
## ✨ What new feature do you want to see?
In order to streamline the onboarding process, we are removing some fields in our sign up page. 

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧶 Acceptance Criteria
[ ] On the signup page, I no longer see the "Name of Organization" field
[ ] On the signup page, I no longer see the "Are you managing subsidy cases for multiple child care businesses" field
[ ] This works in both English & Spanish

**Comment by csprayregen** [comment]
Dupe with #2212
