### ISSUE TITLE
API: Set up Internationalization

### ISSUE THREAD

**Issue by arku** [pieforproviders/pieforproviders#185]
Related to https://github.com/pieforproviders/pieforproviders/issues/23

## ✨ What new feature do you want to see?
The errors returned from the API are i18ned (English and Spanish)

## 🏖 Implementation Details

The validation errors, the model, and field names (_email_ should be translated to _correo_ for example) should be translated.

**Comment by katelovescode** [comment]
@csprayregen ready for prioritization
