### ISSUE TITLE
Re-implement Google Analytics to what it was

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1875]
## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by rebeccakarasiktw** [comment]
Hey @cjhaddad I'm not sure if this is in production yet but I think our production analytics are being sent to staging.
Ex 1 - Right now I'm in production and I can see the data showing up in staging Realtime

<img width="1792" alt="Screen Shot 2021-11-07 at 19 01 21" src="https://user-images.githubusercontent.com/26929739/140667209-6d07fe2d-9eac-461f-bf44-8a43f6bb6874.png">
<img width="1792" alt="Screen Shot 2021-11-07 at 19 01 14" src="https://user-images.githubusercontent.com/26929739/140667213-df5fb64e-4e33-46a8-8381-3ecabda13cbf.png">

Ex 2 - In this report it looks like the user IDs in Stg are our IDs in production:
https://analytics.google.com/analytics/web/?authuser=3#/p261972964/reports/explorer?params=_r.explorerCard..selmet%3D%5B%22newUsers%22%5D%26_r.explorerCard..seldim%3D%5B%22userAcquiredCampaignMedium%22,%22userProperty:1%22%5D%26_u..nav%3Dmaui%26_r.explorerCard..sortKey%3Dd-1&r=lifecycle-user-acquisition&ruid=lifecycle-user-acquisition,life-cycle,acquisition&collectionId=life-cycle
