### ISSUE TITLE
As a user, if I don't use the Pie for Providers sample spreadsheet I get an error message telling me to use it.

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#190]
✨ What new feature do you want to see?
As a user, if I don't use the Pie sample spreadsheet, I get an error message telling me to use  it.

🧶 Acceptance Criteria

- [ ] When I try to upload the data using a spreadsheet that doesn't match our sample, I see an error telling me to use the Pie sample spreadsheet

🖍️ Implementation Details

Right now, all we're doing is chopping the first three rows off to accommodate our sample spreadsheet before parsing data. 

For MVP, we don't want anyone to upload a spreadsheet that doesn't match our sample.  

We want a slightly more restrictive way of checking that they're using the right format so we can alert them and not parse wrong data.

Pie sample spreadsheet: 
[UPDATED Pie for Providers Sample Spreadsheet 9-29.xlsx](https://github.com/pieforproviders/pieforproviders/files/5302460/UPDATED.Pie.for.Providers.Sample.Spreadsheet.9-29.xlsx)

**Comment by csprayregen** [comment]
@rebeccakarasiktw I think this one needs design too? Hopefully very simple...

**Comment by rebeccakarasiktw** [comment]
@csprayregen good point, I updated the Error message. I believe there are 2 types of errors: 

1. Uploading wrong file type
2. Uploading wrong spreadsheet format
And the error message could change in both of those scenarios. What do you think?
![image](https://user-images.githubusercontent.com/26929739/94996724-4ceedd80-0574-11eb-8c0a-e8b00abec7dc.png)

Here is the mockup with the error message:
<img width="603" alt="Screen Shot 2020-10-03 at 12 15 05 PM" src="https://user-images.githubusercontent.com/26929739/94996737-58da9f80-0574-11eb-8b78-25ef19937a77.png">

**Comment by csprayregen** [comment]
Per discussion today, we don't need this ticket. File type error is already in staging (you simply can't select a file that's the wrong file type), and we'll remind users to use our sample spreadsheet in the following screen if they're data doesn't look right.
