### ISSUE TITLE
i18n for emails sent

### ISSUE THREAD

**Issue by weedySeaDragon** [pieforproviders/pieforproviders#196]
## 📋 Summary

#23 
All emails sent to users must be in the preferred language for the user.

## 💻 Implementation Details

Email are sent by the backend (Rails server).  The mail views need to include I18n.t() as necessary.
- locale files need to be updated to include the information necessary for the emails

## 🧐 Why tho

All user interactions must be available in all necessary languages.

**Comment by csprayregen** [comment]
Closing as this is now covered by specific tickets for each email and its full stack functionality
