### ISSUE TITLE
Update spreadsheet to calculate from effective date, not first of month

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1962]
## 📋 Summary
Per bug fixing meeting this morning

When this is done, please double check prod vs. spreadsheet to confirm this has addressed discrepancies for the two children with mid-month effective dates. 

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by JonErvin** [comment]
Scratch notes to remember context for this issue:

- For WS IDs 6998 and 6999 whose authorization begins 11/5/21
- Currently spreadsheet does not take into account active / not active child approval letter in translating attendance records to revenue
- Desired behavior is spreadsheet assigns zero units and zero revenue if no active approval to apply it to

Need to:
- In Daily Calculation, add check for number of valid authorization periods for date of attendance (0, 1, 2+)
- If 0, zero out everything and raise error to dashboard (# of attendance days with 0 valid approvals)
- If 2+, keep logic as is (doesn't affect anything mechanically) but raise error to dashboard

Validate with:
- 6998 and 6999 11/1/21 record should zero out and raise error on dash
- Add fake overlapping period to test 2+ logic (data valid, raise error on dash)

**Comment by JonErvin** [comment]
Updated!  Spreadsheet now works as described above (attendance records will zero out if there's no active approval).  Summary of changes, also captured here ([P4P Nebraska Model Documentation](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#)):

**Daily Calc Helper**
 - new active approvals column
 - new approval errors column
 - Revised calculated minutes column (to zero out if zero active approvals)

**Dashboard - error tracker**
 - New "no approvals" and "multiple approvals" trackers

**Table 1: Unit Calculation**
 - Added a zero row, with zero units to avoid errors when zeroing out above

**Comment by JonErvin** [comment]
Reopening to also include absences here

**Comment by JonErvin** [comment]
Alright @katelovescode this one is actually complete now.  Validated the AC above for 6998 and 6999 plus confirmed for a few others with approvals beginning or ending in November.  Absences are now only included if a child has an active approval. 

Summary of changes:

**Absences table**
- New active approval boolean
- Updated score field to be 0 if active approval = FALSE
- Updated inlcusion flag to be 0 if active approval = FALSE

Update in [docs](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#heading=h.26u73f4embcc) as well
