### ISSUE TITLE
Check performance for centers

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1972]
®## 📋 Summary

- View videos or do in person screenshares with one of our Center users to ensure performance issues aren't preventing the dashboard from loading at all for them.
Performance issues with center user confirmed, see related recordings here: 
https://insights.hotjar.com/sites/2575575/highlights/5104
Issues observed:
- Loading times from 8-27 seconds
- 1 instance of longer loading time (4+ secs) in attendance page
- One instance of very fast loading time after user logs out and back in again

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by rebeccakarasiktw** [comment]
@katelovescode can you help me add details for this card?

**Comment by katelovescode** [comment]
@rebeccakarasiktw added!

**Comment by katelovescode** [comment]
@rebeccakarasiktw we released to prod last week, maybe when you get back in January, you can do a quick review of videos and see how this is going?
