### ISSUE TITLE
Summing Totals bug

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1987]
## 👉🏼 Steps to Reproduce

Pre-setup: delete all your attendances to ensure the kids all have $0 earned revenue, this helps to isolate the problem

1. Click on "Record New"
2. Click on "Payment"
3. Check a box that says "I received a different amount from the state"
4. Type in a large number
5. The sum in the button doesn't seem to be correct, likely due to rounding in large numbers
6. With a large enough number, eventually it displays the number in e+... format

## 🇺🇸 States this bug is happening in
- [ ] ALL
- [X] Nebraska
- [ ] Illinois

## 🧥Expected behavior

@rebeccakarasiktw can you determine desired behavior on this?  I know it's like a 0% use case but just want to make sure you see this.  If this behavior is okay, close this ticket.

## 📸 Screenshots

![summing](https://user-images.githubusercontent.com/8364647/144273004-a3e2857f-2076-4b92-a3dd-61cf6d023ef7.gif)

![Screen Shot 2021-12-01 at 10 31 26 AM](https://user-images.githubusercontent.com/8364647/144274117-7442cf6d-056d-4558-bc4a-6f88511400f9.png)

## 💻 Browser Info

- Operating System: Mac Monterey
- Browser: Chrome
- Version: 96.0.4664.55 (Official Build) (x86_64)

**Comment by csprayregen** [comment]
@katelovescode @davidcandeau this seems to be creating some strange behavior where the number in the open text fields rounds to 1 and then a bunch of zeroes, but the summed total is what you would expect (with a certain number of digits limited) in the button itself (and therefore in the total that actually gets saved):


<img width="904" alt="Screen Shot 2022-04-01 at 9 36 16 AM" src="https://user-images.githubusercontent.com/26717304/161285560-395436a3-ee55-4fe3-9a86-5472589709ed.png">
<img width="997" alt="Screen Shot 2022-04-01 at 9 36 51 AM" src="https://user-images.githubusercontent.com/26717304/161285563-e65dd89e-aaca-419f-b6b3-f4fb461287ba.png">
<img width="620" alt="Screen Shot 2022-04-01 at 9 38 06 AM" src="https://user-images.githubusercontent.com/26717304/161285565-4bea9459-ace9-4340-8202-de6ddd0a1d8e.png">
