### ISSUE TITLE
Can type letters in the number fields

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1988]
## 👉🏼 Steps to Reproduce

1. Click on "Record New"
2. Click on "Payment"
3. Check a box that says "I received a different amount from the state"
4. Letters are able to be entered in the now-enabled text box

## 🇺🇸 States this bug is happening in
- [ ] ALL
- [X] Nebraska
- [ ] Illinois

## 🧥Expected behavior

Letters should not be enterable in the box

## 📸 Screenshots

![letters](https://user-images.githubusercontent.com/8364647/144274783-d5eace27-52b1-4a67-b007-350043999b14.gif)

## 💻 Browser Info

- Operating System: Mac Monterey
- Browser: Chrome
- Version: 96.0.4664.55 (Official Build) (x86_64)

**Comment by davidcandeau** [comment]
The letters are never saved and they are cleared. Anything in particular that we want to do here? There are no antD properties to prevent this @cjhaddad.

**Comment by katelovescode** [comment]
@rebeccakarasiktw what's the ideal state here?  Do we want non-numeric characters to be ignored? (except `.` maybe for cents).  If so, @davidcandeau , we might be able to find a non-antD way of validating/ignoring alpha characters.  If not, I think we can close this as not necessary.

**Comment by davidcandeau** [comment]
I think ignored might imply that they stay in the input, but are not used in the payment value. It's more like once a user inputs the non-numeric character, it gets filtered out of the input and remove from UI as well.

**Comment by rebeccakarasiktw** [comment]
hi @davidcandeau what you are suggesting in your comment sounds like the right behavior to me "once a user inputs the non-numeric character, it gets filtered out of the input and remove from UI as well." as long as it's not saved and not in the UI I think we're good, and that's preferable to adding an error message.

**Comment by katelovescode** [comment]
@rebeccakarasiktw so should we close this issue, as-is?  I can spin up the `atlassian` environment if you want to double-check for yourself.

**Comment by rebeccakarasiktw** [comment]
@katelovescode yeah I would love to check first before we close it, thanks!!
