### ISSUE TITLE
Unchecking box reverts to original state unless value is blank or zero

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1989]
## 👉🏼 Steps to Reproduce

1. Click on "Record New"
2. Click on "Payment"
3. Check a box that says "I received a different amount from the state"
4. Remove "Enter Amount" until the $ is the only thing displaying
5. Uncheck the box
6. The placeholder does not change back to "Enter Amount"

## 🇺🇸 States this bug is happening in
- [ ] ALL
- [X] Nebraska
- [ ] Illinois

## 🧥Expected behavior

The text box reverts to the placeholder value

## 📸 Screenshots

![zerodoesnotclear](https://user-images.githubusercontent.com/8364647/144275116-effb4266-a148-486f-97bb-98db93a080ae.gif)

## 💻 Browser Info

- Operating System: Mac Monterey
- Browser: Chrome
- Version: 96.0.4664.55 (Official Build) (x86_64)

**Comment by davidcandeau** [comment]
Can't seem to reproduce this? Can you verify it is still a bug?
![BugGIF](https://user-images.githubusercontent.com/44675440/149984764-ebc10908-67d5-4f2f-afc1-92ce5c7ad0bc.gif)

**Comment by katelovescode** [comment]
Confirmed, can't reproduce this.  🤷🏼
