### ISSUE TITLE
Family fees not appearing correctly for all children 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1993]
## 👉🏼 Steps to Reproduce

For some rows on the Family Details page, the wrong number of children are appearing as associated with the family fee. For all of these cases, there are multiple authorizations listed in the Child Details page, and we seem to be pulling the a child into the family fee row more than once. However, we are NOT experiencing this bug for all children with multiple authorization periods. 

Affected case numbers are:

- 0089584
- 00107680
- 00240641
- 00725977
- 00663422

## 🇺🇸 States this bug is happening in
- [X] ALL
- [x] Nebraska
- [ ] Illinois

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

- Operating System: [e.g. iOS]
- Browser [e.g. Chrome, Safari]

**Comment by JonErvin** [comment]
Update: Replaced formula in FamilyLevelData, NumberOfChildrenInCase to first pull an array of unique children that match case number and then count them (prevents duplicate counting).
