### ISSUE TITLE
Rates on authorization letters not matching rates in the app 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#1994]
## 👉🏼 Steps to Reproduce

For at least a couple children, the rate listed on the authorization does not match the rate in our app or in the source we found. Case numbers where this occurs (potentially a non-exhaustive list - we haven't looked closely):

- 00695595
- 00317990

This issue was identified as part of onboarding a center, but we should look at our FCC authorizations and see if we have a mismatch there. 

After understanding what our mismatch is, we can follow up with two sources to understand the situation: the state DHHS office and our providers. There is a chance the provider is charging  a rate lower than the state's reimbursement rate to private pay parents. In that case, the state pays the lower rate. 

Our source for rates is here: https://dhhs.ne.gov/Pages/Child-Care-Regulations.aspx (title 392 guidance document)

## 🇺🇸 States this bug is happening in
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

- Operating System: [e.g. iOS]
- Browser [e.g. Chrome, Safari]

**Comment by MsLoriMcNeill** [comment]
Hi @katelovescode and @csprayregen!

Pulling out the different values I found that at least the rates in the letters are consistent for a given service code:
Infant care - $48/day | $7.60/hr
Toddler care - $45/day | $7/hr
Preschool care - $39.20 | $6.50
([here's that data](https://docs.google.com/spreadsheets/d/1mn0bakiPeoP79bd1LWj7v_WVijKVyJudKDmGrPetN-4/edit#gid=1946242020))
So now the question is, are the letters just wrong (Kate guesses that the rates have not been updated to match what the state published), or is this really what people are getting paid? 🤔

**Comment by katelovescode** [comment]
@csprayregen when we met with @JonErvin and @MsLoriMcNeill on Monday Jon took a look and it seems like these are *pre-July* rates specifically for *centers*, which we don't have in the app because we didn't start doing Center rates until after July.  So the pattern seems to be that these are the old rates?

**Comment by MsLoriMcNeill** [comment]
Y'ALL (= @csprayregen @katelovescode @JonErvin ).
I think that the explanation might come down to what CRCC charges private pay enrollees. Per the Rate Unit Authorizations section here: https://www.nebraska.gov/rules-and-regs/regsearch/Rules/Health_and_Human_Services_System/Title-392/Chapter-3.pdf

"004.01 PROVIDER RATES. A provider must establish a private pay rate before being
approved as an enrolled provider. Child Care Subsidy payments to a provider will not exceed
the private pay rate. If the rate the provider charges the public is higher than the Department's
rate, the Department will pay the Department’s established maximum. **If the provider's rate
for the public is lower than the Department's maximums, the Child Care Subsidy rate paid to
the provider will not be more than the provider’s rate charged to the public.**"

All of the rate discrepancies show an authorized amount that is lower than published rates (except one, but the issue there is that we have him as preschool care but the auth letter is for toddler care), which would be appropriate if CRCC's private pay rates reflect what we're seeing in the letters. So then the question for us to ask in the email could be something like...
"We noticed that the authorization letters for your families show lower daily and hourly rates than the amounts the state has published. Are you able to share with us what your private pay rates are? Or, if you prefer, can you tell us if the rates listed below match what you have provided to the state as your standard rates?
Infant care - $48/day | $7.60/hr
Toddler care - $45/day | $7/hr
Preschool care - $39.20/day | $6.50/hr"

Thoughts?

**Comment by csprayregen** [comment]
@MsLoriMcNeill interesting theory - I think that's a really good guess! We'll use this language to reach out to them soon - thanks so much.

**Comment by csprayregen** [comment]
Current hypothesis: provider has lower private pay rate than state max and therefore rates don't match. Ticketed custom rates separately.
