### ISSUE TITLE
Login page won't load directly

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#200]
## 🤬 What's wrong?
Hitting /login directly returns JSON instead of showing the login page

## 👉🏼 Steps to Reproduce

visit https://pie-staging.herokuapp.com/login

## 🧥Expected behavior
It should show the login page, not JSON!

## 📸 Screenshots
<img width="619" alt="Screen Shot 2020-08-21 at 5 03 02 PM" src="https://user-images.githubusercontent.com/8364647/90939049-3d567380-e3d0-11ea-9172-0c301042fa22.png">

**Comment by csprayregen** [comment]
Fixed!
