### ISSUE TITLE
[Placeholder] [Analytics] Marking child inactive triggers 2 events

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2047]
## 👉🏼 Steps to Reproduce

![Screen Shot 2021-12-17 at 08 32 21](https://user-images.githubusercontent.com/26929739/146553016-a05e55f8-fbbf-498f-9222-247eea8b46bc.png)

## 🇺🇸 States this bug is happening in
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

- Operating System: [e.g. iOS]
- Browser [e.g. Chrome, Safari]

**Comment by katelovescode** [comment]
@rebeccakarasiktw I tested this in local development and it doesn't seem to be happening anymore, can you confirm on staging?

**Comment by rebeccakarasiktw** [comment]
Hey @katelovescode I am able to confirm this is happening in staging. But we can move it back to the backlog since it won't affect our metrics ( we will just track 1 of the events, not both of them)
<img width="518" alt="Screen Shot 2022-01-19 at 17 55 51" src="https://user-images.githubusercontent.com/26929739/150231918-1c65ce79-a582-4845-bd1e-0f00546a6a09.png">

**Comment by katelovescode** [comment]
That's weird - I can't find `Child_Marked_Inactive` anywhere in the codebase at all.  Is it possible that's an old event name and it's old data?  What date range were you using?
