### ISSUE TITLE
Spreadsheet error - logic for multiple checkins

### ISSUE THREAD

**Issue by JonErvin** [pieforproviders/pieforproviders#2071]
## 🇺🇸 States this bug is happening in
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧥Expected behavior

Acceptance Criteria from Kate (12/21)

 if a child has a single check-in with no check-out:
 - if the day has a schedule, the duration of that attendance should be the scheduled amount of duration
 - if the day has no schedule, the duration of that attendance should be 8 hours
 
if a child has one or more check-ins with a check-out AND one or more check-ins with no checkout
 - the duration of the ServiceDay should be the actual attended amount + whatever it takes to get to the scheduled duration
 -  if the actual attended amount is over the scheduled duration, use the actual attended amount and don't reduce it, all other attendances count for 0 duration

if a child has one or more check-ins and NONE have a check-out
 - use the scheduled duration
## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

- Operating System: [e.g. iOS]
- Browser [e.g. Chrome, Safari]

## 🍣 Additional context

Currently spreadsheet just used schedule IF >1 "no end time".  Need to first check if total duration of valid check-in records is greater than schedule and, if so, use that instead.

**Comment by JonErvin** [comment]
@katelovescode This should be good to go.  The logic at the ServiceDay level is the following (should match the ACs above):

IF all check-ins have check-outs: just sum duration of all records
IF 1+ check-in is missing check-out:
- Sum duration and compare to schedule (use 8 hrs if no valid schedule).  If duration is greater use duration
- If schedule is greater use schedule

We only have three instances of multiple check-in / check-out pairs in Wonderschool so far, and none have create the condition in the AC:

> if the actual attended amount is over the scheduled duration, use the actual attended amount and don't reduce it, all other attendances count for 0 duration

To fix that, I temporarily adjusted a record to increase the attended amount and it worked as expected.  The other ACs are confirmed in the spreadsheet using real data.

Summary of changes (DailyCalculation table):

- New `Num. Records this day` (helper)
- New `Num. Records without end time` (helper)
- New `Minutes with valid checkout` (helper)
- Updated `Calculated Minutes` to add logic comparing Minutes with valid checkout to ScheduledHours * 60 (using 8 if ScheduledHours is 0) and using the greater of the two, if there's 1+ missing check-out.

Updated in [docs](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#) as well

**Comment by katelovescode** [comment]
What you're doing with these spreadsheets is wizardry!  Thank you!
