### ISSUE TITLE
Spreadsheet Issue - Limit totals do not include absences

### ISSUE THREAD

**Issue by JonErvin** [pieforproviders/pieforproviders#2073]
## 🇺🇸 States this bug is happening in
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧥Expected behavior

Currently spreadsheet only total attended hours from attendance records (i.e. from DailyCalc tab) into limit totals (specifically Weekly Hours, Days Used in Authorization Period, and Hours Used in Authorization Period).  Need to include absence records here

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

- Operating System: [e.g. iOS]
- Browser [e.g. Chrome, Safari]

## 🏓 Implementation Details

Could either:
- Adjust model to create absence attendance records like the real app (more robust, more effort) OR
- Build simple shortcut to also sum absence records (quicker fix)

**Comment by JonErvin** [comment]
@katelovescode This one might be good to talk through next week.  Realized that this might more be complex that I initially thought.

The reason is that the spreadsheet treats absences differently than the real app to limit the data storage / processing for the Google Sheets (poor Google Sheets recalculates entire tables so often that it can't handle what the real app can).  Specifically, absences and the table it relies on (Created Daily Schedule) could be too large if we include the full historical record - therefore as a shortcut it only stores Absence and Schedule Data for the current month. They just recalculate when we switch the Current Date. 

Even with this shortcut, they are pretty big tables right now (1000 records for Absences, 5000 for Created Daily Schedule), with many calculation fields for each record.  They grow quickly with every new child added (~30 new records in Created Daily Schedule for each new child).  If we expand to the full historical record this would mean, say, ~10x the size of each table (e.g., adding 11 months for a typical annual approval letter).

Given this, I wonder what's critical for the spreadsheet to handle, knowing we still hope to retire it (soon?).  A few options I see:
- Match the app exactly, with the full historical record for Absences.  Likely a pretty significant lift to pull off and could risk making the spreadsheet too big to function, unless we find a different shortcut
- Don't make this change in the spreadsheet at all, and know that limit totals will be off.
- Make the change for `Weekly Hours` but not for `Authorized Hourly Units Used` or `Authorized Daily Units Used`.  This might be easier because this is close to accurate currently.  We would need to just include the last week of the prior month to make sure we include absences in current week but previous month.  Also, `Weekly Hours` is currently shown in the app but, to my knowledge, the other two fields aren't yet.  Still would take some effort (maybe 3 hrs including validation) but could be worth it if important

Thoughts?  Maybe we talk through in voices next Monday?

**Comment by katelovescode** [comment]
Yeah let's chat about this next week, I have lots of thoughts :)

**Comment by JonErvin** [comment]
Kate/Jon decided to just fix Weekly Hours.  Will leave Authorized Hours and Days as they are.

**Comment by JonErvin** [comment]
@katelovescode Think this is knocked out.  See changes below, also reflected in [docs](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#).  The `Hours Attended` field now includes absences (hours determined by schedule).  This also includes any absences in the previous month, in the event the current week spans multiple months.

Note that this will only include the top 5 absences, sorted first by number of hours scheduled greatest to least, then chronologically from earliest to latest.  Therefore, in a default M-F, 8 hour schedule, absences earlier in the month are more likely to count toward hours attended than are absences later in the month.

**Summary of Changes:**

- New `Hours Billed` field in Absences
- New Table: Absences - Prev Month.
- New Table: Created Daily Schedule - Prev Month
- Revised `Completed Hours This Week` field in Summary By Child to also sum `Hours Billed` in Absences and Absences - Prev Month.
- New Date Variables in Summary By Child: `Prev Month Begin Date`, `Days in Prev Month`

**Validation:**

- `Weekly Hours` includes absence hours: WS ID 14437, Date 1/27/22.  Correctly includes 33 hours, 17 from attendance (2 days), 16 from absences (2 days)
- `Weekly Hours` includes absences hours from prev month in week spanning multiple months: WS ID 10668, Date 1/1/22.  Correctly includes 16 hours from two days of absence in last week of previous month, December 2021 (12/27 and 12/28).
