### ISSUE TITLE
Refactor to improve the PUT endpoint for attendances

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2080]
That was a quick temp fix for the gif problem but I will be changing the behavior. There is nothing in the code that prevents a service day of having two attendance absences.  I was also planing on writing a hook to remove not only the other attendances with absences but all other attendances of the service day to satisfy: 

> If I change an attendance to an absence, all other attendances for that ServiceDay are deleted - we can only have one absence per day, and no other types of attendance if there's an absence

I would then change that remove absences hook to a custom validation that prevents two absences for a service day.

This case will require refactoring as well:

> if I change the check_in time to a time that belongs to a different service_day (i.e. before midnight to the day before or after midnight to the day after), the ServiceDay for the new date is created if it doesn't exist already, or the attendance is associated to the existing ServiceDay for that date
>  All absence requirements above apply here as well; if I change the check_in time to another date, and it's an absence, the above actions happen as well

_Originally posted by @twinsfan421 in https://github.com/pieforproviders/pieforproviders/pull/2057#discussion_r774304055_

**Comment by katelovescode** [comment]
@twinsfan421 Just checking in, how's this going?  Need any assistance?

**Comment by twinsfan421** [comment]
> @twinsfan421 Just checking in, how's this going? Need any assistance?

I am finishing up.  I will be submitting a pull request soon.  You can check it out here
https://github.com/pieforproviders/pieforproviders/compare/PIE-2080/api_endpoint_put_attendance_refactor?expand=1
