### ISSUE TITLE
Dashboard makes API call twice

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2121]
## 👉🏼 Steps to Reproduce

Explanation in the following slack conversation:
<img width="647" alt="Screen Shot 2022-01-10 at 10 23 55 AM" src="https://user-images.githubusercontent.com/8364647/148800966-23673e6b-e0f9-42be-9fd4-cf508953bbde.png">

## 🇺🇸 States this bug is happening in
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧥Expected behavior

The API will only be hit one time on `case_list_for_dashboard` - it's an expensive query and shouldn't be called unless strictly necessary

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

- Operating System: [e.g. iOS]
- Browser [e.g. Chrome, Safari]

**Comment by anniekao** [comment]
Hi @katelovescode , would it be alright if I had a go at this issue?

**Comment by katelovescode** [comment]
@anniekao Yes please!

**Comment by katelovescode** [comment]
@anniekao I gave you "Triage" access - it's my first time using that setting!  Let me know if you can move your ticket to "In Progress" on our MVP project with that access; if not I'll upgrade you to "Write" :)

**Comment by anniekao** [comment]
@katelovescode I'm seeing a settings icon for everything but projects, so I may need an upgrade. Although I might just be missing something - I'm new to these Github features :)
