### ISSUE TITLE
There is a secondary scroll bar in the log in and create an account pages 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#217]
## 🤬 What's wrong?
There is a secondary scroll bar in the log in and create an account pages 
Relatedly, the image should be fixed, while the right side should scroll, but they are both scrolling currently. 

## 👉🏼 Steps to Reproduce

- go to `/login` at full desktop size (lg. or larger)

## 🧥Expected behavior
We want the image to be stationary and the right side to scroll.
Only one scroll bar should display, for the right side, rather than two stacked scrollbars

**Comment by csprayregen** [comment]
Hi @katelovescode I know this came up at our meeting last Sunday, but I'm not able to reproduce this error. 
On Chrome, I do see that the image is scrolling rather than fixed, but I don't see the secondary scroll. This feels like a low priority fix to me. 
On Safari, it's all working as expected. 
What are you experiencing?

**Comment by shrmpy** [comment]
I'm interested in this. Just managed to build and start the web frontend, and can see double scrollbars on the Sign Up page with the left column image scrolling along as the right column form. I'm viewing from Chromium on Linux.

**Comment by shrmpy** [comment]
I have the change to client/src/_shared/AuthLayout.js and would like to get feedback. Specifically, the AuthLayout is shared by Signup,Login,Password/update so this change potentially affects the UI of these other pages. 

I don't have a UI test yet. I did make sure that I did not break the existing tests [frontend](https://app.circleci.com/pipelines/github/shrmpy/pieforproviders/70/workflows/357c7d80-f3d1-4450-b0ea-505cf99e0ca7/jobs/135/parallel-runs/0/steps/0-107) [e2e](https://app.circleci.com/pipelines/github/shrmpy/pieforproviders/70/workflows/357c7d80-f3d1-4450-b0ea-505cf99e0ca7/jobs/136/parallel-runs/0/steps/0-121).

Proposed change attached here (client/src/_shared/AuthLayout.js):
[AuthLayout.txt](https://github.com/pieforproviders/pieforproviders/files/5420368/AuthLayout.txt)

**Comment by katelovescode** [comment]
Shrmpy - we won't review changes that don't come in a pull request - I'm going to unassign this so others can take it, but feel free to submit a pull request if you can.

**Comment by shrmpy** [comment]
Understood, I must confess that I don't know how to create the PR. I did not have permission. My steps were clone, checkout-Develop-branch, create-branch, push-origin-branch. I admit that I'm more familiar with making the PR using forks so I assumed I just wasn't allowed.

**Comment by katelovescode** [comment]
@shrmpy You can make a PR from a fork, as well! https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by shrmpy** [comment]
That makes more sense! this pass, I will get it right and make sure to include a (Jest) test.

**Comment by csprayregen** [comment]
Per discussion with @cjhaddad, we are unable to reproduce the two scroll bar issue, but we are seeing that in Chrome the leftside picture is not fixed. It is fixed in safari. We want it to behave in Chrome like it does in Safari. 

![Uploading Screen Shot 2020-11-21 at 2.45.55 PM.png…]()
