### ISSUE TITLE
Grey background on logged in layout does not go all the way to the bottom 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#218]
## 🤬 What's wrong?
The grey background on the logged in layout does not go all the way to the bottom. 

## 🧥Expected behavior
The grey background should go all the way to the bottom. When I scroll down, the white space with the core functionality should end, and I can go back to the grey background.  

## 📸 Screenshots
As noted above, this appears in all sizes and screens, but here are some illustrative screenshots:
![Screen Shot 2020-09-07 at 10 55 40 AM](https://user-images.githubusercontent.com/26717304/92404169-87419800-f0f8-11ea-8bf9-af1074b0b662.png)
![Screen Shot 2020-09-07 at 10 55 32 AM](https://user-images.githubusercontent.com/26717304/92404171-87da2e80-f0f8-11ea-91a2-b2ca648d1005.png)
![Screen Shot 2020-09-07 at 10 55 26 AM](https://user-images.githubusercontent.com/26717304/92404172-87da2e80-f0f8-11ea-8c18-d849803cf2f0.png)
![Screen Shot 2020-09-07 at 10 55 13 AM](https://user-images.githubusercontent.com/26717304/92404173-87da2e80-f0f8-11ea-83e6-11b76337280d.png)
![Screen Shot 2020-09-07 at 10 55 00 AM](https://user-images.githubusercontent.com/26717304/92404174-8872c500-f0f8-11ea-8c03-ff24d42359d8.png)

## 💻 Desktop

Please complete the following information if accessing the app from a computer:

- OS: MacOS Catalina 10.15.4
- Chrome Version 85.0.4183.83 (Official Build) (64-bit)

## 📱Smartphone
n/a

**Comment by csprayregen** [comment]
@katelovescode this is another one that came up in our meeting on Sunday. I am able to reproduce this for the Dashboard page, but not for the Getting Started page. Since we've only done front end dev on the Getting Started page, should we revisit this when we're actually doing dev on the dashboard?

**Comment by csprayregen** [comment]
@cjhaddad @katelovescode I'm still seeing this bug in the sm and xs sizes on some screens (see screenshots). Importantly, I'm not seeing it on our principal dashboard screen where the white goes all the way to the bottom. Would it be easier to make the other pages behave like the dashboard? Either way, would be good to be consistent. 

<img width="384" alt="Screen Shot 2020-11-23 at 9 10 38 PM" src="https://user-images.githubusercontent.com/26717304/100042220-a33c0800-2dd0-11eb-9bae-baec03a53b78.png">
<img width="322" alt="Screen Shot 2020-11-23 at 9 10 29 PM" src="https://user-images.githubusercontent.com/26717304/100042229-a6cf8f00-2dd0-11eb-9526-75b0ce789163.png">
<img width="391" alt="Screen Shot 2020-11-23 at 9 10 02 PM" src="https://user-images.githubusercontent.com/26717304/100042234-a9ca7f80-2dd0-11eb-9e4b-9c58bf8e08b9.png">
<img width="387" alt="Screen Shot 2020-11-23 at 9 09 52 PM" src="https://user-images.githubusercontent.com/26717304/100042241-acc57000-2dd0-11eb-8fd2-aca3ebeac3a7.png">

**Comment by cjhaddad** [comment]
@csprayregen ah yes, let me have a look for these other screens.
