### ISSUE TITLE
Tasks for updated auths from two centers

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#2190]
## 📋 Summary

1. Manually update the kids whose updated auths failed
2. Manually update the kids whose auth info changed without making a new case.

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by csprayregen** [comment]
Leaving this open to address one failed update for DDHS ID 99002101

**Comment by katelovescode** [comment]
Last kid has been fixed
