### ISSUE TITLE
Child has higher rate listed on auth letter than in P4P 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#2204]
## 👉🏼 Steps to Reproduce

DHHS ID = 06033834

Per #1994 we thought these discrepancies were due to lower private pay rates, but this is a discrepancy in the other direction. Could there be an issue with our rate tables, or with the QRIS level being used? 

## 🇺🇸 States this bug is happening in
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

- Operating System: [e.g. iOS]
- Browser [e.g. Chrome, Safari]

**Comment by katelovescode** [comment]
TODO: investigate the QRIS/accredited for this kid's business

**Comment by katelovescode** [comment]
After adding QRIS bump, this is actually a case of the letter having the lower rate.  This is under investigation by Lori, if our DB data is right, then we're going to have to reach out to the state.

**Comment by csprayregen** [comment]
Ok @katelovescode and @MsLoriMcNeill to address both this and #1994 I sent the below email to two of our providers:

"We have a quick question for you: we noticed that your authorization letters show lower daily and hourly rates than those the state has published.

Do you know if this is due to your private pay rates being lower than the state's rates? Or do you have any other explanation for this difference? 

I'm asking because we want to make sure our revenue estimates on your dashboard are as accurate as possible. 

No worries if not, but thanks for taking a look! Happy to clarify further if helpful."

**Comment by csprayregen** [comment]
Current hypothesis: provider has lower private pay rate than state max and therefore rates don't match. Ticketed custom rates separately.
