### ISSUE TITLE
Hours per week should be a decimal instead of an integer

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2209]
## 📋 Summary

`ChildApproval.authorized_weekly_hours` is currently stored as an integer and should be a decimal

AC:
- [ ] Data Type is changed
- [ ] All kids in the onboarding spreadsheet with partial weekly limits are corrected (manually)

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by twinsfan421** [comment]
@katelovescode What do you want for the precision and scale? 

would you be handling this part or how would you want it done?
> All kids in the onboarding spreadsheet with partial weekly limits are corrected (manually)

**Comment by katelovescode** [comment]
@twinsfan421

You should have access to pie-prod on Heroku; what I've done in the past to make manual edits is either:
- use Postico or another DB UI to edit records directly, you can get the credentials for the DB from the Heroku Postgres add-on inside pie-prod
- `heroku console --app pie-prod` will get you to the Rails console and you can make record edits that way if you prefer

These are the ones that need to be updated (I included the approval effective/expires dates to make it easier to search):

DHS ID | Authorized Weekly Hours | Effective on | Expires on
-- | -- | -- | --
85295953 | 35.5 | 2021-04-01 | 2022-03-31
57630692 | 47.5 | 2021-07-01 | 2021-12-31
10595968 | 49.5 | 2021-11-01 | 2022-05-31
10096314 | 49.5 | 2021-11-01 | 2022-05-31

**Comment by katelovescode** [comment]
Reopening until manual fixes are done

**Comment by twinsfan421** [comment]
> Reopening until manual fixes are done

@katelovescode  I just updated those
