### ISSUE TITLE
Tweak fields on sign up page 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#2212]
## 🔬 Experiment Details

If we change our multi-step signup process form from two websites into one, we will increase visits to our and decrease bounce rates from the signup page.

**Out of scope**
- "Create an account" header
- Login button prompt on the bottom of the page

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧶 Acceptance Criteria

**Changes to fields**
- [ ] Make cell number mandatory
- [ ] Add State field (dropdown)
- [ ] Remove "password confirmation" field
- [ ] Add mandatory multi-step question "Help us understand your current experience managing the subsidy" (use[ radio button "radio style" component](https://ant.design/components/radio/#components-radio-demo-radiobutton) from Ant)
- [ ] Add non-mandatory question " What are you hoping to get from using Pie for Providers"? 
- [ ] This works in English and Spanish 

**UI & Copy Changes**
- [ ] Change width of & Sign Up CTA button to green
- [ ] Add text below sign up button: 
Once you create your account, your dashboard will remain blank until we update it with more information.
To learn more about Pie for Providers, go to: www.pieforproviders.com
- [ ] Add H1 that says "Welcome to Pie for Providers!" 

**Nice to haves**
- [ ] Change selected state style of Preferred Language
- [ ] Add radius to radio buttons so they can be consistent w the other input fields

## 🥧 Implementation Details
[Link to Figma](https://www.figma.com/file/GAYeTfOa7umyAhssCHUf8d/P4P-2.0?node-id=50579%3A57543) 

Spanish translations for new language: https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=590755784

**Comment by rebeccakarasiktw** [comment]
FYI @cjhaddad updated ticket w what we discussed today

**Comment by rebeccakarasiktw** [comment]
Hey @cjhaddad I found some small things I've added the comments in the screenshots here. LMK if you want to discuss
<img width="1440" alt="Screen Shot 2022-03-23 at 20 20 46" src="https://user-images.githubusercontent.com/26929739/159824094-961fada9-63a7-41f0-b261-06514ba9a37e.png">
!
<img width="734" alt="Screen Shot 2022-03-23 at 20 22 27" src="https://user-images.githubusercontent.com/26929739/159824103-8cccfdf3-e81c-442c-a62e-c4bba349476f.png">
<img width="724" alt="Screen Shot 2022-03-23 at 20 29 34" src="https://user-images.githubusercontent.com/26929739/159824105-dad0ca02-789b-4b9e-9d79-a3bf7dba61cc.png">

**Comment by katelovescode** [comment]
@rebeccakarasiktw these changes are pushed to staging except the two open questions in slack
