### ISSUE TITLE
Add schedules to CRCC kids who are not full time 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#2214]
## 📋 Summary
Per our privacy and security policy, I will link you to the schedule document separately to protect PII. 

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 💻 Implementation Details

- [ ] Update schedules (KD)
- [ ] Email CRCC to confirm (CS)

**Comment by katelovescode** [comment]
Finished and absences have been fixed.
