### ISSUE TITLE
Update typos on three children's cases 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#2227]
## 📋 Summary
Per Slack in data channel from Jon, and link to spreadsheet, two children need their hours/week updated, and one child needs their name spelling corrected

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 💻 Implementation Details

- [ ] First hours/week updated
- [ ] Second hours/week updated
- [ ] Name spelling corrected

**Comment by katelovescode** [comment]
Fixed manually per the Slack message
