### ISSUE TITLE
sign up & login changes

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2250]
## ✨ What new feature do you want to see?

In order to make it more accessible / easier to toggle between signing up & logging in, change the buttons, and adding some copy. The work in this card is not necessary to execute the "Sign up experiment" but would be a nice-to-have.

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧶 Acceptance Criteria

[Link to Figma](https://www.figma.com/file/GAYeTfOa7umyAhssCHUf8d/P4P-2.0?node-id=50792%3A57497)
- [x] Make the header "Welcome to Pie for Providers
Sign up today to claim more childcare subsidy funding" appear in the login page
- [x] Change CTA button and add "Sign up" button
- [x] In the sign up page, add "Log in button"
- [x] In the signup page change the CTA button to "Sign Up"
- [x] Update the login page to look like the sign-up page -- centered elements, and rounded corners on input fields

**Comment by katelovescode** [comment]
<img width="544" alt="Screen Shot 2022-04-11 at 4 00 27 PM" src="https://user-images.githubusercontent.com/8364647/162831294-c3e3787c-6dfc-40cb-bb11-c906f884db6a.png">
Login button is still blue for me, but in the Figma it's green

**Comment by rebeccakarasiktw** [comment]
Hi @cjhaddad I have a couple of copy comments (see screenshots) and then some spacing things. Would it be possible to make these changes for this ticket? For the spacing part, I think it should be for /signup & /login as well.
<img width="729" alt="2250-1" src="https://user-images.githubusercontent.com/26929739/163274791-644e614a-5e16-46d2-81c4-869999c0b2e7.png">
<img width="728" alt="2250-2" src="https://user-images.githubusercontent.com/26929739/163274801-0b702638-0fba-41ec-a82a-c7ed3089107c.png">
<img width="401" alt="2250-3" src="https://user-images.githubusercontent.com/26929739/163274808-4b3ade7e-3bd7-437d-bdb6-ce1947ce4149.png">

**Comment by rebeccakarasiktw** [comment]
Hi @twinsfan421 @katelovescode @cjhaddad looks good to me! thanks!
