### ISSUE TITLE
Dropdown arrow doesn't turn back to normal configuration when modal opens and menu disappears

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2257]
## 👉🏼 Steps to Reproduce

![dropdown](https://user-images.githubusercontent.com/8364647/154346884-7c9cea3b-1aef-45ee-b48e-4f3f8266efbf.gif)
When I click "payment", the modal opens and the dropdown menu closes, which is what I'd expect, but now the arrow is indicating an open menu and is swapped for the next interaction

## 🇺🇸 States this bug is happening in
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

- Operating System: [e.g. iOS]
- Browser [e.g. Chrome, Safari]

**Comment by rebeccakarasiktw** [comment]
Hi @davidcandeau looks good to me! We can move to done cc @katelovescode
