### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#23]
## ✨ What new feature do you want to see?
The app copy can be read in both English and Spanish

## 🏖 Implementation Details
Most of the copy we're concerned with will be on the front-end side so this ticket should:
- find an internationalization library for react
- talk to @rebeccakarasiktw and @csprayregen for translations or next steps to get translations

Stretch goal:
- either translate all the existing copy in the app, OR
- write a ticket for that translation with a full audit of currently-implemented copy as part of the ticket description

**Comment by katelovescode** [comment]
* [ ]  go to any page, and click the language switcher at the top to change to Spanish. Make sure the language changes for the form labels, etc.
>   This works for sign up and log in. For "thanks for signing up" the language button doesn't do anything. There is no language button on the Getting Started page. @katelovescode do you prefer I write separate tickets for these?

This will get a new ticket, Chelsea's got it on her todo list

> * [ ]  submit a form with failing fields, and make sure the errors are in Spanish
>   This works partially. See two English errors in the login page:

@arku are these two backend errors? (I think so) so handled by #185 

> No errors are produced when I fail to sign the terms of use unless it is the only thing wrong - I couldn't get it to appear here.

This requires a separate ticket, the issue is that the validation will only work the first time, if you un-check after it's passed validation it will not show a validation error.

> Other English error messages here on signup:

@arku pretty sure these are also backend, so handled by #185 

> * [ ]  visit another page (by logging in or navigating via a link) and make sure the language stays the same - this did work. However, the words Setup and Steps are not translated.
>   ![Screen Shot 2020-08-22 at 8 32 16 PM](https://user-images.githubusercontent.com/26717304/90968940-13787c00-e4b8-11ea-9904-70ed37741bd3.png)

@arku can you fix this pre-QA? (setup and steps)

> * [ ]  switch back to English and make sure the language changes and the same behaviors can be reproduced in English - this did not work after log in, since there was either no button or a broken button to switch languages. It did work on the sign up and log in page. However, errors stay in Spanish when I switch back to English.
>   ![Screen Shot 2020-08-22 at 8 55 40 PM](https://user-images.githubusercontent.com/26717304/90969069-c85f6880-e4b9-11ea-9922-0f9fd321a60c.png)

@arku this should probably be addressed before re-QA

**Comment by csprayregen** [comment]
@arku @katelovescode I'm still seeing the same errors noted above - moving this back to In Progress:

When I select Spanish on the log in page, and I log in, my preference remains Spanish. However, errors are:
- [ ] The word "setup" and the word "steps" are not translated
- [ ] The dashboard page is not translated, except for Cierra Sesión on the top right
- [ ] On the Sign Up Page, errors stay in Spanish when I switch back to English. Similarly, Errors stay in English when I switch to Spanish
- [ ]  On the log in page (same as above), errors stay in Spanish when I switch back to English. Similarly, Errors stay in English when I switch to Spanish

![Screen Shot 2020-08-28 at 10 30 49 AM](https://user-images.githubusercontent.com/26717304/91585237-679cb980-e919-11ea-8645-7e8141e1b03e.png)
![Screen Shot 2020-08-28 at 10 29 53 AM](https://user-images.githubusercontent.com/26717304/91585240-68355000-e919-11ea-841c-2e18ca0a9feb.png)
![Screen Shot 2020-08-28 at 10 29 34 AM](https://user-images.githubusercontent.com/26717304/91585242-68cde680-e919-11ea-9487-f95cb750b90a.png)
![Screen Shot 2020-08-28 at 10 28 46 AM](https://user-images.githubusercontent.com/26717304/91585243-68cde680-e919-11ea-82bc-b7db9cf186ae.png)
![Screen Shot 2020-08-28 at 10 27 35 AM](https://user-images.githubusercontent.com/26717304/91585244-69667d00-e919-11ea-8632-079e70a8dec6.png)
![Screen Shot 2020-08-28 at 10 27 21 AM](https://user-images.githubusercontent.com/26717304/91585245-69667d00-e919-11ea-86a8-b5cb9777caf3.png)

**Comment by csprayregen** [comment]
Per conversation with Kate - I will review files on pull request 254 and then click through front end to make sure all these translations work on developed screens. Then I can approve all three internationalization tickets still in QA: this one, #251  and #185

**Comment by arku** [comment]
@csprayregen Can we close this as it is done?

**Comment by katelovescode** [comment]
Yeah, I'll close it - we're doing translation in a more holistic way now.
