### ISSUE TITLE
Users in states other than Nebraska should see a "coming soon in your state" message

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2359]
## 📋 Summary

If a user from a state other than Nebraska signs up, we want them to go through the regular confirmation process, and then when they are redirected to the dashboard, we want to send them to a view with *no* attendance or dashboard view, and instead show them a screen that says, "We'll let you know as soon as we're available in your state" or something similar.  @cjhaddad would love it if you could design and implement this.

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧳 Steps to test
Log in as a NE user and everything should look the same -- you go to Dashboard and the header and mobile menu have the navigation buttons available.

Log in as a non-NE user and you are directed to a Coming Soon view. The header and mobile menu do not have "Dashboard" and "Attendance" buttons available.

Create a non-NE user and you are directed to a Coming Soon view. The header and mobile menu do not have "Dashboard" and "Attendance" buttons available.

**Comment by cjhaddad** [comment]
@katelovescode should the header nav bar have the 'Dashboard' and 'Attendance' buttons eliminated for this? or do you think they should be disabled?

**Comment by katelovescode** [comment]
Personally, my opinion would be that they would be eliminated.

**Comment by cjhaddad** [comment]
@katelovescode agreed. @rebeccakarasiktw  do you have any thoughts?

**Comment by rebeccakarasiktw** [comment]
Hey @cjhaddad took a look, looks great to me! We can move this to done :)
