### ISSUE TITLE
Override breakpoints to be consistent across the UI and align to layout

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#238]
## 📋 Summary

Override the breakpoints and make sure the sizes are aligned.

## 💻 Implementation Details

Override the breakpoints to be: 
s: 360-width
m: 768-width
l: 1024-width
xl: 1280-width

Tailwind uses a different set of breakpoints than Ant Design (which is using Bootstrap 4's breakpoints) - both libraries need to match the breakpoints above, both might require overrides.

Make sure gutters & margins and column sizes align to what's in the layout grids [here](https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=248%3A150) in Figma.

## 🧐 Why tho

We want to have a consistent UI that is responsive, scaleable, and also easy to implement with our libraries.

## ✅ Testing Instructions

Change your screen to our breakpoints as laid out in the ticket, you should see the expected screens from Figma. Our sizes will be:
```
    xs: '360px',
    sm: '768px',
    md: '1024px',
    lg: '1280px'
```
because of limitations with Ant design

**Comment by katelovescode** [comment]
@rebeccakarasiktw we're going to have to do this because of Antd's configuration:

```
    xs: '360px',
    sm: '768px',
    md: '1024px',
    lg: '1280px'
```

They don't have an xl indicator or xxs or anything, this is the best we can get from them 😭

**Comment by csprayregen** [comment]
@katelovescode @rebeccakarasiktw at 360px, this looks slightly different from Figma on the Getting Started page. In Figma, greeting name is on the second line of the header, but in staging it spills onto the third line. The next block of text matches, but then each card seems to have slightly different break points for the body text. I don't necessarily think one is better than the other, but want to check in before approving these. Could these differences have to do with typography and/or the cards themselves?

**Comment by csprayregen** [comment]
At 768px, Getting Started page looks different. Cards are in 2x2 pattern in Figma, vs. 4 across in staging. 

![Screen Shot 2020-09-11 at 12 05 21 PM](https://user-images.githubusercontent.com/26717304/92953192-eb30cd00-f426-11ea-869b-2bf5d6e03c1a.png)

**Comment by csprayregen** [comment]
Breakpoints are not the same as Figma for 1024. Body under the greeting fits all on one line in Figma. Breakpoints within the cards are not the same either. 

![Screen Shot 2020-09-11 at 12 06 21 PM](https://user-images.githubusercontent.com/26717304/92953325-23381000-f427-11ea-8d24-a372268703cc.png)

**Comment by katelovescode** [comment]
These should probably be bug tickets for these specific layouts - also probably good for the hackathon.  Also am I misremembering or did we decide text word-breaks aren't reliable?  I might be wrong. :/

**Comment by csprayregen** [comment]
Per discussion in Slack, we are going to circle back to these once Rebecca and Candace are back / onboarded.

**Comment by csprayregen** [comment]
Per discussion tonight with Rebecca, we cannot visually QA this - this is simply added to the code. Then we need to visually QA specific screens.
