### ISSUE TITLE
Add effective_on and expires_on to child_approval

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2388]
## 📋 Summary

AC:
- ~migration to add effective_on and expires_on to child approval, not required~
- ~migration to copy approval effective_on and expires_on dates to the child_approvals associated with that approval~
- migration to make child_approval dates required
- migration to make approval dates optional

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by twinsfan421** [comment]
Here is what I have done so far off of @minaslater branch. https://github.com/pieforproviders/pieforproviders/compare/PIE-2288/add_effective_on_expires_on_child_approvals_additional?expand=1
There are tests that need refactoring, including all those using with the necc_child facotory.

**Comment by rebeccakarasiktw** [comment]
Per discussion w @katelovescode we are going to de-prioritize this and Kate will delete the branches.
