### ISSUE TITLE
Manually update kids that had the wrong approval dates

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2391]
## 📋 Summary

Blocked by #2388 and #2390

Any kids that we put in with the wrong approval dates because the system was incorrect need to be corrected.  @csprayregen I don't know if we tracked this, maybe it makes sense to ask some volunteers to do some data comparison and make a list of what needs to be fixed.  Any other ideas?

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by csprayregen** [comment]
@katelovescode this is documented in the two centers' tabs in the onboarding spreadsheet!
