### ISSUE TITLE
Pick a CSS framework/library

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#24]
## 📋 Summary
We need to decide how we're going to implement CSS, and what framework to use.  I'm coming off of the Tailwind train for this one, I think, it seems to be no better than managing css-in-js directly.

**Comment by brobertsaz** [comment]
Tailwind is great for prototyping but then it gets to be a PITA.  I still think that Bootstrap is great to use and easy enough to customize

**Comment by katelovescode** [comment]
Personally I think Bootstrap is too heavy for this project, but I'm open to other suggestions.

**Comment by rebeccakarasiktw** [comment]
Adding blocked label until we get feedback from implementing #65 and whether Semantic UI works for that. Then @katelovescode and I  can make a decision and close this card.

**Comment by csprayregen** [comment]
We are moving forward with Tailwind. See card #102 and #54 will include a deeper dive into semantic UI
