### ISSUE TITLE
Replace greeting name initial in Header with full name initial

### ISSUE THREAD

**Issue by nicorinn** [pieforproviders/pieforproviders#2420]
## 📋 Summary
In `Header.js`, the avatar currently displays the first initial of the user's `greeting_name`. Since this field is going away, it should display the first initial of the `full_name` field instead.

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 💻 Implementation Details

**Comment by katelovescode** [comment]
@nicorinn omg I completely misspoke.  You'll want to do `first_name` instead, we're phasing out `full_name` soon.  Sorry for the confusion. 🤦🏼‍♀️

**Comment by rebeccakarasiktw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Post-NECC Contact Marketing (one-pager)](https://trello.com/c/3b84KHfX/2-post-necc-contact-marketing-one-pager)

**Comment by rebeccakarasiktw** [comment]
ignore the Trello integration update -- it was just a test!
