### ISSUE TITLE
Update spreadsheet to allow for license exempt providers

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2436]
## ✨ What new feature do you want to see?

Slack from @JonErvin 

> There's a weird split on the rates (the 4 urban counties are split, so Douglas and Sarpy are higher than Lancaster and Dakota) which might take.... an hour to fix.

**Comment by rebeccakarasiktw** [comment]
Closing per @JonErvin  comment: 
"This was a note to fix the rate table in our spreadsheet for license exempt providers.  This was relevant IF we were still using the spreadsheet to check the formulas in our app (we rarely do) AND if we had license exempt providers (which we don't).  The rates table in the app includes them I believe.  All this to say, its not done but I don't really think it should be done"
