### ISSUE TITLE
I can switch languages from every screen 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#248]
## ✨ What new feature do you want to see?
On any screen in the app, there is a button I can click to change the language I see. 

## 🧶 Acceptance Criteria
- [x] In sizes 1024 px width or larger, I can switch languages via the button at the top right, next to my account icon. When I'm in English, this option reads "Español." When I'm in Spanish, this option reads "English." 
- [x] In sizes smaller than 1024 px, I see a hamburger menu. When I click it, I have two options - log-out, or switch your language. When I'm in English, this option reads "Español." When I'm in Spanish, this option reads "English." 

## 🖍️ Implementation Details
@katelovescode is there any additional context you want to add on the tech we're using here?

The screen sizes we're building for are below. Sizes xs and sm have the hamburger menus. Sizes md and lg have the language visible in the top right. 
-     xs: '360px',
-     sm: '768px',
-     md: '1024px',
-     lg: '1280px'

## 🥧 Additional context
Figma mockup (sizes 1024 and 1280) here **look at current state only:**: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=1165%3A0
Mobile mockup (for sizes 360 and 768) **look at current state only:**: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=1165%3A0

**Comment by csprayregen** [comment]
@katelovescode @cjhaddad the hamburger menu appears in our size xs, but not in size sm. Moving back to "in progress."

**Comment by cjhaddad** [comment]
@csprayregen the breakpoints in ant-design work as min-widths it seems. therefore, screens more than or equal to 768 have regular nav links and then 767 or less have hamburger. would you like it to be 768 or less? if yes, I can do some finagling. let me know! :)

**Comment by csprayregen** [comment]
@cjhaddad if you can get it to be 768 or less in less than an hour that would be great! If not, we can live with it as is.

**Comment by cjhaddad** [comment]
@csprayregen yes! I will look into it. may need to bypass using the built in breakpoints via ant-design, but it should be possible. @katelovescode any objections to going that route if needed?
