### ISSUE TITLE
Run local profiling on dashboard

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2490]
Results of profiling locally:
- [pdf of profiling output](https://drive.google.com/file/d/1PaO-jc7ahdX_o_MmkLpLcRONFyK89kTp/view?usp=sharing)
- [metrics analysis](https://docs.google.com/spreadsheets/d/1AbIYs2JyPpR87EG8AoHvz3c0rIh1-SGEh25k4XFBNJY/edit?usp=sharing)

**Comment by katelovescode** [comment]
Local profiling of the dashboard:
/profile - 1.1 sec
/case_list_for_dashboard - 61.5 sec

Some suggested actions based on the profiling results:
https://github.com/pieforproviders/pieforproviders/issues/2494
https://github.com/pieforproviders/pieforproviders/issues/2495
https://github.com/pieforproviders/pieforproviders/issues/2496
https://github.com/pieforproviders/pieforproviders/issues/2497
https://github.com/pieforproviders/pieforproviders/issues/2498
https://github.com/pieforproviders/pieforproviders/issues/2499
https://github.com/pieforproviders/pieforproviders/issues/2500
https://github.com/pieforproviders/pieforproviders/issues/2501
https://github.com/pieforproviders/pieforproviders/issues/2502
https://github.com/pieforproviders/pieforproviders/issues/2503
https://github.com/pieforproviders/pieforproviders/issues/2504
https://github.com/pieforproviders/pieforproviders/issues/2505
https://github.com/pieforproviders/pieforproviders/issues/2506
https://github.com/pieforproviders/pieforproviders/issues/2507
https://github.com/pieforproviders/pieforproviders/issues/2508
https://github.com/pieforproviders/pieforproviders/issues/2509

**Comment by rebeccakarasiktw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Top 6 offenders for Performance Improvements](https://trello.com/c/9ubTm6cU/15-top-6-offenders-for-performance-improvements)
