### ISSUE TITLE
Performance - `active_approval` - 2 trace frames - 115 calls - 15.33s - 95.65% of calls are slow

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2500]
In single profile example, these 115 calls were responsible for 15.33s of the request, and 95.65% of the calls of this method were above the double-digit mark of milliseconds.

Executing action: case_list_for_dashboard — 163.40 ms
```
app/models/child.rb:81:in `active_approval'
app/models/child.rb:85:in `active_child_approval'
app/blueprints/child_blueprint.rb:46:in `block (2 levels) in '
app/controllers/api/v1/users_controller.rb:51:in `nebraska_dashboard'
app/controllers/api/v1/users_controller.rb:26:in `case_list_for_dashboard'
app/controllers/application_controller.rb:51:in `collect_metrics'

SELECT "approvals".* FROM "approvals" INNER JOIN "child_approvals" ON "approvals"."id" = "child_approvals"."approval_id" WHERE "child_approvals"."child_id" = $1 AND "approvals"."effective_on" <= $2 AND ("approvals"."expires_on" IS NULL OR "approvals"."expires_on" >= $3) ORDER BY "approvals"."updated_at" DESC LIMIT $4;
```

```
app/models/child.rb:85:in `active_child_approval'
app/blueprints/child_blueprint.rb:46:in `block (2 levels) in '
app/controllers/api/v1/users_controller.rb:51:in `nebraska_dashboard'
app/controllers/api/v1/users_controller.rb:26:in `case_list_for_dashboard'
app/controllers/application_controller.rb:51:in `collect_metrics'

SELECT "child_approvals".* FROM "child_approvals" WHERE "child_approvals"."approval_id" = $1 AND "child_approvals"."child_id" = $2 LIMIT $3;
```

**Comment by katelovescode** [comment]
Draft next steps:
- benchmark this method
- add automated performance testing for this method (?)
- work on making less calls to this method
- work on making this method call faster
- re-benchmark

**Comment by katelovescode** [comment]
<img width="1088" alt="Screen Shot 2022-04-25 at 1 00 48 PM" src="https://user-images.githubusercontent.com/8364647/165147220-875d68b8-0007-4f55-a440-8966f50c5e34.png">
I'm not sure this is helpful; latency is saying 6m or 4m? The request is taking ~1.2 mins on local so this is weird.

**Comment by katelovescode** [comment]
<img width="1091" alt="Screen Shot 2022-04-25 at 3 39 50 PM" src="https://user-images.githubusercontent.com/8364647/165171108-d84e1d2a-9af1-4bd4-9a15-ae0454b9508e.png">

**Comment by rebeccakarasiktw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Top 6 offenders for Performance Improvements](https://trello.com/c/9ubTm6cU/15-top-6-offenders-for-performance-improvements)
