### ISSUE TITLE
[Bug] Child attendance data not populating from Wonderschool to P4P

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2542]
## 👉🏼 Steps to Reproduce

1. Go to 'app.pieforproviders.com'
2. Scroll down to 'Blessed Are They' children (JM)
3. See there is no attendance for April
4. See, via Periscope, that there is attendance for the child in Periscope

## 🇺🇸 States this bug is happening in
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 🧥Expected behavior

The info from Wonderschool should be showing up in P4P.

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

- Operating System: [e.g. iOS]
- Browser [e.g. Chrome, Safari]

**Comment by katelovescode** [comment]
Investigating via communications with Wonderschool - this child has two enrollment records, and we've been using one as a unique identifier, which means we're only getting attendances associated with the first enrollment.  Working through how to improve this now.

**Comment by rebeccakarasiktw** [comment]
Closing per message from Gray - this is not a bug but a feature. We will figure out other ways to handle this type of case.
