### ISSUE TITLE
Move attendance creation process to Command object in services

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2554]

**Comment by rebeccakarasiktw** [comment]
Regression testing looked good, notes are here: https://docs.google.com/document/d/1pxwxPmCmsR1Xsjgp7E-hhy-Va_zVgTOt5mfkWxSnADc/edit

Small issue found but not a show stopper for this ticket. Moving to done

cc @katelovescode @cjhaddad
