### ISSUE TITLE
Update for Tailwind changes

### ISSUE THREAD

**Issue by noragharris** [pieforproviders/pieforproviders#258]
## 📋 Summary
See upcoming [Tailwind changes around `removeDeprecatedGapUtilities`](https://tailwindcss.com/docs/upcoming-changes)

## 💻 Implementation Details
See upcoming [Tailwind changes around `removeDeprecatedGapUtilities`](https://tailwindcss.com/docs/upcoming-changes)

## 🧐 Why tho
Stay current!

**Comment by arku** [comment]
Fixed in #260
