### ISSUE TITLE
[for July 1st 2022] Update Nebraska rates in the app to reflect new rates

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2599]
## 📋 Summary

Based on new information in the update Title 392 Guidance doc, linked here: https://dhhs.ne.gov/Guidance%20Docs/Title%20392%20Guidance%20Document.pdf, update the rates in our app
Link to source of that PDF: https://dhhs.ne.gov/Pages/Child-Care-Regulations.aspx
**UPDATED PDF ATTACHED**
[7-1-2022 Subsidy Rates (1).pdf](https://github.com/pieforproviders/pieforproviders/files/9097436/7-1-2022.Subsidy.Rates.1.pdf)

## 🇺🇸 States this change applies to
- [ ] ALL
- [X] Nebraska
- [ ] Illinois

## 💻 Implementation Details

How to test: Query the database and make sure new rates are being calculated instead of old rates.
_Question to discuss_ Can we ensure the rates are effective as of July 1st?

Old rates:
![Screen Shot 2022-05-13 at 10 56 55 AM](https://user-images.githubusercontent.com/8364647/168321896-55d0686a-21fd-4bac-bfe5-d8a8340be44e.png)

New rates (note the table is laid out differently)
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/26929739/178612576-580a9144-d7b1-43e3-b31b-84b64986651b.png">

**Comment by rebeccakarasiktw** [comment]
@katelovescode let's discuss what if any other work needs to be done before we can make the updates in the app.

**Comment by rebeccakarasiktw** [comment]
This card is not yet ready to be worked on as the rates are not yet updated on the website.

**Comment by katelovescode** [comment]
@JonErvin and @OliverCai0 - if Jon says these rates look right, and the changes are made from my last review, we're good to go.  The last time we had to do rate-checks w/ Jon, I ran the rate rake task locally, and then exported the table directly from Postico as a CSV, then sent it to Jon to check.
