### ISSUE TITLE
Skeleton component for Notifications

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2603]
## ✨ What new feature do you want to see?

Create card component for notifications that will show notifications when:
* There is an authorization that is expiring in 30 days or less.

_Preliminary design_

<img width="967" alt="image" src="https://user-images.githubusercontent.com/26929739/168308556-9283abf5-a604-457f-99b0-5911b3324edd.png">

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by katelovescode** [comment]
@rebeccakarasiktw this is on staging when you want to review; it's hidden behind a feature flag that is currently ON in staging.

**Comment by rebeccakarasiktw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [In-App Alerts for Authorization Letters](https://trello.com/c/RxFZAlI3/9-in-app-alerts-for-authorization-letters)
