### ISSUE TITLE
What happens when we upload a case with the "max hours per week" field blank?

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#2639]

**Comment by katelovescode** [comment]
@csprayregen confirmed - max hours per week (in the data model called `authorized_weekly_hours`) is not a required field - uploading it blank is fine for the database.

For the front-end, we use it in the dashboard in one field: Hours Attended.  If it doesn't exist in the child's approval, it will read:
`0.0 of nil` or `23.4 of nil`.
