### ISSUE TITLE
Absences not being created

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#2673]
Absences are not being created when they should be for at least some children. 

Example: DHS IDs 55028881 and 22711905 were added to P4P prior to 6/3. This means I did run the fix absences task for them. We then added attendance for those kids on 6/6. On 5/18, both children have "no info" listed, where they should have an absence listed, since they are full time children. 

SPIKE WORK:
Generate a document w/ expected logic/behavior/data
Write tests for this logic/behavior/data if they're missing
Deep dive on one kid (3x) to figure out what's wrong with their data
Try to extrapolate a theory and a rake task to investigate
**Things to check specifically**
- daily absence creator
- wonderschool attendance import
- csv attendance import
- UI attendance creation

To do:

- [ ] Create absences for these days for these children
- [ ] Investigate whether other attendances/children were impacted by this bug, including kids added when we were still running the Fix Attendances task

**Comment by rebeccakarasiktw** [comment]
I was able to manually change those two instances to absences without changing other data.

Want to point out that I found this similar issue in the last regression testing of 5/19. OK WE DONT THINK THIS IS RELATED.

Also, have found another issue of check-in & check-out times not being exactly aligned , sometimes P4P shows 1 minute earlier.

**Comment by rebeccakarasiktw** [comment]
As we agreed with @katelovescode @csprayregen we are not going to fix this issue as it would involve fixing "fix absences" which we are not going to do. So I am closing this ticket.
