### ISSUE TITLE
1 minute discrepancies in attendance found

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2682]
## 👉🏼 Steps to Reproduce

1. Go to this spreadsheet, which shows the attendance that a center sent us: https://docs.google.com/spreadsheets/d/1VTmL82qpkNv1oDQf28kIcLSRNSVdnssLBD4iZyshikE/edit#gid=1912999816
2. Click on the second tab
3. Go to View Attendance for UNL center
4. Scroll down to Compare the check in & check out times 
5. See that there are various 1-minute discrepancies.

## 🇺🇸 States this bug is happening in
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

- Operating System: [e.g. iOS]
- Browser [e.g. Chrome, Safari]

**Comment by rebeccakarasiktw** [comment]
@katelovescode more details in this Slack thread: https://pie-for-providers.slack.com/archives/CRRQLLXFZ/p1654702206240189

**Comment by OliverCai0** [comment]
Bug occurs during the upload process to Airtable.

**Comment by rebeccakarasiktw** [comment]
As we discussed w @csprayregen @katelovescode @OliverCai0 the root cause is Airtable upload step in the process. We are going to stop using Airtable for now.
