### ISSUE TITLE
Add new absence/attendance types and update logic

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2693]
## 📋 Summary

- Add `absence_on_scheduled_day` to allowed absence types
- Add `absence_on_unscheduled_day` to allowed absence types
- Update all logic (calculations for the dashboard) to include both of these new types as if they were regular `absence`s
- Change all existing absences to `absence_on_scheduled_day` given prior restrictions to be removed in #2692 
- Change incoming ServiceDay#creates and #updates from AttendanceDay to take `absence` from the `absence_type` value and determine if it is scheduled or unscheduled, and assign the appropriate type (this will eventually be moved to a command in #2570 and #2571 )
- Document the API: incoming values can be `absence` or `covid_absence` or `nil` for `ServiceDay.absence_type` - the backend will decide if it's scheduled or not

Doc for context: https://github.com/pieforproviders/pieforproviders/blob/main/docs/attendances_and_absences.md

**Comment by rebeccakarasiktw** [comment]
@OliverCai0 and @rebeccakarasiktw to kick off this card together if @katelovescode is out
