### ISSUE TITLE
Update Heroku data clip to apply to Prod

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2711]
## 📋 Summary

Make this data clip (currently in Staging): https://data.heroku.com/dataclips/zmfmhkrzqqzdueqysbefxntpvepc

Usable for Prod environment

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by OliverCai0** [comment]
Created a data clip named Attendances [Production] with same query [here](https://data.heroku.com/dataclips/lefuygfflftqexugofnfzrsizfom)
