### ISSUE TITLE
Heroku dataclip to match approval id to provider & child name

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2725]
## 📋 Summary

Create a dataclip that can match `child id` to `approval id` to `user full name` to `children name` (I believe this is first & last name)

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by OliverCai0** [comment]
Clip can be found [here ](https://data.heroku.com/dataclips/andsmnvjnufzvtvlrxewsejmqwcw). A bit slow initially.
