### ISSUE TITLE
Add family fee for specific child

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#2778]
The child with DHHS ID 91918521 is listed on the dashboard as having a $0 family fee. The family fee should be $204. The CSV used for inputs to S3 with full details for this child is available at the link below. Please note that the currently active case is row 3 of this spreadsheet. Row 2 is the same child's expired case. We should use the active family fee amount of $204. 

https://docs.google.com/spreadsheets/d/1ziu2v2RqTsHvZ2Coav7iixjLpAHeiN7bb0jH-UilnF4/edit#gid=0

If you discover anything in updating this card that needs to be fixed, please add it to this ticket: #2779

**Comment by katelovescode** [comment]
@csprayregen this is fixed on prod

**Comment by csprayregen** [comment]
Looks good!
