### ISSUE TITLE
Fix family fee for specific kids

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#2803]
Family fee came up as $0 for the following kids who have non-zero family fees (all listed by DHHS ID):

- [x] 16666154
- [x] 48725341 
- [x] 36889588
- [x] 32718594 
- [ ] 48177553 --> appears correctly on prod, but open discussion re: malformed dates in third auth to be resolved 

Please note that some of these children have different family fees listed during different periods within their authorization.

Spreadsheet with details: https://docs.google.com/spreadsheets/d/1QVeilPUT2KYrJEHQQQdISMpCn8vJqlZyHKysxJlxWQ4/edit#gid=1500400876

**Comment by katelovescode** [comment]
Finished
