### ISSUE TITLE
Add business name to service days endpoint

### ISSUE THREAD

**Issue by cjhaddad** [pieforproviders/pieforproviders#2812]
## 📋 Summary
For the attendance view enhancements we are adding a child's associated business under their name. Therefore, we need to add the business name to the service day object returned from the /service_days endpoint.

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by twinsfan421** [comment]
@katelovescode  Do you want the whole business object or just the name from the business.

**Comment by cjhaddad** [comment]
@twinsfan421 just the name from the business is great!
