### ISSUE TITLE
Investigate React-Query

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#284]
## 📋 Summary
https://react-query.tanstack.com/docs/videos

Investigate for cacheing user data (as well as invalidating cache)

## 🧐 Why tho

cc @cjhaddad we'll probably want to look at this and have a chat about routing back-end and front-end (this will also tie in with maybe removing slugs from the backend)

**Comment by cjhaddad** [comment]
going to hold off on implementing this. looks like it can be useful, but in the interest of keeping it moving and not immediate need, putting a pin in this.
