### ISSUE TITLE
Display child name in IL dashboard

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2852]
## ✨ What new feature do you want to see?

Our Illinois dashboard currently does not display Child Name. This is because when we updated our data to be first_name and last_name in the child table we never made the update to the IL Dashboard. 

## 🇺🇸 States this change applies to
- [ ] ALL
- [ ] Nebraska
- [X] Illinois

## 🧶 Acceptance Criteria

- [ ] If I am in the IL dashboard, I am able to see the First Name & Last Name in the "Child Name" column.

**Comment by rebeccakarasiktw** [comment]
@OliverCai0 can you update the font size to 16px (1rem)? With that change we can then move this to done. Thanks!

**Comment by OliverCai0** [comment]
The names should be 16px on staging now!
