### ISSUE TITLE
Remove "Coming Soon" message for IL 

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2853]
## ✨ What new feature do you want to see?

Since we are planning to launch soon in Illinois, we want to remove the "Coming Soon" message that you currently see.

## 🇺🇸 States this change applies to
- [ ] ALL
- [ ] Nebraska
- [X] Illinois

## 🧶 Acceptance Criteria

- [ ] If I sign up and say I am from IL, then I see a blank dashboard once I have logged into my account. 
- [ ] If I log in and I am an IL user, then I see a dashboard when I log into my account.
- [ ] If I sign up from any state that is not IL or NE, then I see the "Coming soon" message once I have created my account.
- [ ] If I log in with any account that is not IL or NE, then I see the "Coming soon" message when I log in.

**Comment by OliverCai0** [comment]
Added a non-IL and non-NE user example (newyork@test.com, testpass1234!) to staging.

**Comment by rebeccakarasiktw** [comment]
LGTM moving this to done!
