### ISSUE TITLE
[Spike] Various issues w attendance rate

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2855]
## 📋 Summary

Look into the issues/bugs below happening with attendance rate in IL app.

1. In the month of July 2022, there are attendance rate calculations & tags, but not in other months: **resolved**
![Screen Shot 2022-08-04 at 10 11 12](https://user-images.githubusercontent.com/26929739/182893762-9ca1531b-8f68-4098-b681-082962c37b7a.png)
![Screen Shot 2022-07-21 at 09 43 18](https://user-images.githubusercontent.com/26929739/182893804-49254e1b-2671-4008-80df-3c1ea8bc56ea.png)

2. When the attendance rate is 0%, the attendance rate tag says "Not enough info" for previous months when the attendance rate should say "0% - At risk" (I believe this is because it is taking into account the day of the month that the user is visiting the site, regardless of which month it is in the dashboard. **resolved**
![Screen Shot 2022-08-04 at 11 01 06](https://user-images.githubusercontent.com/26929739/182894059-69e33571-f6a9-41dc-b0ac-6c05b2c9fb31.png)

4. Attendance rate is not being calculated correctly in general -- see Tab 2 of the spreadsheet [here] **resolved but need to double check (https://docs.google.com/spreadsheets/d/1xbV9UYAZbX9IYfUn6Jz_0fdpH7lvrdW2PpYKMMh_Gx8/edit#gid=476305199).** 

5. Needs more analysis -- this "Sure bet" being calculated at 180% --- how is that happening?
Goal of this spike is to figure out the cause of these issues and determine if we should remove attendance rate altogether or set up a different way to calculate it.
![Screen Shot 2022-08-04 at 10 11 08](https://user-images.githubusercontent.com/26929739/182894360-6dc0d088-06bb-4c00-8f3c-62eccf6ec696.png)

## 🇺🇸 States this change applies to
- [X] ALL
- [ ] Nebraska
- [ ] Illinois

**Comment by OliverCai0** [comment]
2. I believe this issue is being caused by the mock data being supplied for each child. Creating a Illinois approval amount for the months in Aug 2021-2022 causes the "at risk" tag to show up.

**Comment by rebeccakarasiktw** [comment]
Moving to Done as I can confirm that all issues identified in this card have now been resolved.
