### ISSUE TITLE
Duplicate records created due to child name spellings

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#2871]
For the following children, a duplicate record was accidentally created due to new authorizations being uploaded with different name spellings:

- 48177553
- 13259408
- 94374744
- 07966921

I would ideally like to use the updated spelling of the children's names, but most importantly we don't want the provider to see duplicate records (as they now appear on the front end)

Update names to match spelling used in new record, then delete new record. Chelsea then needs to re-upload new auths for these four children.

**Comment by OliverCai0** [comment]
Child records have been updated.
