### ISSUE TITLE
Update IL rates table

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2876]
## 📋 Summary

Update the rates amounts in the Illinois_rates table.  See here for a table of all of the rates to upload into the app (Rates Tab): [IL Refresh - New Market Template](https://docs.google.com/spreadsheets/d/18tlpyDd5cGon8Rw7Q1nHHnugfRJKRT2yMQzrr_3GqaY/edit#gid=0).

This is pulled from this DHS Site: [IDHS 06.05.01](https://www.dhs.state.il.us/page.aspx?item=144991) as of 7/1/2022

To test - export to csv and create pivot table to match tables on DHS site and visually compare.

Per conversation w @JonErvin & @OliverCai0 we are also making the following updates to the IL rates table:
GET RID OF:
Bronze_percentage: 0%
Silver_percentage: 10%
Gold_percentage: 15%
Attendance_threshold: 70%

CHANGE IN TABLE
Change County to Region
Age_bucket -- change name to "max age" and change values that are in there currently 
[@Jon Ervin]
 to update spreadsheet and then Oliver can make the updates
Get rid of part day rate and change full day rate to rate type so it is consistent with NE (
[@Oliver Cai]
 let us know if this change is a big one)

OUT OF SCOPE:
Add another card to update QRIS math for IL (
[@Jon Ervin] to create that card)

## 🇺🇸 States this change applies to
- [ ] ALL
- [ ] Nebraska
- [X] Illinois

**Comment by JonErvin** [comment]
@rebeccakarasiktw Added the info we discussed here and removed the Blocked label.

**Comment by JonErvin** [comment]
Thanks for the adds @rebeccakarasiktw.  Updated the spreadsheet to fix the max age issue.  Will create the update IL rates card

**Comment by JonErvin** [comment]
Here's the spreadsheet documenting the rate checks.  All good, except for one old rate in there from prior testing to be deleted.

https://docs.google.com/spreadsheets/d/1jbbsh7qAdUXBbmfrslN25W0gVAIGcIYt/edit?usp=sharing&ouid=113865307885577501841&rtpof=true&sd=true

**Comment by JonErvin** [comment]
In convo between Oliver and Jon.  Need to be able to join rates table with a Region (e.g., Group 1A) to a business with a County (e.g., Cook).  In Nebraska, we have a class called RegionFinder that adds to the rates table.  We are building similar functionality in Illinois to fully implement this ticket.

**Comment by OliverCai0** [comment]
The rake task to import the latest illinois rates, migration to update to illinois rates table, and region finder are all done. Attached is the csv file with all the rate records. The rake can be executed with 

- heroku run bundle exec rails illinois:illinois_rates0916 

[illinois_rates.csv](https://github.com/pieforproviders/pieforproviders/files/9588485/illinois_rates.csv)

**Comment by rebeccakarasiktw** [comment]
@JonErvin the rates are now in staging. can you review the CSV please? thank you!

**Comment by JonErvin** [comment]
@fabianraf All good!  Ready to push to production.

Here's the spreadsheet I used to confirm, for posterity: https://docs.google.com/spreadsheets/d/1gG9hjfYb4DFsr0OVKslZ63JKxc9aezjP/edit?usp=sharing&ouid=113865307885577501841&rtpof=true&sd=true
