### ISSUE TITLE
Set up "Total Time in Care" calculator for IL

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#2918]
## 📋 Summary

_No longer blocked by pending policy research_

Today, our [Total Time in Care ](https://github.com/pieforproviders/pieforproviders/blob/aba7f5c20743c62b0c5691204dca31534c2f80af/app/services/total_time_in_care_calculator.rb ) calculator only calculates for Nebraska children. 
We want to either update this calculator to include Illinois children, or create a new calculator. 
This will probably take some investigation into the best path forward before implementation.

Jon's updates from spike.  Currently, total_time_in_care serves three purposes:

**1. Aggregate by date** (e.g., if a child attends 2 hrs in morning and comes back for 3 hrs at night, combine into one total of 5 hrs)
**2. Handle missing checkouts.**  Current behavior: apply scheduled hours (default = 8) unless already attended more than schedule.  If no schedule, assume 8 hours.
**3. Handle absences.**  Current behavior: similar to above (first try schedule, then if no valid schedule assume 8 hrs)

We want to create similar behavior in IL with the following changes:

**1. Different logic for missing checkouts.**  "Scheduled duration" doesn't exist as a concept IL.  Therefore, we'll want to return zero and create an additional flag that check-out is missing (to use when determining FT and PT days)
**2. No absence logic.**  Absences (as we used them in NE) do not exist in IL.

Page 1 here has more details on how this fits in the end to end process: [Path to get to eligible and attended FT and PT days](https://docs.google.com/document/d/1gBuVSdWF28-HqEOrll5hCQgiW2TRaDt8YbkZUc6RNvI/edit#heading=h.szwjygz4c2lk) (Steps 1-4)

Acceptance Criteria
 - When I add multiple attendances for the same child on the same day, the total_time_in_care in service_day sums their duration
 - When an attendance record is missing a check_out time, the total_time_in_care is zero AND there is a flag that check-out is missing
 - This calculator runs for children in IL (and not for children in Nebraska)

## 🇺🇸 States this change applies to
- [ ] ALL
- [ ] Nebraska
- [X] Illinois

## 💻 Implementation Details

For different logic for missing checkouts, I'd suggest starting with the NE version and:
    - Confirm that time_in_care (on attendance model) returns 0 if missing checkout
    - Maintain total_time_in_care as 0 when checkout is missing
    - Create an additional "missing_checkout" field in service_day model where TRUE means >=1 attendances for a given child and date have a check-in time but no check-out time (otherwise FALSE)

**Comment by JonErvin** [comment]
Tagging PR for easy reference: https://github.com/pieforproviders/pieforproviders/pull/2953
