### ISSUE TITLE
Use URLSearchParams instead of splitting strings

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#317]
I like this (what's in PasswordReset) a lot better than what I implemented in `client/src/Confirmation/Confirmation.js:13` and `client/src/Signup/Signup.js:65`

We should refactor those two other locations to use `new URLSearchParams(location.search)`

_Originally posted by @katelovescode in https://github.com/pieforproviders/pieforproviders/pull/287#discussion_r484607520_

**Comment by naresh3599** [comment]
Hii @katelovescode, would like to work on this?
Please assign me!

**Comment by katelovescode** [comment]
> Hii @katelovescode, would like to work on this?
> Please assign me!

Hi Naresh!  I'll assign a second ticket after you've finished the first one! :) Want to make sure we have issues to go around.

**Comment by rebeldroid12** [comment]
https://github.com/pieforproviders/pieforproviders/pull/543
