### ISSUE TITLE
Audit Add a Site screen (multi business) for discrepancies with Ant functionality 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#327]
## 📋 Summary
We are using the Ant design library/framework, but are finding that it is very opinionated in a way that sometimes conflicts with design intentions. Review the Add a Site Screen for multi business users, and let us know if any of the planned functionality would be difficult or impossible in Ant.

## 💻 Implementation Details
1. Look at the Add a Site screens in Figma for multi business users:
Mock ups: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=2409%3A7318

2. Look at the Add a Site cards to understand associated user stories: #53 

3. Review each component in Ant, specifically the API, for attributes that might need to be set to implement the design as intended: https://ant.design/components/overview/

4. If you anticipate any of the user stories associated with these components will create engineering challenges, flag that in a comment below and describe the challenge. Bonus points if you can propose an alternative path using Ant components that still accomplishes the goals of the user stories.

## Note:

For future behavior, we'd like a dropdown for adding a new case, and then either assigning that case to an existing business or creating a new one (from the dropdown) - what does a select or create new dropdown look like in Ant?

## 🧐 Why tho
We want to anticipate blockers in advance and address them so engineering is not blocked.

**Comment by cjhaddad** [comment]
For the functionality requested above I do not foresee an issue using ant components. I implemented a component that functionally replicates the mock-ups. I also played around with the dropdown component, per the Note request and also found it to do what I perceive we need it to do. Branch can be found here: https://github.com/pieforproviders/pieforproviders/tree/327/add-site-ant-audit

**Comment by csprayregen** [comment]
When we get to this functionality, we can revisit this ticket, but the research is done.
