### ISSUE TITLE
DB Implementation: : ChildSite Controller, API, and swagger 

### ISSUE THREAD

**Issue by weedySeaDragon** [pieforproviders/pieforproviders#329]
## 📋 Summary

Add a Controller, request spec, api .json files, and swagger_helper.rb info for ChildSite

## 🧐 Why tho

need to have controller actions and API documentation

**Comment by weedySeaDragon** [comment]
Just to verify, @katelovescode :  ChildSite _does_ need a Controller, routes, and API info, yes?
 I also noticed that this model doesn't have timestamps or a slug.  I know we'll be removing the slugs, but for now it's needed, right?

**Comment by katelovescode** [comment]
Timestamps and a slug are a yes.  Good question about ChildSite's controllers, etc.  I think I haven't been paying close enough attention to these tickets/tables; our join tables don't need controller/routes/API.  We're more likely to be accessing them through their association (in this case, through the Child's record).  We should pull those out for things like ChildCaseCyclePayments, etc.  So I'd say this one needs a migration and a model only, and then we can pull out the other controllers/API/routes in another PR.

**Comment by csprayregen** [comment]
No longer doing child sites
