### ISSUE TITLE
"Email taken" warning on sign up page doesn't disappear

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#333]
## 🤬 What's wrong?
When I'm on the sign up page, and I input an email address that has already been taken, the warning stays there, even after I fix this problem. The user would not be sure she had fixed the error in the current state. 

## 👉🏼 Steps to Reproduce

<!-- Steps to reproduce the behavior:
1. Go to https://pie-staging.herokuapp.com/signup
2. Go through the steps to create an account, but use an email address that has already been taken. 
3. You'll see the warning message appropriately appear stating "email address is already taken."
4. Update the email to a new address.
5. The warning does not go away. However, I can successfully create a new account once I input a new email address. 

## 🧥Expected behavior
The warning should go away once I input a new email address, so that I know I can create an account.

## 📸 Screenshots
![Screen Shot 2020-09-11 at 11 20 28 AM](https://user-images.githubusercontent.com/26717304/92949964-8b83f300-f421-11ea-87e5-d5611749ef46.png)

## 💻 Desktop

Please complete the following information if accessing the app from a computer:

- OS: Catalina 10.15.4
- Browser: Chrome
- Version [e.g. 22]:  85.0.4183.83 (Official Build) (64-bit)

## 📱Smartphone

n/a

**Comment by csprayregen** [comment]
@arku @katelovescode this does not appear to be fixed. See that the error remains in this example

![Screen Shot 2020-09-18 at 9 36 26 AM](https://user-images.githubusercontent.com/26717304/93610126-4cf6b700-f992-11ea-9b1e-328d25d24f55.png)

Additionally, this error does not appear at all when there are other errors. It seems to take this one as last priority. 
![Screen Shot 2020-09-18 at 9 34 45 AM](https://user-images.githubusercontent.com/26717304/93610167-57b14c00-f992-11ea-9064-53da42eb5709.png)

**Comment by naresh3599** [comment]
Hii @csprayregen , would like to work on this, 
please assign me!

**Comment by csprayregen** [comment]
Done @naresh3599 !

**Comment by narendran-kannan** [comment]
I need quite more details on how to reproduce this @csprayregen 
Do we need to remove that error msg "Email has already been taken" after they've changed their email in frontend?
Correct me if I'm wrong

**Comment by katelovescode** [comment]
> I need quite more details on how to reproduce this @csprayregen
> Do we need to remove that error msg "Email has already been taken" after they've changed their email in frontend?
> Correct me if I'm wrong

Yes, that is my understanding.  If you get the error message, do not submit the form, and then change your email address in the form, the error message still displays.

Also there's a second problem: if other errors are displayed, this one does not display at all.  Let us know if you can't reproduce!

**Comment by narendran-kannan** [comment]
> > I need quite more details on how to reproduce this @csprayregen
> > Do we need to remove that error msg "Email has already been taken" after they've changed their email in frontend?
> > Correct me if I'm wrong
> 
> Yes, that is my understanding. If you get the error message, do not submit the form, and then change your email address in the form, the error message still displays.
> 
> Also there's a second problem: if other errors are displayed, this one does not display at all. Let us know if you can't reproduce!

No, @katelovescode I couldn't reproduce this error, 
In pie-staging.herokuapp.com
I've tried to submit existing email, and error is shown and I've changed the mail, error gone?
Everything works fine?
Maybe I can't reproduce this?
Can you tell me how to reproduce this?

**Comment by katelovescode** [comment]
![stickyerrormessage](https://user-images.githubusercontent.com/8364647/95335370-f1269c00-0874-11eb-9448-a7d7d9f6e83d.gif)

You can ignore the second problem of other errors preventing the email already taken error - I figured out what that is and I have to chat with Chelsea and Rebecca about it.
