### ISSUE TITLE
Column issue on Getting Started page tablet size

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#355]
## 🤬 What's wrong?
On tablet size for the Let's Get Started page, the 4 cards should be in a 2x2 format. Instead, they stay 4 across and get very skinny.

## 👉🏼 Steps to Reproduce
1. Go to https://pie-staging.herokuapp.com/getting-started
2. Using the Inspect feature in Chrome, or simply by dragging, move your browser thru different screen sizes. You will see the format jump straight from a single row to a single column, instead of behaving differently at the tablet-sized breakpoint. 

## 🧥Expected behavior
Correct Figma mockup for this size is here: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=313%3A1049

The screen sizes we're building for are below. In size sm (768 px), we expect the 2x2 layout pictured in Figma. Instead, we see the single row layout pictured in Figma for the two larger screen sizes, and then we jump straight to the single column layout pictured in Figma in xs size. 
-     xs: '360px',
-     sm: '768px',
-     md: '1024px',
-     lg: '1280px'

## 📸 Screenshots
![Screen Shot 2020-09-21 at 7 28 55 PM](https://user-images.githubusercontent.com/26717304/93834201-a08e2c80-fc40-11ea-84d6-65d8392f172a.png)

## 💻 Desktop

Please complete the following information if accessing the app from a computer:

- OS: Catalina 10.15.4
- Browser: Chrome
- Version [e.g. 22]:  85.0.4183.83 (Official Build) (64-bit)

## 📱Smartphone

Please complete the following information if accessing the app from a mobile phone:

**Comment by hmarcks** [comment]
Some Tailwind classes aren't included in the compiled css on staging – `xs:grid-cols-2` in this scenario, but strangely `md:grid-cols-4` is included.

I'm not great with the asset pipeline and I'm still getting my env set up, but thought I'd drop that note.
