### ISSUE TITLE
Update IL algorithms to include absences 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#411]
## ✨ What new feature do you want to see?
Review the IL policy manual and determine how excused absences are handled in the attendance threshold. Does this change our formula?

**Comment by csprayregen** [comment]
Per conversation with @jacqzwy today, this only applies to child care centers, not FCC

**Comment by jacqzwy** [comment]
[https://www.dhs.state.il.us/page.aspx?item=10862](url)
See II. Changes to Eligible Days A. Vacations/Illness (Licensed child care centers only)
[absences.pdf](https://github.com/pieforproviders/pieforproviders/files/5403344/absences.pdf)

**Comment by csprayregen** [comment]
@csprayregen review above resource from Jacqueline before closing issue
