### ISSUE TITLE
Accessibility fixes for sign up view 

### ISSUE THREAD

**Issue by hmarcks** [pieforproviders/pieforproviders#426]
## 🤬 What's wrong?
• Missing two input labels
• Landmark / markup structure issues
• Error text color lacks sufficient contrast
• Language toggle missing focus state

## 👉🏼 Steps to Reproduce
Go to the sign up view and run [axe](https://www.deque.com/axe/) or [Lighthouse](https://developers.google.com/web/tools/lighthouse)

There will be some ARIA issues flagged by the tests, but I imagine it would be very hard to untangle from the Ant components (I'm not qualified). There are also three color contrast issues that are flagged - two are false and one is for a non-essential element that would require some css overrides of the Ant styles, so I left it for now.

## 🧥Expected behavior
See the above issues are no longer present in the testing tools and that the language toggle has a visible focus state when you tab to it.

## 📸 Screenshots
NA

## 💻 Browser Info
NA

## 🍣 Additional context
NA

## 🏓 Implementation Details
NA

**Comment by rebeccakarasiktw** [comment]
Hi @hmarcks I took a look at this in staging and it looks good. I don't know which labels didn't have inputs before but I ran the check and didn't find input issues. I don't know if you made this change or I hadn't seen it before but I noticed that the text in the toast messages is blue when it should be our regular font gray text, #333333, and the background should be ##FFEDED.

<img width="1409" alt="Screen Shot 2020-10-20 at 8 23 35 AM" src="https://user-images.githubusercontent.com/26929739/96585914-3eabfb80-12ae-11eb-85d1-01981325a11d.png">

@cjhaddad do you want to take a look as well?

**Comment by hmarcks** [comment]
@rebeccakarasiktw the phone inputs were the ones missing labels on the SIGN UP view.

Ah, good catch, I can create a new issue and do this small fix unless @cjhaddad you would like to do it quickly in something you're currently working on.
