### ISSUE TITLE
My dashboard displays a table with static data

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#428]
## ✨ What new feature do you want to see?
On my dashboard page - the main page of the app - I see a list of children associated with my account. 

## 🧶 Acceptance Criteria
- [ ] The dashboard matches the design in the mock up
- [ ] The above criteria work in both English and Spanish
- [ ] Verify accessibility (see details below)

## 🖍️ Implementation Details

Notes on Ant components:

- table: https://ant.design/components/table/
Properties we want to use from the table:
- Bordered
- Column header
- Fixed header
- Size: Middle
- Table scroll
-Sort (if it's just a property - otherwise, write a ticket)

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

^^Related to the above, there is a known issue with table headers, see here for more information/potential way to resolve it: https://github.com/ant-design/ant-design/issues/24772

## 🥧 Additional context
Spanish translation is here: https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=0 

The overall design of the dashboard is here: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=2572%3A15126

**Comment by csprayregen** [comment]
@cjhaddad I'm seeing a few issues:

- [ ] The column headers do not translate to Spanish
- [ ] I think you might have missed my translations in the google doc, linked in the ticket and here - these are what you should be using: https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=0
- [ ] On XS size, the grey shadow is in the middle of the screen (see screenshot below)
- [ ] The dashboard table is less inset in staging than in the mockup. @rebeccakarasiktw to comment on how important this is to address ASAP 

<img width="348" alt="Screen Shot 2020-11-01 at 5 38 53 PM" src="https://user-images.githubusercontent.com/26717304/97819045-b5aca100-1c6b-11eb-9a47-4bc2f4ace0e6.png">

**Comment by cjhaddad** [comment]
@csprayregen cool! will make a PR today addressing these items!

**Comment by cjhaddad** [comment]
re: the table being more inset -- I added margins sm >= sized screens.

**Comment by cjhaddad** [comment]
tweaks for this are being made in the PR for #511, fyi
