### ISSUE TITLE
Confirm if IL copay happen at case level vs. child level and update algorithm accordingly

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#446]
Ensure revenue projections are accurate based on this rule after reviewing in the manual

**Comment by jacqzwy** [comment]
Confirming that copays happen at the case level monthly. I've updated the algorithm in the spreadsheet to reflect this. 
[[provider_copay.pdf](https://github.com/pieforproviders/pieforproviders/files/5410533/provider_copay.pdf)](url)
