### ISSUE TITLE
My dashboard displays static summary statistics above the table

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#449]
## ✨ What new feature do you want to see?
I can see the summary statistics at the top of my dashboard above the table. These display static data. 

## 🧶 Acceptance Criteria
- [x] Guaranteed revenue is included with a definition 
- [x] Potential revenue is included with a definition 
- [x] Max approved revenue is included with a definition
- [x] Attendance rate is included with a definition
- [x] The above criteria work in both English and Spanish
- [x] Verify accessibility (see details below)

## 🖍️ Implementation Details
Future work will include hooking the front end up to the API, for now this implementation should use mock static data for front-end design.  @cjhaddad if you need me to mock up some data, let me know

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🥧 Additional context
Spanish translation is here (still needs to be updated for these features): https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=0 

The overall design of the dashboard is here - make sure to use this version, not similar ones near it: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3003%3A14298

**Comment by rebeccakarasiktw** [comment]
Hi @cjhaddad about your question about the stats in different sizes. In the design there are two elements in the static states, 1 is the statistic (Example: Min. revenue expected title, $981 number, Based on attendance to date description) the other is the divider. 
In L & XL sizes, each statistic should take up 3 columns width, and the divider should be centered on the next column.
In M size, each statistic is 6 column width and the divider should be centered on the next column: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3131%3A14347
In S & XS sizes, each statistic should take up 8 columns width, and the divider should be centered on the next column: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3131%3A15202

**Comment by katelovescode** [comment]
<img width="1094" alt="Screen Shot 2020-11-15 at 6 43 14 PM" src="https://user-images.githubusercontent.com/8364647/99201831-7a819600-2772-11eb-957a-554e4bff3ee4.png">

Are these meant to have Spanish translations as well?

**Comment by katelovescode** [comment]
> Are these meant to have Spanish translations as well?

Oh, I answered my own question O_O when I hard-refresh after picking "Español", it's in Spanish, but it doesn't seem to change with the button click.

**Comment by cjhaddad** [comment]
QA Notes (@csprayregen): FYI, the figma mockups include the use of three statistics. and because our usage currently includes four, you are going to see some word wrapping occurring at different screen sizes to account for fitting four vs three columns. @rebeccakarasiktw and I looked at this together and I came up with the solution to keep the word wrapping and ensure the alignment of the other rows (the actual statistic and the definition) when the title moves to two lines. let me know if this makes sense or if you need more clarification.
