### ISSUE TITLE
Update copy on Python dashboard 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#487]
## ✨ What new feature do you want to see?
We talked about three different places to update copy - attendance definitions, revenue definitions, and instructions on how to upload attendance.  

## 🧶 Acceptance Criteria
- [x] Attendance definitions copy is added to the dashboard
- [x] Revenue definitions copy is added to the dashboard
- [x] Instructions on how to upload attendance are added to the dashboard 

## 🖍️ Implementation Details
Chelsea to provide initial copy and then give to Jacqueline to edit and implement. 

## 🥧 Additional context
Chelsea's suggested copy (edits welcome):

Guaranteed Revenue
_Based on days already attended_

Potential revenue
_Based on attendance expected for rest of the month_

Max. approved revenue
_If all children meet 80% attendance rate_

Change Attendance Category to "Attendance Risk", then define:
On Track - _likely to meet attendance rate for full payment_
At Risk - _may not meet attendance rate for full payment - encourage family to attend _
Not Met - _full payment not possible; you'll get paid for days attended only_
Sure Bet - _attendance rate met - maximum payment expected!_
Not Enough Info - _email us 16+ days of attendance records to get projections_
(update 16 number to whatever is currently accurate)

Email copy:
For the most accurate estimates, email all your attendance records for this month to info@pieforproviders.com. You can pull a report from software you already use, or fill this spreadsheet. (Link to: https://docs.google.com/spreadsheets/d/1OsNy6BgH09dDf2PlZ32qT7mgJMSmd6sRqxH1bpfccgI/edit#gid=246587558)

Note: we may need to change the email address - I'm waiting for a response from Winnie.

**Comment by hmarcks** [comment]
> Potential revenue
> Based on attendance expected for rest of the month

I may be misinterpreting this calculation, but isn't I more like, "The possible revenue if attendance is 100% for the rest of the month" instead of _attendance expected_?

Also, do we want to add a line about minimum attendance days for accurate estimates? Something like, "The estimates become more accurate later in the month. You will start to get a useful estimate with 16 days of attendance data."

**Comment by csprayregen** [comment]
@hmarcks on Potential Revenue, I initially had that language as well, but I think it's not quite right. If a child has already met the 80% attendance, she actually doesn't need to attend at all for the provider to get her full revenue, and I want to avoid giving the provider the impression that she should push that child to attend (at least for subsidy purposes). Which actually makes me realize the Max Revenue definition was wrong - I changed that. @jacqzwy should double check us though! 

I like the idea of being specific on how much attendance we need. How about here:
Not Enough Info - _email us 16+ days of attendance records to get projections_ 
(@jacqzwy to confirm the right number here)

**Comment by csprayregen** [comment]
That's true. So maybe these are better definitions. I still don't love them though. What do you think? 

Guaranteed Revenue
_Based on days already attended_

Potential revenue
_Maximum possible for the remainder of the month, based on attendance to date_ 

Max. approved revenue
_If all children meet 80% attendance rate_

**Comment by hmarcks** [comment]
This is a bit more clear to me because I could see "for the remainder of the month" being confused as additional $ rather than max total:

_Maximum possible ~~for the remainder of the month,~~ based on attendance to date_

**Comment by csprayregen** [comment]
Hmm, I think I thought that it _was_ additional, but now that I re-read Jacqueline's definitions, I think you're right.. This is a good back and forth. 

I think this is the right copy @jacqzwy @hmarcks 

Guaranteed Revenue
_Based on days already attended_

Potential revenue
_Maximum possible, based on attendance to date_

Max. approved revenue
_If all children meet 80% attendance rate_

**Comment by jacqzwy** [comment]
I think the copy for max approved revenue may be a little confusing and could potentially be interpreted as all children having to individually meet the 80% rate. How about something like If all children in the family meet a combined 80% attendance rate?

**Comment by csprayregen** [comment]
@jacqzwy how about "If all families meet 80% attendance rate."

**Comment by jacqzwy** [comment]
Yeah I think that makes sense. Should we also add a line saying that the 80% threshold is currently 50%?

**Comment by csprayregen** [comment]
Oh good point. Why don't we just say 50% here and we can move it back up to 80% if/when the rule changes @jacqzwy 

So, ""If all families meet 50% attendance rate."

**Comment by csprayregen** [comment]
@jacqzwy as discussed, change Sure Bet to "Sure bet: Maximum payment expected! Based on attendance rate for full and part days "

**Comment by csprayregen** [comment]
@jacqzwy it looks like there is still one copy change not implemented. Change the definition of Potential Revenue to "Maximum possible, based on attendance to date"
