### ISSUE TITLE
I can retrieve attendance rate from the API

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#500]
## ✨ What new feature do you want to see?
The API returns the attendance rate for the dashboard

## 🧶 Acceptance Criteria
- [x] The `case_list_for_dashboard` endpoint returns attendance rate
- [x] Ticket #497 has the necessary query for this data documented

## 🖍️ Implementation Details
Per @jacqzwy:
> The attendance rate is calculated as family total days attended / family total days approved. We don't have separate calculations for different rate types since the threshold applies to the combination of rate type days. This attendance rate is the same for all children of the family.

Technically for IL this calculation is 
```
num-half-days-attended (for each child on the approval) + num-full-days-attended (for each child on the approval) / num-half-days-approved (for each child on the approval) + num-full-days-approved (for each child on the approval)
```
and if the child is approved for half days (for example) but hasn't attended any half-days, half-days are left out of the calculation (cc @csprayregen to verify this algorithm description)

This requires an association to rate types, so is blocked behind #515 and #516 

- Edit the /dashboard endpoint to calculate and return this field in the response for a list of the user's children (if it doesn't already)
- Document the endpoint and field in the ticket listed in the acceptance criteria. For example:
> Endpoint: GET /api/v1/case_list_for_dashboard
> Authentication required: yes
> Authorization: scoped to the user's children
> Example response:
> ```
> [
>     {
>         "full_name": "Maria Baca",
>         "approvals": [
>             {
>                 "case_number": "5184465331"
>             }
>         ]
>     },
>     {
>         "full_name": "K'Shawn Henderson",
>         "approvals": [
>             {
>                 "case_number": "5198908053"
>             }
>         ]
>     }
> ]
> ```

## 🥧 Additional context
Figma link for reference of initial implementation of this query on the front-end: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=2734%3A261

**Comment by katelovescode** [comment]
Going to break this down into smaller items that need to be implemented; the scope on this is very large based on what's still not implemented in the data model.

**Comment by csprayregen** [comment]
Closing with additional QA coming on #769
