### ISSUE TITLE
I can retrieve the attendance risk category from the API

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#505]
🧮 Blocked behind #500 for the initial attendance rate algorithm

## ✨ What new feature do you want to see?
The API returns the attendance risk category for the dashboard

## 🧶 Acceptance Criteria
- [x] The `case_list_for_dashboard` endpoint returns attendance risk category
- [x] Ticket #504 has the necessary query for this data documented

## 🖍️ Implementation Details
- Parameters:
```
Child level
Number of full days attended so far: full_days_attended
Number of part days attended so far: part_days_attended
Total days attended: total_days_attended =  full_days_attended + part_days_attended

Number of full days approved: full_days_approved
Number of part days approved: part_days_approved
Total days approved: total_days_approved =  full_days_approved + part_days_approved

Family level
Number of children in the family: n_child

Number of family full days attended so far: family_full_days_attended
Number of family part days attended so far: family_part_days_attended
Family total days attended: family_total_days_attended =  family_full_days_attended + family_part_days_attended

Number of family full days approved: family_full_days_approved
Number of family part days approved: family_part_days_approved
Total family days approved: family_total_days_approved =  family_full_days_approved + family_part_days_approved

Time
Number of days from start of the month to max date in attendance data for the month: days_elapsed 
Number of days left in the month: days_left (weekends? Assume more than 12 unusual?)
Number of days in month: month_days = days_elapsed + days_left 

Attendance threshold: threshold (COVID threshold = 0.495, normal threshold = 0.795)

---------------------------------------------------------------------------
Approved
------------------------------------------------------------
threshold%
-------------------|________________________|
Attended           gap (threshold * approved - attended)
```

- Formulas:
```
# Not enough information (applies to all children based on attendance data uploaded)
days_elapsed / month_days < 0.5

# Sure-bets (threshold met)
family_total_days_attended / family_total_days_approved  >= Threshold 

# Not met (threshold not met)
(threshold * family_total_days_approved  -  family_total_days_attended) > n_child * days_left 

# At-risk: Percentage rule
We adjust the family attendance rate according to the fraction of the month elapsed (days_elapsed / month_days)
family_total_days_attended / [(days_elapsed / month_days) * family_total_days_approved] < threshold AND NOT not met

# On-track - anyone else not in above categories
```

- Edit the /case_list_for_dashboard endpoint to return this field in the response for a list of the user's children (if it doesn't already)
- Document the endpoint and field in the ticket listed in the acceptance criteria. For example:
> Endpoint: GET /api/v1/case_list_for_dashboard
> Authentication required: yes
> Authorization: scoped to the user's children
> Example response:
> ```
> [
>     {
>         "full_name": "Maria Baca",
>         "approvals": [
>             {
>                 "case_number": "5184465331"
>             }
>         ]
>     },
>     {
>         "full_name": "K'Shawn Henderson",
>         "approvals": [
>             {
>                 "case_number": "5198908053"
>             }
>         ]
>     }
> ]
> ```

## 🥧 Additional context
Figma link for reference of initial implementation of this query on the front-end: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=2734%3A261

**Comment by csprayregen** [comment]
Closing with additional QA coming on #769
