### ISSUE TITLE
Determine units for transportation fee in NE (per trip?  per mile?)

### ISSUE THREAD

**Issue by JonErvin** [pieforproviders/pieforproviders#507]

**Comment by csprayregen** [comment]
@JonErvin based on research I did and documented here, this seems to be pretty clearly per one way trip. Can re-open this card if you think there is more complexity here I'm missing: https://docs.google.com/document/d/127Qrzf6vuA5RJ0aaAG_kfY_WBc2fNL1puwiMCnbyF38/edit
