### ISSUE TITLE
I can associate a subsidy rule with a child when the child is added via any method

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#514]
## ✨ What new feature do you want to see?
In Illinois, based on Child's age, and County where care is received, a SubsidyRule is associated with a ChildApproval when the Child is created

## 🧶 Acceptance Criteria
- [ ] When I `create` an instance of the Child model, the correct SubsidyRule is applied to the child's _current_ ChildApproval instance

## 🖍️ Implementation Details

For initial MVP usage, the plan is for children to be created via a rake task parsing CSVs.  Eventually this will be done via the API, but for now it probably makes sense to do this logic in a service class we can call from the model, from rake tasks, or from the controller.

**Comment by weedySeaDragon** [comment]
@katelovescode - So this issue is:
1. Somehow populate the Illinois Subsidy rules or ensure they already exist
1. parse a CSV to create 1 or more children
2. when creating a child:
   - find the appropriate subsidy rule based on the State and County
   - create a ChildApproval and associate it with the subsidy rule

is that correct?

**Comment by katelovescode** [comment]
> @katelovescode - So this issue is:
> 
> 1. Somehow populate the Illinois Subsidy rules or ensure they already exist
Yes - and for testing/development right now we can just do a few subsidy rules in the seeds that match some of the kids in the seeds.

> 2. parse a CSV to create 1 or more children
>    * the CSV is the `Onboarding spreadsheet` as described in the `narrative_data_model.md`
yes

>      * can we assume that the CSV file is valid (no malformed entries; no missing data)?  or do we need to check as it's parsed?
yes

>      * can we assume that location info (states, counties, cities, zipcodes) are in the DB?
yes

>      * can we assume that the subsidy rules and rates are in the DB?
yes

>      * what if a zipcode entered is not found?
great question, it'll be an edge case but my expectation for MVP is that we return in the response something to the effect of "the following cases were created but no subsidy rule could be found that applied to them" and then maybe in the list add what the problem was - "business zipcode not found" - "no subsidy rule could be found for this kid's age"


> 3. when creating a child:
>    * find the appropriate subsidy rule based on the State and County
Find the appropriate subsidy rule based on the business' county (which should already be an association on the business, so you won't need to search by state), **and the child's age**

>    * create a ChildApproval and associate it with the subsidy rule
yes

**Comment by weedySeaDragon** [comment]
More questions as I'm starting this, @katelovescode :
- each **Business** requires a `user` and a `license_type`
   - how to assign the `user`?  choose the first _admin_ that is found? 
   - should `license_type` be `licensed_center` ?

**Comment by weedySeaDragon** [comment]
Also -- `county` is not unique across States.  So both are needed.

**Comment by katelovescode** [comment]
> More questions as I'm starting this, @katelovescode :
> 
> * each **Business** requires a `user` and a `license_type`
>   
>   * how to assign the `user`?  choose the first _admin_ that is found?

The business will (currently) be associated to the authenticated user that creates it, so you shouldn't have to assign the user.

>   * should `license_type` be `licensed_center` ?

 No, the license_type will be any of those values in the enum (though we're focusing on family childcare centers in the pilot we don't want to restrict it in the code currently)

> Also -- county is not unique across States. So both are needed.

County _name_ won't be unique across states, but once the business is associated to a county, that UUID/relationship should be used to identify the SubsidyRule (which is also associated to a County)

**Comment by weedySeaDragon** [comment]
Aha.  I was assuming that I also needed to create the business if it didn't already exist.  (Even though the description is clear that it's only about creating the _children_.)  
That simplifies things!   Will have the PR in before long.

**Comment by katelovescode** [comment]
> Aha. I was assuming that I also needed to create the business if it didn't already exist. (Even though the description is clear that it's only about creating the _children_.)
> That simplifies things! Will have the PR in before long.

Ultimately we do probably have to do this but it'll be in another ticket.
