### ISSUE TITLE
As a multi-business user I can add businesses to my account - part 1/2

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#52]
## ✨ What new feature do you want to see?
A multi-business user can add businesses to their account.  

## 🧶 Acceptance Criteria

- [ ] -When I arrive at this page, business name is blank with "write your business name here" prompt
- [ ] -When I arrive at this page, the words "Hub ABC" in the top text block are replaced with the Organization field (in the Users table)
- [ ] The above acceptance criteria work for both English and Spanish

## 🖍️ Implementation Details
-The second set of acceptance criteria for this screen are covered in #137
-Adding a site is covered in another ticket #53 

-License types on the front end map the the database as follows:
Licensed family childcare --> licensed_family_home
Licensed group home --> licensed_group_home
Single-site center --> licensed_center_single
Multi-site center --> licensed_center_multi
License-exempt family childcare --> license_exempt_home
License-exempt center (single-site) --> license_exempt_center_single
License-exempt center (multi-site) --> license_exempt_center_multi

## 🥞Additional context
Blank add business page: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=130%3A299
Spanish translation: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=2316%3A7201

First business: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=312%3A112
Spanish translation: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=130%3A299

Multiples/second business: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=2089%3A604

License dropdown mockup: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=185%3A1998
Spanish translation: I believe we already have these in the app, but please let me know if not and I'll add.

Tablet design: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=2119%3A7519

Mobile design: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=588%3A3014 (Note users cannot do the spreadsheet upload process on a mobile or small screen size.)

**Comment by csprayregen** [comment]
@katelovescode starting to break up these tickets. Would it make sense to break up the AC as follows:

Issue 1: 
-When I arrive at this page, business name is blank with "write your business name here" prompt
-When I arrive at this page, the words "Hub ABC" in the top text block are replaced with the Organization field (in the Users table)

Issue 2:
-I can select a license type for my business
-I have the option to add additional businesses, or to click "next"
-The "next" button is disabled until I complete a field
