### ISSUE TITLE
Return only the current approval from the backend

### ISSUE THREAD

**Issue by cjhaddad** [pieforproviders/pieforproviders#526]
## 🤬 What's wrong?

The endpoint '/api/v1/case_list_for_dashboard' should return the current approval. Right now, it returns an array of potentially multiple approvals. We want only one for the dashboard data. 

## 💻 Browser Info

Please complete the following information if accessing the app from a computer:

## 🏓 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by katelovescode** [comment]
@csprayregen - I need to seed the staging database before you can QA, but I'll list testing instructions here as soon as I have data updated.

**Comment by katelovescode** [comment]
@csprayregen I lied - you won't be able to check this behavior until #450 is in; when @cjhaddad gets there, we'll file bugs if she sees unexpected behavior.
