### ISSUE TITLE
I can see tags (with static data) on the attendance rate column in my dashboard table

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#528]
## ✨ What new feature do you want to see?
I can see tags (with static data) in the Attendance rate column of my dashboard table that give me a qualitative summary of my attendance rate for each child. 

## 🧶 Acceptance Criteria
- [x] There is an On Track tag with green coloring
- [x] There is a Sure Bet tag with green coloring
- [x] There is an At Risk tag with red coloring
- [x] There is a Not Met tag with red coloring
- [x] There is a Not Enough Info tag with grey coloring 
- [x] The above criteria work in both English and Spanish
- [x] Verify accessibility (see details below)

## 🖍️ Implementation Details
**Ant component: https://ant.design/components/tag/**
- We want to implement the custom colorful tags
- These tags are non-removable
- See red, green, grey tags here, along with their states (i.e hover, pressed, default): https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=733%3A4545

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🥧 Additional context
Use this Figma mockup (not the ones near it!): https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3003%3A14298
Spanish: https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=0

**Comment by cjhaddad** [comment]
<img width="443" alt="Screen Shot 2020-11-19 at 3 32 31 PM" src="https://user-images.githubusercontent.com/4565578/99732596-ff272980-2a7c-11eb-822e-105ba68186d2.png">

Upon running an axe accessibility analysis on the dashboard view, an alert concerning the contrast of the foreground and background red color came up. Please advise how to proceed @rebeccakarasiktw @hmarcks

**Comment by cjhaddad** [comment]
> <img alt="Screen Shot 2020-11-19 at 3 32 31 PM" width="443" src="https://user-images.githubusercontent.com/4565578/99732596-ff272980-2a7c-11eb-822e-105ba68186d2.png">
> 
> Upon running an axe accessibility analysis on the dashboard view, an alert concerning the contrast of the foreground and background red color came up. Please advise how to proceed @rebeccakarasiktw @hmarcks



Per conversation with Rebecca and Hunter, we switched to using orange instead of red for the at risk and not met tags: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3185%3A2338

**Comment by csprayregen** [comment]
- [ ] There is an On Track tag with green coloring
- [ ]  There is a Sure Bet tag with green coloring
- [ ]  There is an At Risk tag with red coloring
- [ ]  There is a Not Met tag with red coloring
- [ ]  There is a Not Enough Info tag with grey coloring
- [ ]  The above criteria work in both English and Spanish
- [ ]  Verify accessibility (see details below)

**Comment by csprayregen** [comment]
Hey @cjhaddad this looks good! One small tweak - the font in the mock up is 14px, but here it's 12px. If it's an easy fix, would be great to update that.

**Comment by cjhaddad** [comment]
@csprayregen yes! that's easy enough!
