### ISSUE TITLE
As a user I can sign up for an account

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#54]
## ✨ What new feature do you want to see?
I can create an account with Pie for Providers by filling out the user form and clicking submit. 

## 🧶 Acceptance Criteria
- [x] I can enter all the fields present in the UX mockup
- [x] All fields are required except phone
- [x] The field "Preferred Language" defaults to English
- [x] The user must accept the terms of service in order to click submit
- [x] If any required fields are not filled, error states are displayed and submit button is disabled
- [x] The following field validations are present:
  - [x] Email is the correct format
  - [x] Phone is the correct format
  - [x] Password must be a minimum of 8 characters and include both numbers and letters
- [x] If the terms of service are not agreed to, an error state is displayed and submit button is disabled
- [x] I can click submit when all required fields are filled and terms of service are agreed to
- [x] The "terms of service" phrase should link to the TOS content in a separate page
- [x] When I click submit, **my user account is created and** I'm navigated to a page that tells me to check my email (pending design)

## 🖍️ Implementation Details
~This does not need to connect to the API yet - this is blocked by authentication work so this ticket is only for front-end design.~  This is no longer true; API work is here too.

~Verify if semantic UI can be used together with Tailwind within the scope of this card~ Not using Semantic UI for this project.

## 🥧 Additional context
Mockup:
https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=149%3A2227

Terms of service link: https://www.pieforproviders.com/terms/

**Comment by rebeccakarasiktw** [comment]
Attaching logo here
[](url)
![p4p_full_logo](https://user-images.githubusercontent.com/26929739/79985748-b076ca00-8470-11ea-8763-4a82f0e1968a.png)

**Comment by rebeccakarasiktw** [comment]
Adding image of child on the sign in page (this is the cropped version)
![signin-image-child](https://user-images.githubusercontent.com/26929739/79989123-1d8c5e80-8475-11ea-86aa-12d46996bb63.png)

**Comment by csprayregen** [comment]
QA comments: All acceptance criteria met - yay! 

Visual design notes - we will discuss which are priorities to implement:
-Font should be bolded in all three sizes
-Spacing is off on all three sizes - text should be closer to each open field, not evenly spaced between fields

@rebeccakarasiktw - what did I miss?

**Comment by rebeccakarasiktw** [comment]
@csprayregen @katelovescode just to add to Chelsea's comment:
- The font that is the field name should be bold for each field
- The image looks more cropped than it should, and I vaguely remember we discussed it but I don't remember what we said about it?
- The icons do not seem to be the Material Guide icons.
- Icons are 14px but should be 16px (otherwise they are too small)
- Should we get rid of the word "English" while we don't have that functionality?

That's all on my end!

**Comment by katelovescode** [comment]
- [ ] font-weight 600 on the labels
- [ ] 16px between field and following field; 8px between field and its own label
- [ ] 16px error icon and check mark

**Comment by katelovescode** [comment]
@rebeccakarasiktw and @csprayregen this should be ready for re-QA on staging for the checklist in my comment above.

**Comment by csprayregen** [comment]
@katelovescode - My comment on this checklist. Will need your and RK's help determining next steps/urgency. 

@rebeccakarasiktw - please check me on all of these. 

[ ] font-weight 600 on the labels --> this is done. However, do we want that weight on the error message as well. This does not match the mock ups, I think. 
[ ] 16px between field and following field; 8px between field and its own label --> this is done, except doe Phone Number have a bit further distance between field and its own label
[ ]  16px error icon and check mark  --> this is done

**Comment by csprayregen** [comment]
@rebeccakarasiktw @katelovescode moving the two unchecked items in the above comment to a new bug ticket.
