### ISSUE TITLE
Time Calculation

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#544]
## 📋 Summary
We need to figure out the time calculation for ages, attendances, etc., and how time zone factors into that.

Likely, normalizing our timezone usage so that users get their own timezone back regardless of how the date is stored, will require us to put IN the birthdate, attendance times, and subsidy rule effective dates/max age/expiration, etc. with a timezone and calculating it to UTC, and then returning it in the user's timezone (or the business' timezone?)

## 💻 Implementation Details

Possibly use this library: https://github.com/infused/ziptz

## 🧐 Why tho
Time math is hard.

**Comment by weedySeaDragon** [comment]
My recommendation:
**always store and work with times in UTC**
   - use the `ziptz` gem to convert all incoming times to UTC or maybe just always use that to convert before _any_ calculations or storage happens

That gem is a great find, @katelovescode !
