### ISSUE TITLE
As a user, I can see the fields I've uploaded via CSV in a table view format

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#55]
## ✨ What new feature do you want to see?
Users can see that the CSV they've uploaded is correct

## 🖍️ Implementation Details
Mockup: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=131%3A150

**Comment by csprayregen** [comment]
Collapsing into multiple other issues.
