### ISSUE TITLE
Set up GA dashboard for Python prototype

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#555]
## ✨ What new feature do you want to see?
We need to make sure we can access the GA data for the Python prototype test in IL. What account(s) is this connected with? Will we need a unique account or view per dashboard or are they all in the same place? We simply need to know "login" or view rates per month per user.

**Comment by katelovescode** [comment]
This is a great time for us to set up a shared password account, my preference is to use 1Password, where we can all access passwords to accounts like this.  If @csprayregen and @rebeccakarasiktw are okay with this, I'll create an account and share the login info for Google Analytics; all dashboards per deployment will be available via the same GA account.

**Comment by csprayregen** [comment]
Works for me @katelovescode ! Thanks!
