### ISSUE TITLE
Associate a Child to an existing Approval if one with their case number and effective/expiration date already exists

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#562]
## 📋 Summary
When we import a child via CSV (or eventually, the frontend), we will want to check to see if their case number already exists and is active for another child, since approvals are shared for multiple children.

## 💻 Implementation Details

Use the SubsidyRuleAssociator as an example of how we should implement this.
When a child is created or updated, find_or_create_by the approvals using case number, effective_on and expires_on

For Release 2, we'll refactor this to take in all the records from a CSV or JSON request, group by approval information, create approvals first, then associate children with them (ticket TBD)

## 🧐 Why tho

So we don't get duplicate approvals, which will mess up our calculations for attendance rate.

**Comment by csprayregen** [comment]
@katelovescode should this be de-prioritized as an IL ticket or kept as is (if it applies to multiple states)?

**Comment by katelovescode** [comment]
This one's already done, not really QA'able because we don't have an onboarding step right now.
