### ISSUE TITLE
Refactor associating approvals to children on creation

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#563]
## 📋 Summary
We're currently taking each individual child and find_or_create_by the approvals in case another child was imported with the same case.  I want to refactor this to not hit the db until the data is cleaned up.

## 💻 Implementation Details

Refactor this to take in all the records from a CSV or JSON request, group by approval information, create approvals first, then associate children with them

**Notes**
- make sure the CSV parser and reader (this might need a serializing piece) build the exact same JSON that the front end will need to build when importing from onboarding
- group by approval, create approval, create children associated to these approvals

## 🧐 Why tho
Performance on large imports, fewer async jobs or backed up queue of transactions

**Comment by csprayregen** [comment]
Closing because this is now superseded by more recent design and product work
