### ISSUE TITLE
Dockerizing this app

### ISSUE THREAD

**Issue by jhsu802701** [pieforproviders/pieforproviders#576]
## 📋 Summary
Provide an easy and fully automated way to set up this app on any machine.  The current setup instructions don't include everything necessary.  I wish that there were just one script to run after using "git clone" to download the source code.  So I guess I just volunteered to provide this.

## 💻 Implementation Details

* First, I will create a script to set up this app in Linux Mint 20.
* Once I have everything working, I will be in a stronger position to Dockerize this app.

**Comment by jhsu802701** [comment]
I'm currently working on this in the dockerize branch of my fork (https://github.com/jhsu802701/pieforproviders).  I will make a pull request when it's ready.

**Comment by katelovescode** [comment]
@jhsu802701 one other note, I know you'd prefer fewer logs; feel free to add an env var to do verbose logging, as long as it's set to `true` by default, and then you can turn the verbose logging off in the docker container if that helps your workflow; the non-tech users won't ever be running it that way.
