### ISSUE TITLE
If I'm a Nebraska user, my dashboard displays a table with the appropriate Nebraska columns and dynamic data

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#577]
## ✨ What new feature do you want to see?
Nebraska users see a table that is different from the Illinois table. These users see static data in that table. 

## 🧶 Acceptance Criteria
- [x] The column names match the names in the Nebraska mockup 
- [x] The above criteria work in English and Spanish
- [x] Verify accessibility (see details below) 

## 🖍️ Implementation Details
Figma link: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3579%3A1
> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🥧 Additional context
Figma mockup: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3579%3A1
Spanish (see NE tab): https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=1049848154

**Comment by csprayregen** [comment]
@cjhaddad and @rebeccakarasiktw noting one open question here - with this concatenated design in column 1, will the user still be able to sort by business name (using existing ant components)? Is that something Rebecca should investigate, or wait until Candice picks up this card? If there is no ant component, I think we should move forward without the ability to sort by business - we have learned that our main use case is actually a single business user, especially in the Release 1 version of the app. But just wanted to be clear on next steps.

**Comment by cjhaddad** [comment]
@csprayregen re: your question about whether we can sort by business name -- we should be able to. are you imagining the only 'sortable' column for this table will be column 1? I will be able to sort by the business name.

**Comment by csprayregen** [comment]
@cjhaddad I would want us to be able to sort by every column, like in the IL table. Just wasn't sure how Column 1 would work given that now there are three data points in htere.

**Comment by cjhaddad** [comment]
@csprayregen got it! making all columns sortable is doable. and I can hone in on the businessname to be what is used to sort the first column.

**Comment by csprayregen** [comment]
@cjhaddad is there a way to let the user sort by any of the three fields in that first column?

**Comment by cjhaddad** [comment]
For reference -- per conversation with @csprayregen sorting for 'stringified' number columns will be sortable based on the first number in the 'num of num' string.

**Comment by cjhaddad** [comment]
@csprayregen upon some investigation into sorting for the 'child' column -- I have a few thoughts. 1) we need some UI of sorts for the user to be able to select which datapoint in that column to use as the sorting point. 2) I wonder if a filter with a dropdown could help for the desired usage for this, i.e., there's a filter button and upon selecting it a dropdown menu pops up and you can select the things you'd want to continue to show in the table (child from a specific business, etc.) tagging @rebeccakarasik and @hmarcks for input. 

for now, I just made the column sorting alphabetically by child name. we can chat more about this post-holiday.

**Comment by csprayregen** [comment]
Visual QA checklist:
- [ ] Copy matches
- [ ] Copy matches-ES
- [ ] Sorting works on all columns
- [ ] Colors
- [ ] Font
- [ ] Font size
- [ ] Buttons (size, content)
- [ ] Other interactions
- [ ] Responsive
- [ ] Icon (size, correct icon)
- [ ] Padding
- [ ] Spacing

**Comment by csprayregen** [comment]
@cjhaddad issues with the dashboard table:
More important:
- [ ] I cannot sort by last name on column 1
- [ ] I cannot sort by any of the three revenue columns
Less important: 
- [ ] Left justify the Attendance and Revenue headers within their sub-sections in the header
- [ ] There is less space between rows on the first column. But is this simply because the business name is longer than the example business names in Figma? If so, leave as is.

**Comment by cjhaddad** [comment]
@csprayregen I have a PR for all of the sorting right now. Realized I missed this and it is coming soon. Will let you know when it is merged. Will make an PR to address spacing now. Will also let you know when this is ready for QA.

**Comment by csprayregen** [comment]
Hi @cjhaddad a few lingering issues here:
- [ ] When I try to sort by full days, I am redirected to a page that just says "Report Feedback" (screenshot below)
- [ ] I can't QA sorting on any of the numeric columns (all but column 1) since the data is all the same (see Slack message)
- [ ]

**Comment by cjhaddad** [comment]
@csprayregen I must have borked the sorting for fulldays when I added the attendance risk tag. let me fix that! and adding the dollar sign is no problem, sorry I missed that! 
 Once Kate makes the staging data update, we should be good!

**Comment by cjhaddad** [comment]
@csprayregen this ticket is ready for you again on staging. Please confirm $s are present on both NE and IL.
