### ISSUE TITLE
Write IL formulas for integration into web app

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#581]
## 📋 Summary
Write in words, with operators, the formulas that you used to project subsidy revenue, attendance risk (and other relevant figures) in IL, including both the Python prototype and the Google sheets.

## 💻 Implementation Details

You can add those details in this ticket, or link to it in a separate doc. Please check with @katelovescode when you've begun this task to make sure the format and context make sense. 

Current spreadsheet is here: https://docs.google.com/spreadsheets/d/1L0ZxNfaG-2tFsrn2RKwjMVaSiJx8hrhBdhfv5kwCPk0/edit

Current summary of formulas is here: https://docs.google.com/document/d/1vEhEXs8DXw4HZ6mm_dOfcH4QxsAE28dTEXn_NBUHoyk/edit

## 🧐 Why tho
We are going to integrate these formulas directly into code.

**Comment by csprayregen** [comment]
@jacqzwy can you include in your documentation this detail about how the copay is handled when families use multiple providers:

Here’s the full explanation from the state: https://www.dhs.state.il.us/page.aspx?item=54862

Key points: “If a family has more than one child care provider, only one provider is assessed and collects the copayment.If the copay exceeds the amount charged to the first provider, the second provider shall be assessed the remainder. This situation doesn’t happen very often.”

**Comment by jacqzwy** [comment]
Will do
