### ISSUE TITLE
Create a scheduled job to populate staging database with NE onboarding spreadsheet data

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#585]
## 📋 Summary
We anticipate that our MVP Release 1 will not include spreadsheet upload. Instead, users will email us spreadsheets, and we will populate the database on their behalf. 

## 💻 Implementation Details
The fields we will get and the sources we will get them from - as currently scoped in our pilot - are laid out in detail here: https://docs.google.com/document/d/15wOle6y3JDdarluwXCv0UrjQoZ-jnDTpBcBCw8fI-GM/edit

I'm open to discussion on the best way to consolidate these in the upload to lighten the engineering load. 

- This should probably be built as a service that gets called by a rake task, and I'd love to make a separate directory called `demo_support` or something similar so this type of functionality is separate from the actual application.

## 🧐 Why tho
So that users can see their data before we finish building spreadsheet upload

**Comment by katelovescode** [comment]
Blocked by #909
