### ISSUE TITLE
I can see definitions on my dashboard in IL and NE 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#588]
## ✨ What new feature do you want to see?
Add definitions to the dashboard so users can understand what they're seeing. 

## 🧶 Acceptance Criteria
- [x] I've added definitions to the mockup for revenue columns in IL
- [x] I've added definitions to the mockup for attendance risk in IL
- [x] I've added definitions to the mockup for revenue columns in NE
- [x] I've added definitions to the mockup (as needed) for attendance columns in NE

## 🖍️ Implementation Details
Let Chelsea know when this is final so I can create new front end dev tickets to add these.

**Comment by rebeccakarasiktw** [comment]
this is me testing my notifications @rebeccakarasiktw

**Comment by csprayregen** [comment]
@rebeccakarasiktw can you prioritize this for NE as your next work?
