### ISSUE TITLE
Possible flaky test? # billable occurrences API

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#618]
## 📋 Summary

```
Finished in 8.4 seconds (files took 3.52 seconds to load)
212 examples, 1 failure

Failed examples:

rspec './spec/requests/api/v1/billable_occurrences_spec.rb[1:1:1:1:1:1:3:1:1]' # billable occurrences API behaves like it lists all records for a user /api/v1/billable_occurrences get on the right api version when authenticated non-owner billable_occurrences found returns a 200 response

Randomized with seed 21132
```

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by arku** [comment]
Since there's no information on whether the test failure is an assertion failure or an error, it's difficult to debug this one.

@katelovescode Can you add more information on the error if you run into this issue again?

**Comment by katelovescode** [comment]
This isn't necessary anymore - billable occurrences has been removed
