### ISSUE TITLE
Flakey Cypress Login test

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#623]
## 📋 Summary
```
3 passing (40s)
  1 failing

  1) Login
       unconfirmed users
         displays an error message and allows the user to resend the confirmation email:
     AssertionError: Timed out retrying: Expected to find element: `[data-cy="authError"]`, but never found it.
      at Context.eval (http://localhost:5017/__cypress/tests?p=cypress/integration/login.spec.js:111998:55)
```
We're still having issues with this flakey test.  I tried to up the timeout but it will still intermittently time out.  I'm not sure if it's a problem with the timeout length itself and running tests in Github actions or if the test itself is just flakey, but we're having to re-run E2E tests nearly every other time.

## 💻 Implementation Details

In the root package.json file, there is a yarn cypress command. Look at running tests inside the readme. Interactive `yarn start server` and then `yarn cy open`

## 🧐 Why tho

Drastically impacts how quickly we get code out because we have to run the full 10-min suite multiple times for most of our PRs.

**Comment by csprayregen** [comment]
@katelovescode is this relevant to NE as well? If so, will keep prioritized, otherwise will deprioritize

**Comment by katelovescode** [comment]
@csprayregen yeah, this is on the login screen; it's impacting development, we often have to run the test suite twice (which is 20 minutes instead of 10) in order to merge tickets in.  If it was more occasional, I'd care less about it but it's really annoying when we have to re run specs for every dependency update or pull request.
