### ISSUE TITLE
Update NE algorithm for full days converted to hourly days

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#627]
## ✨ What new feature do you want to see?
What are the rules in Nebraska for when a child attends for a number of hours below the full day threshold? Can she "convert" approved days into approved hours? 

After confirming the rules for how this works in Nebraska, review our algorithm. Is this incorporated correctly into our formulas? Would changing it have implications for the data we display to the user on the dashboard?

## 🧶 Acceptance Criteria
- [ ] Add a description of how this rule works to the NE formula overview to be created (see #580)
- [ ] Add a recommendation for how this should change our formulas in Rails into that same overview doc (see #580)
- [ ] Message @katelovescode to share the updated recommendation
- [ ] If this change has implications for dashboard design, message @rebeccakarasiktw 
- [ ] If this change has implications for either back or frontend engineering work, message @csprayregen to create new issues 

(Of course, we can talk as a group as needed, but the above are all the bases that need to be covered). 

## 🥧 Additional context
This has been flagged by partners in NE and other states with the same payment structure as a significant source of revenue loss. Children leave early and providers only get paid for the hours they attended, rather than for the whole day. It would be a value add to help users understand this revenue loss and communicate it to parents. 

NE spreadsheet: https://docs.google.com/spreadsheets/d/1FKw4C6Cw0oQT6YJX8GoSZ5p4-7YaOGIxDe20tb-SaSM/edit

NE policy manual: http://dhhs.ne.gov/Pages/Child-Care-Subsidy-Information-for-Providers.aspx

**Comment by chekos** [comment]
Reference/Context: Section K in the Child Care Provider Handbook ([PDF](http://dhhs.ne.gov/Documents/CCPB24.pdf)) 

<img width="760" alt="Screen Shot 2020-12-11 at 4 25 11 PM" src="https://user-images.githubusercontent.com/28694175/101966694-8e7fb280-3bcd-11eb-8589-03fa934e16a4.png">

**Comment by csprayregen** [comment]
Hey @chekos thanks for getting this started - I replied in Slack hopefully clarifying the question here. Let me know if this makes sense and/or if we should talk live!

**Comment by csprayregen** [comment]
Added this as an open question for community input in NE here: https://docs.google.com/document/d/1XZEafZmDHMsSL3zAZ17MNmiE0uNEbJRPU_C1uK4_cQY/edit#

Moving this card to backlog until we get an answer. At that point, will create another card to integrate this into formulas as needed

@JonErvin @chekos FYI

**Comment by csprayregen** [comment]
Closed because new policy info has superseded this card
