### ISSUE TITLE
As a user, I can see the "Get Started" page 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#65]
## ✨ What new feature do you want to see?
Users can see the "Get Started" page

## 🧶 Acceptance Criteria

- [ ] -The design in the mockup is present
- [ ] I can click the "Get Started" button to be redirected to the next page
- [ ] The word "Amanda" in the mockup is replaced with the user's greeting_name field from the Users table

## 🥧 Additional context
Mockup: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=227%3A307
Tablet: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=313%3A1049
Mobile: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=619%3A2584

**Comment by csprayregen** [comment]
Per KD, need to create separate ticket for the borders and layout of the page - Andrew created this already.

**Comment by csprayregen** [comment]
- [ ]  The design in the mockup is present - not yet - issues noted below: 
Design questions:
- [ ] Across all screen sizes, the icons on the four cards are smaller than in the mockups 
- [ ] Across all screen sizes, the title text on all four cards should be bigger. In staging, I'm seeing 14px for title and body font. In mockups, I'm seeing 18px for title vs. 14 px. for body. I think those relative differences matter for usability. 
- [ ] Across all screen sizes, there is less left/right padding than in the mockups, but I believe this is because of the new layout grid. Could you confirm @rebeccakarasiktw ?
- [ ] In the Large screen size, the break points here are different than in the mockups, but I believe this to be because of the new layout grid. Could you just confirm this @rebeccakarasiktw ? (Did I use the word break point correctly!?)
- [ ] The title (Welcome to Pie...) has the same font size and weight as the mockups, but it looks bigger to me. Am I crazy?! Is this an issue related to typography stuff being handled elsewhere? @katelovescode @rebeccakarasiktw ?

Noting that I'm not doing visual QA on mobile, because we'll need to redirect users to a different screen here (#145)

- [ ]  I can click the "Get Started" button to be redirected to the next page
This doesn't do anything, but I think should be removed as an AC for this ticket, because we're going to work on connecting the screens later. Do you agree @katelovescode ?

- [ ]  The word "Amanda" in the mockup is replaced with the user's greeting_name field from the Users table
This is still showing up as Amanda for me.

**Comment by katelovescode** [comment]
> * [ ]  Across all screen sizes, the icons on the four cards are smaller than in the mockups

Will need to be fixed.

> * [ ]  Across all screen sizes, the title text on all four cards should be bigger. In staging, I'm seeing 14px for title and body font. In mockups, I'm seeing 18px for title vs. 14 px. for body. I think those relative differences matter for usability.

This should probably be left for typography, rather than done ad hoc.

> * [ ]  The title (Welcome to Pie...) has the same font size and weight as the mockups, but it looks bigger to me. Am I crazy?! Is this an issue related to typography stuff being handled elsewhere? @katelovescode @rebeccakarasiktw ?

You are not crazy, will be solved with typography

> * [ ]   I can click the "Get Started" button to be redirected to the next page
>   This doesn't do anything, but I think should be removed as an AC for this ticket, because we're going to work on connecting the screens later. Do you agree @katelovescode ?

Agreed

> * [ ]   The word "Amanda" in the mockup is replaced with the user's greeting_name field from the Users table
>   This is still showing up as Amanda for me.

Will need to be fixed.

@csprayregen given the age of this ticket, can you please move those two things that need to be fixed now into a bug ticket, and we'll close this one out?
