### ISSUE TITLE
Add more realistic data to dashboard

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#665]
## 📋 Summary
For user testing and sales it will be helpful to have a more realistic demo. 

## 💻 Implementation Details
- [ ] Attendance rate should vary from 10% to 75%
- [x] Guaranteed revenue should vary from 200-600
- [x] Potential revenue and Max Approved Revenue should vary from 515 to 1199
- [ ] Max approved should be greater than or equal to potential revenue

## 🧐 Why tho
These are closer to numbers providers would expect to see during the month

@rebeccakarasiktw

**Comment by katelovescode** [comment]
@rebeccakarasiktw ideas?

**Comment by csprayregen** [comment]
@katelovescode confirming we should de-prioritize this as discussed yesterday? What help did you need from Rebecca here?

**Comment by katelovescode** [comment]
This one is done and ready for QA with some caveats:
- attendance rate isn't random, it's tied to how many attendances have been generated using `rails attendances` on the Heroku instance.
- guaranteed revenue numbers are between 0 and 500
- potential revenue is between 500 and 1000
- max approved revenue is between 1000 and 2000
- there's no easy way to base potential or guaranteed revenue on max approved revenue so this is sort of the best stopgap until we get revenue calculations in that won't hold us up.

If those caveats are okay, this is ready to QA and then close.

**Comment by katelovescode** [comment]
(also I think we tagged Rebecca to test her notifications, not because I actually needed her input on this one 😂  )

**Comment by csprayregen** [comment]
Lol I am remembering that now!

**Comment by csprayregen** [comment]
For QA: 

Nebraska
- [ ]  Attendance rate should vary from 10% to 75% -> attendance rate isn't random, it's tied to how many attendances have been generated using rails attendances on the Heroku instance.
- [ ]  Guaranteed revenue should vary from 200-600 -> guaranteed revenue numbers are between 0 and 500
- [ ] Potential revenue should vary from 515 to 1199 -->  potential revenue is between 500 and 1000
- [ ] Max Approved Revenue should vary from 515 to 1199 --> max approved revenue is between 1000 and 2000
- [ ]  Max approved should be greater than or equal to potential revenue --> there's no easy way to base potential or guaranteed revenue on max approved revenue so this is sort of the best stopgap until we get revenue calculations in that won't hold us up.

IL
- [ ]  Attendance rate should vary from 10% to 75% -> attendance rate isn't random, it's tied to how many attendances have been generated using rails attendances on the Heroku instance.
- [ ]  Guaranteed revenue should vary from 200-600 -> guaranteed revenue numbers are between 0 and 500
- [ ] Potential revenue should vary from 515 to 1199 -->  potential revenue is between 500 and 1000
- [ ] Max Approved Revenue should vary from 515 to 1199 --> max approved revenue is between 1000 and 2000
- [ ]  Max approved should be greater than or equal to potential revenue --> there's no easy way to base potential or guaranteed revenue on max approved revenue so this is sort of the best stopgap until we get revenue calculations in that won't hold us up.

**Comment by csprayregen** [comment]
Hi @katelovescode these numbers are fairly different for NE, and the dashboard in staging shows no data for IL. Let's discuss.
