### ISSUE TITLE
As a NE user, I can see dynamic data in the "as of" date field

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#677]
## ✨ What new feature do you want to see?
In the NE dashboard, I see a current "as of" date. This is defined as the last date attendance was uploaded for any child.

## 🧶 Acceptance Criteria
- [x]  I see the As Of date on my dashboard 
- [x]  The above criterion works in both English and Spanish
- [x]  Verify accessibility (see details below)

## 🖍️ Implementation Details
[
    {
        "absences": "1 of 5",
        "approvals": [
            {
                "case_number": "4441500188"
            }
        ],
        "as_of": "12/21/2020",
        "business": {
            "name": "Nebraska Home Child Care"
        },
        "case_number": "case#1",
        "earned_revenue": 1045.32,
        "estimated_revenue": 2022.14,
        "full_days": "14 of 15",
        "full_name": "Rhonan Shaw",
        "hours": "1 of 6.5",
        "transportation_revenue": "30 trips - $80.00"
    },
    {
        "absences": "1 of 5",
        "approvals": [
            {
                "case_number": "8712853078"
            }
        ],
        "as_of": "12/21/2020",
        "business": {
            "name": "Nebraska Home Child Care"
        },
        "case_number": "case#1",
        "earned_revenue": 1045.32,
        "estimated_revenue": 2022.14,
        "full_days": "14 of 15",
        "full_name": "Tanim Zaidi",
        "hours": "1 of 6.5",
        "transportation_revenue": "30 trips - $80.00"
    }
]

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🥧 Additional context
Mockup: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3579%3A1
Spanish: https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=0

**Comment by cjhaddad** [comment]
in the case list for the dashboard this will be a new key "as_of": dateString

**Comment by csprayregen** [comment]
Hey @cjhaddad this does not have the Spanish translation - which is available here: https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=1049848154
