### ISSUE TITLE
I can retrieve Business name from the API for the NE dashboard

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#703]
✨ What new feature do you want to see?
The API returns the Business name category for the Nebraska dashboard

🧶 Acceptance Criteria
- [ ] Ticket #700  has the necessary query for this data documented

🥧 Additional context
Figma link for reference of initial implementation of this query on the front-end: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3579%3A1

**Comment by csprayregen** [comment]
@katelovescode can this be closed since there's no formulas for you to create on top of what Candice has already developed?

**Comment by katelovescode** [comment]
Yes, this is done.
