### ISSUE TITLE
As a user, I can see and follow instructions for preparing and uploading my spreadsheet  

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#71]
## ✨ What new feature do you want to see?
As a user, I can see instructions for uploading my spreadsheet

## 🧶 Acceptance Criteria
- [ ] I can click "Select a file to upload" and select a file from my computer for upload 
- [ ] I can see the screen in the mock up in English
- [ ] I can see the screen in the mock up in Spanish

## 🖍️ Implementation Details
Downloading the spreadsheets themselves are covered in #398 
Upload details are covered in #36 and #116 
An upload bug is covered in #84 
Upload confirmation is covered in #144
-Mobile design (users cannot upload in small screen sizes): https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=588%3A3014

## 🥧 Additional context
-Mockups (tablet and desktop): https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=281%3A1

The current sample spreadsheet is for IL only. We will need to figure out how to integrate NE users as well, and that's covered in #401

**Comment by csprayregen** [comment]
@rebeccakarasiktw do they need to click forward to the next step, or should they be automatically redirected after the upload is complete?

**Comment by katelovescode** [comment]
@csprayregen and @rebeccakarasiktw is this one still accurate?

**Comment by csprayregen** [comment]
@katelovescode definitely out of date - this will be replaced by the new onboarding process which is next up in design for @rebeccakarasiktw

**Comment by katelovescode** [comment]
K, I'm gonna close this ticket for now and we can make new ones when the design is done!
