### ISSUE TITLE
I can retrieve Earned Revenue from the API for the NE dashboard

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#712]
✨ What new feature do you want to see?
The API returns the Earned Revenue category for the Nebraska dashboard

🧶 Acceptance Criteria
- [x] Ticket #707  has the necessary query for this data documented
- [ ] This passes test cases (to be finalized)
- [ ] This matches formulas laid out by the data team (to be finalized)

🥧 Additional context
Figma link for reference of initial implementation of this query on the front-end: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3579%3A1

## Steps to QA

- in your terminal, run the following command:
```
heroku run bundle exec rails nebraska_rates20210813 --app pie-staging
```
- download the production Inputs to S3 sheet as CSV
- change every email address to `nebraska@test.com`
- upload the CSV to S3 in the `test-onboarding-bucket-pie` bucket
- in your terminal, run the following command:
```
heroku run bundle exec rails read_wonderschool_necc_onboarding_cases --app pie-staging
```
- update the children's wonderschool IDs to match their real ones (see the NE Prediction Algorithms - NECC Pilot spreadsheet for the chart) - _**you'll need dev help on this step**_
- in your terminal, run the following command:
```
heroku run bundle exec rails read_wonderschool_necc_attendances --app pie-staging
```
- reload the dashboard and cross your fingers, this should be accurate to what the spreadsheet says for September and prior months.

**Comment by katelovescode** [comment]
First pass at description of logic:
```
IF DAILY UNIT
  IF Special Needs Rate
    active_child_approval.special_needs_daily_rate
  ELSE
    if child_care_center
      child_care_center_daily_rate by child_age and county, multiplied by QRIS bump
    ELSE
      licensed_family_child_care_daily_rate by child_age and county, multiplied by QRIS bump
    end
  end
ELSE
  IF Special Needs Rate
    active_child_approval.special_needs_hourly_rate, multiplied by attendance hourly units (rounded to the next 15 mins)
  ELSE
    if child_care_center
      child_care_center_hourly_rate by child_age and county, multiplied by attendance hourly units (rounded to the next 15 mins), multiplied by QRIS bump
    ELSE
      licensed_family_child_care_hourly_rate by child_age and county, multiplied by attendance hourly units (rounded to the next 15 mins), multiplied by QRIS bump
    end
  end
end

QRIS bump calculations:

if provider is accredited
  accredited_qris_bump_by_provider_qris_level
ELSE
  unaccredited_qris_bump_by_provider_qris_level
end
```

This will be calculated for each attendance as it's created or edited

**Comment by csprayregen** [comment]
@katelovescode seeing a small number of discrepancies:

- For 6980, Estimated Revenue in the spreadsheet is $1906.17. In staging, it is $1,996.94.
- For 8500, Estimated Revenue in the spreadsheet is $630. In staging, it is $660.
- For 8501, Estimated Revenue in the spreadsheet is $630. In staging, it is $660. 
- For 13948, Estimated Revenue in the spreadsheet is $630. In staging, it is $660.

**Comment by csprayregen** [comment]
@katelovescode discrepancies from this morning's QA:

- Attendance risk is not appearing on staging, but does appear in the dashboard now (i.e. there is enough info for all children)
- For 6980, Estimated Revenue in spreadsheet is 1724.63 and in staging it is $1,815.40 (unlike yesterday, this does not match Approved (Scheduled) revenue in the spreadsheet, which is 1996.94)
- For 8500, 8501 and 13948, Estimated Revenue in spreadsheet is $570.00 and in staging it is 600.00
- 7560 and 7561 continue to be accurate (except for attendance risk)

**Comment by katelovescode** [comment]
- [ ] Attendance risk is not appearing on staging, but does appear in the dashboard now (i.e. there is enough info for all children)
- [ ] For 6980, Estimated Revenue in spreadsheet is 1724.63 and in staging it is $1,815.40 (unlike yesterday, this does not match Approved (Scheduled) revenue in the spreadsheet, which is 1996.94)
- [ ] For 8500, 8501 and 13948, Estimated Revenue in spreadsheet is $570.00 and in staging it is 600.00
