### ISSUE TITLE
I can retrieve Attendance Risk from the API for the NE dashboard

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#776]
✨ What new feature do you want to see?
The API returns the Attendance Risk category for the Nebraska dashboard

🧶 Acceptance Criteria
- [x] Ticket #764  has the necessary query for this data documented
- [ ] This passes test cases (to be finalized)
- [ ] This matches formulas laid out by the data team (to be finalized)

🥧 Additional context
Figma link for reference of initial implementation of this query on the front-end: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=3579%3A1

🧞‍♀️ Implementation Details
[WIP] The algorithm for this is:
```
if days_passed >=10
  <calculate risk>
else
  "not_enough_info"
end
```
The best way to implement this is through an adaptation of the Illinois Attendance Risk Calculator (though maybe it should be Revenue Risk Calculator given that this is based on potential revenue rather than straight through the attendances).

**OPEN QUESTIONS**
- In Illinois we use a calculation based on attendance - in Nebraska this is based more on revenue (possibly because of the complications between daily, hourly, etc.).  I think what we're doing here is this:
  - calculating the Scheduled Revenue (ScheduledDailyUnits * DailyRate + ScheduledHourlyUnits * HourlyRate)
  - calculating the Forecasted Revenue which sums the following:
    - Attended Revenue (DailyUnitsAttended * DailyRate + HourlyUnitsAttended * HourlyRate)
    - Absence Revenue (seems to not be used right now? Or maybe we just don't have any?) (DailyAbsences * DailyRate + HourlyAbsences * HourlyRate)
    - Expected Additional Attendance Revenue (RemainingScheduledDays * DailyRate + RemainingScheduledHours * HourlyRate)
  - Subtracting Scheduled Revenue from Forecasted Revenue to get the Difference
  - Percentage difference = (Difference / Scheduled Revenue) * 100
```
# psuedocode:
If Percentage Difference >= 20%
  | ahead_of_schedule |
else if Percentage Difference < 20% > -20%
  | on_track |
else
  | at_risk |
```

It's required that we use the daily and hourly rates because they "weight" the calculations; i.e. if someone is closer to meeting their daily attendance, they're closer to making their scheduled revenue than if they're closer to meeting their hourly attendance (obviously depending on rates!)

**Comment by JonErvin** [comment]
I think, to repeat this approach exactly, the hourly rate and daily rate info is necessary to be able to relate hours and days in the same indicator.  Worked out the algebra below.

That said, there's no reason this indicator is necessarily the right indicator - Nebraska operates differently than IL so we just came up with something simple as a starting point.  There could be some creative ways to come with a different indicator (e.g., by making an assumption about the relative value of hours and days).  How important is it to get this implemented without the rates in place?  Easiest path is probably to wait until rates/revenue are in the model, but there could be other paths.

**Algebra for Revenue Indicator**
Difference = ForecastRev - ScheduledRev
= (EarnedRev + ExpectedRev) - ScheduledRev
= (ActualRev + AbsenceRev + ExpectedRev) - ScheduledRev
= (ActualDayUnits + AbsenceDayUnits + ExpectedDayUnits) * DailyRate + (ActualHourUnits  + AbsenceHourUnits + 
   ExpectedHourUnits) * HourlyRate - ScheduledDayUnits * Daily Rate + ScheduledHourUnits * HourlyRate
= (ActualDayUnits + AbsenceDayUnits + ExpectedDayUnits - ScheduledDay Units) * Daily Rate + 
   (ActualHourUnits + AbsenceHourUnits + ExpectedHourUnits - ScheduledHourUnits) * Hourly Rate

**Comment by katelovescode** [comment]
Yeah, now that you've explained how the rates actually weight the calculation, I totally get it.  Thank you so much!
