### ISSUE TITLE
Write test cases for NE formulas

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#784]
## 📋 Summary
Create plain language test cases in the NE formulas doc to be used in testing the implementation of these formulas in Rails. 

- [x] Review NE formulas doc and spreadsheet
- [x] Create test cases to cover attendance-related estimates
- [x] Create test cases to cover revenue estimates
- [x] Test rollup numbers and individual numbers
- [x] Test edge cases and straightforward cases 
- [x] Share with @katelovescode for feedback and use 

## 💻 Implementation Details
NE formula doc with link to spreadsheet: https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🧐 Why tho
So we know our formulas are working!

**Comment by JTBassett** [comment]
Hey Chelsea, I don't think I have the ability to check off the boxes on this card - not sure what is off with my settings. This card can be moved in progress and I'll be reaching out to Kate to check in about her thoughts shortly!

**Comment by csprayregen** [comment]
Thanks @JTBassett ! Tried to update your role, but I might have made it worse (lol). In the meantime, I moved the card.

**Comment by JTBassett** [comment]
@katelovescode I'm still struggling with adding cards at the moment, but hopefully tagging you here to check the updated test cases works just as well! It starts on page 23 of [this doc](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#).

**Comment by csprayregen** [comment]
Great! I'll move this to in QA and add Kate as an assignee to give feedback.

**Comment by katelovescode** [comment]
I'll review this on Tuesday after we start documentation!

**Comment by csprayregen** [comment]
@katelovescode per Jon's comments in Slack, it may make sense to wait for @JTBassett to do an updated version of these, as the formulas have changed significantly

**Comment by JTBassett** [comment]
@katelovescode I updated the cases based on Jon's new calculations in the [model doc](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#heading=h.lat1zbge2l51). I know there are lots of aggregated inputs, so please let me know if there are any questions or suggestions for making it clearer. Thanks!

**Comment by katelovescode** [comment]
> @katelovescode I updated the cases based on Jon's new calculations in the [model doc](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#heading=h.lat1zbge2l51). I know there are lots of aggregated inputs, so please let me know if there are any questions or suggestions for making it clearer. Thanks!

Thanks JT, will look this weekend!
