### ISSUE TITLE
Add Brakeman for Security

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#8]
## 📋 Summary
Implement Brakeman into the Rails app (and React?  Does it do frontend?)

## 🧐 Why tho
Securiteeeeeeeeeee - automated

**Comment by brobertsaz** [comment]
@katelovescode I suggest using the [Pronto gem](https://github.com/prontolabs/pronto) a Git hook to run before push.

We could add Brakeman and Rubocop for starters.

**Comment by katelovescode** [comment]
Feel free to make a PR for me to test out and review!
