### ISSUE TITLE
Hitting routes directly doesn't work

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#83]
## 🤬 What's wrong?
Hitting routes directly doesn't work

## 👉🏼 Steps to Reproduce
1. visit pie-staging.herokuapp.com
2. you'll be redirected to pie-staging.herokuapp.com/login
3. hit pie-staging.herokuapp.com/login directly
4. the UI will not load

## 🧥Expected behavior
Hitting routes directly should load the UI just like being redirected there

## 💻 Desktop
**(please complete the following information if accessing the app from a computer)**
 - OS: Mac OSX
 - Browser: Chrome

**Comment by rahman-aj** [comment]
As i made some research i found out that the problem is because of server configuration problem.
Heroku runs on nginx as i find out and there should be some files that i couldn't find in the project that should be edited to fix the problem.
