### ISSUE TITLE
Upload .xls and .xlsx

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#84]
##  🕷Description

As a user I want to be able to upload .xls and .xlsx (in addition to .csv)

## 🍭 Steps to Reproduce
1. Go to 'https://pie-staging.herokuapp.com/cases/import'
2. Click on 'CSV import'
3. Try to upload a .xls

## 🍣 Additional context

- Devices you saw the bug on: Mac laptop
- Any other information that's relevant: We expect users to have .xls files not only .csv

## 🧮 Priority

Medium

**Comment by jessehall3** [comment]
Current questions:

1. For xlsx/workbooks, would the user need an option to select a particular tab or sheet? Is this looking too far ahead, are we just expecting to choose the first sheet available?

1. Any concerns with using [xlsx](https://www.npmjs.com/package/xlsx) as the library for this? It's big, but very popular and well supported.

1. Are we ok with just a simple upload button with little to no error handling and feedback for now, or are we looking to make use of a robust upload or dropzone library?

1. What should the output data look like? Right now it looks like:
`[
    [Harry, Potter, 123-45-6789],
    [Pie, Provider, 987-65-4321]
]`
Is that okay for now?

1. Are we looking to output (to the view) anything beyond a simple table for now?

**Comment by katelovescode** [comment]
Hey Jesse - I think I answered these questions poorly last time we talked, I'm not sure I understood the correlation between these questions and the shifting requirements. Once you started working on this we developed a template XLS; sorry that happened while you were working on it.  A couple of ideas: we can merge your PR and write another ticket for the requirements of the new spreadsheet, or we can change the requirements of this ticket and you can either open a new PR or reopen this one and make changes.  @jessehall3 any preference about which route we take?

**Comment by jessehall3** [comment]
Thanks for the update, @katelovescode  Please feel free to merge the PR and/or make a new issue as you see fit. I can't commit to working on the future issue right now but I will take a look at it if it is created.

**Comment by katelovescode** [comment]
Sounds good - since we've been getting better at defining issues and reducing scope on them, we've got a couple smaller tickets if you're still interested in working on some stuff!  Sorry this one got away from us.

**Comment by csprayregen** [comment]
- [ ]  .csv, 

- [ ] .xlsx

- [ ] .xls

**Comment by csprayregen** [comment]
@arku @katelovescode .xls produced this error (Github doesn't support it, so I can't attach the file, but can share over slack!)

![Screen Shot 2020-08-28 at 10 38 09 AM](https://user-images.githubusercontent.com/26717304/91586244-b3039780-e91a-11ea-87c9-ff5365a2a19d.png)

**Comment by katelovescode** [comment]
> * [ ]   .csv,
> * [x]  .xlsx
> * [ ]  .xls

@arku can you investigate this?
