### ISSUE TITLE
When I select a month in the date dropdown, that month is requested from the API

### ISSUE THREAD

**Issue by rebeccakarasiktw** [pieforproviders/pieforproviders#846]
## ✨ What new feature do you want to see?
When I select a month in the date dropdown, that month is requested from the API. The user interaction with the dropdown is ticketed in #928 

## 🧶 Acceptance Criteria
- [x] When the date is changed, and the new data is retrieved, the front end re-renders with new data 
- [x] This works for the NE and IL dashboard --> IL only for now; NE is not visible

## 🖍️ Implementation Details

![Screen Shot 2021-03-07 at 3 49 01 PM](https://user-images.githubusercontent.com/8364647/110256107-baa49880-7f5c-11eb-9433-abfc712b2c30.png)

## 🥧 Additional context
Figma mockup: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=4547%3A16651
Spanish: https://docs.google.com/spreadsheets/d/1d0RPc9PXvTCFpq8bfkZxgNL35MEpX5s8EvBwqex8564/edit#gid=0

**Comment by cjhaddad** [comment]
@katelovescode a reminder to add what the name of the data field is

**Comment by katelovescode** [comment]
@cjhaddad - the value of the `first_approval_effective_date` field can be nil or a date

cURL request:
```
curl --location --request GET 'localhost:3000/api/v1/case_list_for_dashboard?filter_date=2021-01-02' \
--header 'Accept: application/vnd.pieforproviders.v1+json' \
--header 'Authorization: Bearer <token>'
```
