### ISSUE TITLE
Move Google Analytics to production

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#860]
## 📋 Summary
analytics to implement:
- when people visit dashboard
  -- send email address with the analytic

other ideas to possibly implement:
- confirmation 

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by cjhaddad** [comment]
@csprayregen this is ready for QA! not 100% sure how to create views for user id, do you? everything should be viewable on the 'Pie for Providers Staging' properties/ apps, when interacting with https://pie-staging.herokuapp.com
