### ISSUE TITLE
Check permissions on Heroku production

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#861]
## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by katelovescode** [comment]
Chelsea, Candice and I are the only ones with access to Pie Prod right now - @rebeccakarasiktw if you're going to want to look at production data using that data clip I think you'll have to accept the heroku invite I sent a while back.  Let me know if you need me to re-send it.

**Comment by rebeccakarasiktw** [comment]
@katelovescode yes, can you resend it please? thank you! (no rush)

**Comment by katelovescode** [comment]
> @katelovescode yes, can you resend it please? thank you! (no rush)

Resent!
