### ISSUE TITLE
Finalize data share details with Wonderschool

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#905]
## 📋 Summary
- [x] Confirm S3 dump --> deferred 
- [x] Confirm timing of S3 dump --> deferred 
- [x] Child fields are missing. Do they need our help to identify which children have subsidy cases, or can they pull that from data the provider has entered to WS? (If the former, I can update the onboarding tracker to make this explicit: https://docs.google.com/spreadsheets/d/1jMuOkv3WSUCBjQAnbZ16-TPCtCp1rnroSH1hb5O0oJE/edit#gid=1849635746 --> added
- [x] If a provider changes a field in the onboarding data, will we see the update? (e.g. county is blank for most currently). Ideal to get that update. --> all tables will refresh every 4 hours
- [x] Confirm timing of adding child weekly schedule data to dashboard view; clarify this is currently needed to generate most of our dashboard estimate --> done

**Comment by katelovescode** [comment]
Contacted WS today via Slack, waiting for responses
