### ISSUE TITLE
Finalize onboarding data fields and add tab to template spreadsheet

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#909]
## 📋 Summary
- [x] @JonErvin create an additional tab that collates all the onboarding data into one tab. Each row is a child, and each child carries with it a provider, case, etc. (data entry for onboarding will be to multiple tabs, and the relevant fields will be pulled into this single tab)
- [x] @csprayregen work with Jon to mock up this tab and confirm fields with @katelovescode

**Comment by csprayregen** [comment]
@JonErvin @katelovescode I think this is this a duplicate of #907. Is that correct?

**Comment by JonErvin** [comment]
@csprayregen I took this to cover the steps of uploading inputs to S3 (i.e., child-level, family-level, and provider-level) while #907 was focused on the dashboard and associated outputs.

**Comment by csprayregen** [comment]
Yes you are absolutely right, thank you for clarifying @JonErvin !

**Comment by JonErvin** [comment]
Awesome thanks @csprayregen.

Speaking of uploading inputs, @katelovescode here is a sample inputs csv. The field list and datatypes are on page 9 in the [docs](https://docs.google.com/document/d/1IRbjS3mgbzTA8yzR38ewg10sTsfKN-HUxr9WyLpbvAw/edit#). 

Each row represents one child and includes the associated provider (many to 1 relationship) and associated set of family fee approvals (1 to many relationship).  You'll see provider information repeated for each relevant child.  To handle the 1 to many relationship for family fees, each family fee approval (up to 5) has its own set of four columns (1 for each of the relevant fields).  Happy to explain further and/or set up differently if there's a more useful way to take in the data.
