### ISSUE TITLE
Allow Chelsea to see who has created an account in the DB

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#911]
## 📋 Summary
Chelsea should know whether a provider has created an account before she executes the onboarding Rake task. 

- [x] Write a data clip so Chelsea can see who's in the DB (or any other preferred method for pulling this data)
- [x] Teach Chelsea how to access this info

**Comment by katelovescode** [comment]
@csprayregen - this is how you can get to the Production Users dataclip I set up.  Occasionally a "load new data" button will display and you can click it to refresh the query
![dataclips](https://user-images.githubusercontent.com/8364647/107533493-9c799180-6b84-11eb-9391-e6d4e6a04922.gif)
