### ISSUE TITLE
Parse attendances into the db to prep for the app doing revenue calculations 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#913]
## 📋 Summary
The goal is to be able to take data directly from WS's attendance data dump and use it for the revenue calculations, once those are implemented in the app. To prepare for this:
- [ ] Create importer rake task
- [ ] Add logging if the user isn't found
- [ ] Add instructions/buckets for manually uploading WS's attendance data to S3
- [ ] Parse the attendance data and make sure to find/overwrite existing records with the same attendance ID so we don't make dupes

## Implementation Details
Open Questions/Out of Scope:
- ~~Can WS add an attendance ID to the table, i.e. their unique ID so we can match on that?~~
- Can we get the attendances from a public CSV?
- Can we scrape the website with the password access to get this information rather than manually downloading it?

**Comment by katelovescode** [comment]
@csprayregen this is on hold while we wait for updates from Wonderschool; we're hoping we can pull the child info from a CSV link automatically but if not we can scrape the website.  For now I think the formulas are most important so I'm going to move on to those and we'll keep doing manual attendance upload.
