### ISSUE TITLE
As a user, I should be able to reset my password

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#92]
## ✨ What new feature do you want to see?
As a user I should be able to reset my password with a form if I've forgotten it

## 🖍️ Implementation Details
Integrate with devise; seemingly if you send a request to `/password` with the user's email (see the Postman collection), you'll get an email with a link to confirm and reset but currently with no views, nothing happens.  We'll need to investigate (and it'll be related to how we handle email confirmations)

**Comment by sassygrody** [comment]
dupe! of 121
