### ISSUE TITLE
"As of date" falls off screen in XS size on NE dashboard

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#927]
## 🤬 What's wrong?
"As of date" falls off screen in XS size on NE dashboard

## 🏓 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by nneka-nu** [comment]
I'd like to work on this issue, @katelovescode.

**Comment by katelovescode** [comment]
@nneka-nu Feel free to grab it and make a PR!

**Comment by nneka-nu** [comment]
@katelovescode I'm unable to push my work. Looks like I need permission to access the repo.
