### ISSUE TITLE
As a user I can confirm my email as part of account creation

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#93]
## ✨ What new feature do you want to see?
When I create an account, I should get an email asking me to confirm my email by clicking a link, and when I click on it I should be redirected to the login page

## 🧶 Acceptance Criteria
- [x] When I click submit on user sign up page (per acceptance criteria on #54), I receive email with design and copy that matches the mock up below
- [x] The email is addressed to the user's first name
- [x] When I click the link in that email, it takes me to the log-in page
- [x] When I copy and paste the link in that email, it takes me to the log-in page

## 🖍️ Implementation Details
Follows from account sign up, see ticket #54 
Will be related to password reset behavior, see ticket #92 

Currently devise is sending emails (in localhost, they'll display in the logs unless you configure the development environment to send through whatever email service you have (I personally use GMail and an app password), see: https://github.com/pieforproviders/pieforproviders/blob/develop/config/environments/development.rb#L38

When you click the link it takes you to a blank confirmation page; it should redirect you to the login page instead.

If we can implement devise to log people in automatically without going back to the log in page when they click their confirmation link, and it's an easy config, we should do it in this ticket.  If it seems like a bigger lift, we should make another ticket.

## 🥧 Additional context
Email mockup: https://docs.google.com/document/d/16N5nEuKHZ31qECS4hqw6dtVowOrVsVAKRjQ-WZw6mg8/edit

## 🧳 Steps to test

- sign up as a new user
- click the confirmation link that opens in the browser
- you should be logged in and redirected to getting-started
- log out
- click the confirmation link again
- you should get an error telling you your user has already been confirmed, and you should try logging in
- log in as the new user
- you should be logged in and redirected to getting-started
- visit pie-staging.herokuapp.com/confirm?confirmation_token=cactus
- you should get an error indicating your token is invalid and that you should request a new confirmation token (this behavior does not exist)

**Comment by rebeccakarasiktw** [comment]
Hi @katelovescode @csprayregen why does the user need to be redirected to the login screen? Can't they just be signed in once they click the link from their email?

**Comment by katelovescode** [comment]
@rebeccakarasiktw doing a direct pass-through to sign in *might* work out of the box with Devise (our auth library), but I'm not sure that it does.  I would consider the sign-in-when-you-confirm functionality to be an enhancement unless we find out that Devise does it by default.

**Comment by csprayregen** [comment]
@katelovescode asked you a question in Slack about functionality. One formatting issue - logo is showing up as an attachment rather than in email body. If this is a quick fix, let's address. Otherwise, I say we close this without a logo at all, and address it as a low priority bug later.

**Comment by katelovescode** [comment]
> * [ ]  visit localhost:3000/confirm?confirmation_token=cactus. you should get an error indicating your token is invalid and that you should request a new confirmation token (this behavior does not exist) - no, I get an error
> 
> ![Screen Shot 2020-09-04 at 12 06 37 PM](https://user-images.githubusercontent.com/26717304/92267842-f3c55880-eea6-11ea-8b0c-9fd25422985a.png)

@csprayregen this one's on me, instead visit `pie-staging.herokuapp.com/confirm?confirmation_token=cactus` - I just copied/pasted and it had the address for local testing, sorry.

**Comment by csprayregen** [comment]
@katelovescode this works now!

**Comment by csprayregen** [comment]
@katelovescode as discussed, one last formatting issue here - we need carriage returns in the email, and we need to center the logo. Carriage returns are correctly displayed in this earlier version of the email (which had a broken logo) and in the mock up

![image](https://user-images.githubusercontent.com/26717304/92404425-2b2b4380-f0f9-11ea-841e-f716c6458c97.png)

**Comment by csprayregen** [comment]
@katelovescode final formatting issue - could you center the logo here 
![Screen Shot 2020-09-07 at 11 04 26 AM](https://user-images.githubusercontent.com/26717304/92404884-1602e480-f0fa-11ea-9cab-83a744431d3f.png)

As discussed in Slack, do we want the full URL in this email so people can copy/paste if needed?

**Comment by csprayregen** [comment]
@katelovescode everything noted above has been addressed! Will close this after we resolve that one last question in Slack re spanish translation

**Comment by katelovescode** [comment]
> @katelovescode everything noted above has been addressed! Will close this after we resolve that one last question in Slack re spanish translation

@csprayregen these translations should be deployed now.
