### ISSUE TITLE
Pre-launch tweaks to NE spreadsheet

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#944]
## ✨ What new feature do you want to see?
- [x] Add email address as a field in the onboarding spreadsheet to S3
- [x] Confirm we are ready to accept WS schedule data format 
- [x] Confirm we are ready to accept WS attendance data format --> per Jon, final step is to determine child identifier based on conversation with WS. Currently this is using child ID (from DHS?), but we can update this to name or possibly something else based on WS answer. 
- [x] Is the zip code field doing anything? --> per Jon, no, from an old template. CS: update, we are actually using this to determine state
- [x] How does the spreadsheet know which rate tables to pull from, since I’m not adding license type as a field? Are we assuming they are license type family child care I or II? --> per Jon, yes, that is the assumption

## 🖍️ Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by JonErvin** [comment]
Updates for part 2: Confirm we are ready to accept WS Schedule data. (updated in testing, NECC pilot, and docs)

- Schedule Data (input): Weekday datatype is integer not string
- Schedule - Units Calculation (calc): New field "Day of Week" to turn integer into string of format "Monday".  Per WS, Monday = 1, Friday = 5.
- Other Lookup Tables (reference): Added a Table 7: Wonderschool day of week to make explicit that Monday = 1.

**Comment by katelovescode** [comment]
@csprayregen @JonErvin noticed one more missing field: right now we're requiring a license type in the db but we don't have that option in the spreadsheet.  We can either remove the requirement or add it into the spreadsheet.  For IL (currently) we're not using it for calculations, but if it's used in the spreadsheet for dashboard calculations, we'll need it in this onboarding sheet too.

Updating as I code for onboarding:

|field|format|required in db|options|implemented in spreadsheet|implemented in code|
|----|----|----|----|----|----|
|Full Name|string, spaces okay|required||✅|✅|
|Client Id|string|optional||✅|🚧|
|Provider Name|string|required||✅|✅|
|Date of birth (required)|string|required||✅|✅|
|Enrolled in School (Kindergarten or later)|dropdown of strings|optional|Yes, No|✅|🚧|
|Case number|string|optional||✅|✅|
|Authorized full day units|integer|optional||✅|🚧|
|Authorized hourly units|integer|optional||✅|🚧|
|Effective on|date string|required||✅|✅|
|Expires on|date string|required||✅|✅|
|Special Needs Rate?|dropdown of strings|optional|Yes, No|✅|🚧|
|Special Needs Daily Rate|decimal|optional||✅|🚧|
|Special Needs Hourly Rate|decimal|optional||✅|🚧|
|Provider Email|string|required||✅|✅|
|Business License|string|required||🚨|✅|
|Business Zip Code|string|required||✅|✅|
|Business County|string|required||✅|✅|
|Business QRIS rating|string|optional||✅|✅|
|Accredited|dropdown of strings|optional|Yes, No|✅|🚧|
|Approval #1 - Family Fee|decimal|optional||✅|🚧|
|Approval #1 - Begin Date|date string|optional||✅|🚧|
|Approval #1 - End Date|date string|optional||✅|🚧|
|Approval #1 - Allocated Family Fee|decimal|optional||✅|🚧|
|Approval #2 - Family Fee|decimal|optional||✅|🚧|
|Approval #2 - Begin Date|date string|optional||✅|🚧|
|Approval #2 - End Date|date string|optional||✅|🚧|
|Approval #2 - Allocated Family Fee|decimal|optional||✅|🚧|
|Approval #3 - Family Fee|decimal|optional||✅|🚧|
|Approval #3 - Begin Date|date string|optional||✅|🚧|
|Approval #3 - End Date|date string|optional||✅|🚧|
|Approval #3 - Allocated Family Fee|decimal|optional||✅|🚧|
|Approval #4 - Family Fee|decimal|optional||✅|🚧|
|Approval #4 - Begin Date|date string|optional||✅|🚧|
|Approval #4 - End Date|date string|optional||✅|🚧|
|Approval #4 - Allocated Family Fee|decimal|optional||✅|🚧|
|Approval #5 - Family Fee|decimal|optional||✅|🚧|
|Approval #5 - Begin Date|date string|optional||✅|🚧|
|Approval #5 - End Date|date string|optional||✅|🚧|
|Approval #5 - Allocated Family Fee|decimal|optional||✅|🚧|

**Comment by csprayregen** [comment]
@JonErvin I am getting this data from NECC, so if you could add it as a field in the Provider Data tab, and then have it pulled into the inputs to S3 tab, that would be great. Ideally, please put that field between business county and QRIS rating.

**Comment by csprayregen** [comment]
Noting based on conversation with Kate tonight that business license type only needs to be a string - there are no other validations on this for now.

**Comment by JonErvin** [comment]
Should be good to go now @csprayregen @katelovescode
