### ISSUE TITLE
Add new attendance risk category for Nebraska

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#951]
> * There's actually a fourth option for an attendance risk that's "ahead_of_schedule."  It's essentially the opposite of "at_risk" where a child is attending much more frequently than his/her schedule and runs the risk of exceeding limits (but has not yet exceeded limits).

This will need to be updated in the front end status constants, I believe.

**Comment by JonErvin** [comment]
@katelovescode just removed the "hours" and "days" units.  Should be good to go!
