### ISSUE TITLE
When I create an account, the confirmation communications include the correct email address

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#955]
## ✨ What new feature do you want to see?
The account confirmation emails now come from team@pieforproviders.com - our communications should reflect that. 

## 🧶 Acceptance Criteria
- [x] The confirmation message (screenshot below) says "Add team@pieforproviders.com..." not kate@pieforproviders.com
- [x] The email I receive with the confirmation link says, "Questions? Email team@pieforproviders.com" not kate@pieforproviders.com
- [x] The above criteria work in English and Spanish
- [x] Check for accessibility 

## 🖍️ Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

## 🥧 Additional context
Current confirmation screen after creating an account
![image](https://user-images.githubusercontent.com/26717304/108537476-43f07580-72a3-11eb-9246-0c0cd74131c9.png)

Current email copy: 
![image](https://user-images.githubusercontent.com/26717304/108537533-579bdc00-72a3-11eb-969b-d7b86e09b7c9.png)

**Comment by nneka-nu** [comment]
I'd like to work on this issue, @katelovescode .

**Comment by cjhaddad** [comment]
@nneka-nu made changes to make this show appropriately for the frontend. but @katelovescode can you confirm what backend changes may need to be made for this ticket?
