### ISSUE TITLE
On my NE dashboard, family fees are subtracted from revenue estimates 

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#973]
## 🖍️ Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**

**Comment by JTBassett** [comment]
@JonErvin Just want to check on this - in the "Summary by Child" tab, would it be helpful to add another column for "Total Earned Revenue les family fees" to append to the last four columns as a reference? Maybe that is unnecessary, but otherwise the calculation looks good to me!

**Comment by JonErvin** [comment]
Nice thanks @JTBassett!  Will do.  This will be the same as Total Earned Attendance for now, but once we have non-attendance revenue this will be an important number.
