### ISSUE TITLE
As a user, I can log into my account

### ISSUE THREAD

**Issue by csprayregen** [pieforproviders/pieforproviders#98]
## ✨ What new feature do you want to see?
I can see the account log in page, enter my email address and password, and then log in

## 🧶 Acceptance Criteria
If my email or password have not been filled in, I see an error state after clicking submit
If my email and password do not match, I see an error state after clicking submit
If I enter the correct information, I can click submit and log into my account

## 🖍️ Implementation Details
* Users will have to be confirmed before they can log in; you can do that by running `User.find_by(email: [your_test_user_email]).confirm` in the console.
* Probably makes sense to redirect to a page that requires auth to redirect to, as well as showing data that requires auth as well

## 🥧 Additional context
Figma link: https://www.figma.com/file/uCveVQQnYcw3MsenD1PNcG/P4P-2.0?node-id=420%3A163

## Testing Instructions
- visit pie-staging.herokuapp.com
- you should be redirected to the /login route
- log in with the user you created before (if you don't remember the password, you'll probably need to create a new user at /signup and have Kate confirm it, because we don't have a reset password flow set up)

**Comment by rebeccakarasiktw** [comment]
Can we add some padding to the word "English" on the top right of the page? (32 pix from the top)

**Comment by katelovescode** [comment]
Padding was added and approved

**Comment by csprayregen** [comment]
@katelovescode sorry, reopening this because I don't think we actually QA-d the functionality. 

- [ ] If my email or password have not been filled in, I see an error state after clicking submit
- [ ] If my email and password do not match, I see an error state after clicking submit
- [ ] If I enter the correct information, I can click submit and log into my account
